import type { ComponentEntry } from "../types";

/** Backgrounds — full-canvas / ambient visual systems. */
export const backgrounds: ComponentEntry[] = [
	{
		slug: "threads",
		name: "Threads",
		category: "Backgrounds",
		tier: "free",
		description:
			"A woven field of flowing threads rendered on a WebGL line shader.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/threads/Threads.tsx",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Line color of the threads.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.5,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Wave displacement strength.",
			},
			{
				name: "distance",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 1.5,
				step: 0.05,
				description: "Z-spread between the layered lines.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation of the field.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity of the threads.",
			},
			{
				name: "enableMouseInteraction",
				kind: "boolean",
				default: true,
				description: "Let the cursor bend the field.",
			},
		],
	},
	{
		slug: "grainient",
		name: "Grainient",
		category: "Backgrounds",
		tier: "free",
		description:
			"An animated grainy mesh-gradient rendered on a WebGL2 shader.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/grainient/Grainient.tsx",
			},
		],
		props: [
			{
				name: "timeSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Overall animation speed.",
			},
			{
				name: "warpStrength",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Domain-warp intensity.",
			},
			{
				name: "warpFrequency",
				kind: "number",
				default: 2,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Warp detail frequency.",
			},
			{
				name: "blendSoftness",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Softness of the gradient blend.",
			},
			{
				name: "noiseScale",
				kind: "number",
				default: 1.2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Scale of the underlying noise.",
			},
			{
				name: "grainAmount",
				kind: "number",
				default: 0.12,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Film-grain intensity.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1,
				min: 0.5,
				max: 2,
				step: 0.05,
				description: "Output contrast.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1.1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Output saturation.",
			},
			{
				name: "zoom",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.05,
				description: "Camera zoom.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#a855f7",
				description: "First gradient color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#6d28d9",
				description: "Second gradient color.",
			},
			{
				name: "color3",
				kind: "color",
				default: "#22d3ee",
				description: "Third gradient color.",
			},
		],
	},
	{
		slug: "light-rays",
		name: "LightRays",
		category: "Backgrounds",
		tier: "free",
		description:
			"Volumetric god-rays from a configurable origin, optionally mouse-following.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/light-rays/LightRays.tsx",
			},
		],
		props: [
			{
				name: "raysColor",
				kind: "color",
				default: "#a855f7",
				description: "Ray color.",
			},
			{
				name: "raysSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "lightSpread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread of the rays.",
			},
			{
				name: "rayLength",
				kind: "number",
				default: 2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Length of the rays.",
			},
			{
				name: "pulsating",
				kind: "boolean",
				default: false,
				description: "Pulse the ray intensity.",
			},
			{
				name: "fadeDistance",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 2,
				step: 0.05,
				description: "Distance over which rays fade.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "followMouse",
				kind: "boolean",
				default: true,
				description: "Aim the rays toward the cursor.",
			},
			{
				name: "mouseInfluence",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the cursor steers the rays.",
			},
			{
				name: "noiseAmount",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Noise texture over the rays.",
			},
			{
				name: "distortion",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wavy distortion of the rays.",
			},
		],
	},
	{
		slug: "gradual-blur",
		name: "GradualBlur",
		category: "Backgrounds",
		tier: "free",
		description:
			"Progressive edge blur — stacked backdrop-filter layers dissolve content toward a chosen edge.",
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/gradual-blur/GradualBlur.tsx",
			},
		],
		props: [
			{
				name: "position",
				kind: "enum",
				default: "bottom",
				options: ["top", "bottom", "left", "right"],
				description: "Edge the blur attaches to.",
			},
			{
				name: "strength",
				kind: "number",
				default: 1,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Base blur multiplier applied to every layer.",
			},
			{
				name: "divCount",
				label: "Div Count",
				kind: "number",
				default: 5,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of stacked blur layers (higher = smoother ramp).",
			},
			{
				name: "exponential",
				kind: "boolean",
				default: true,
				description: "Exponential progression for a stronger blur at the edge.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Opacity applied to each blur layer.",
			},
			{
				name: "target",
				kind: "enum",
				default: "parent",
				options: ["parent", "page"],
				description: "Attach to the parent container or the viewport (fixed).",
			},
			{
				name: "tinted",
				kind: "boolean",
				default: false,
				description: "Wash the blurred edge with a faint amethyst accent.",
			},
		],
	},
	{
		slug: "side-rays",
		name: "SideRays",
		category: "Backgrounds",
		tier: "pro",
		description:
			"Corner-anchored two-color light rays with adjustable tilt and blend.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/side-rays/SideRays.tsx",
			},
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "rayColor1",
				kind: "color",
				default: "#a855f7",
				description: "First ray color.",
			},
			{
				name: "rayColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Second ray color.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 2,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Ray brightness.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread.",
			},
			{
				name: "tilt",
				kind: "number",
				default: 0,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Tilt of the ray bundle.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "blend",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Blend between the two colors.",
			},
			{
				name: "falloff",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Edge falloff.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
		],
	},
	{
		slug: "dot-field",
		name: "DotField",
		category: "Backgrounds",
		tier: "free",
		description:
			"An interactive dot grid that bulges and glows around the cursor.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/dot-field/DotField.tsx",
			},
		],
		props: [
			{
				name: "dotRadius",
				kind: "number",
				default: 1.5,
				min: 0.5,
				max: 5,
				step: 0.5,
				unit: "px",
				description: "Radius of each dot.",
			},
			{
				name: "dotSpacing",
				kind: "number",
				default: 25,
				min: 10,
				max: 50,
				step: 1,
				unit: "px",
				description: "Spacing between dots.",
			},
			{
				name: "cursorRadius",
				kind: "number",
				default: 500,
				min: 100,
				max: 800,
				step: 10,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "cursorForce",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Strength of the cursor push.",
			},
			{
				name: "bulgeOnly",
				kind: "boolean",
				default: true,
				description: "Bulge toward the cursor only (no repel).",
			},
			{
				name: "bulgeStrength",
				kind: "number",
				default: 67,
				min: 0,
				max: 150,
				step: 1,
				description: "Bulge displacement strength.",
			},
			{
				name: "glowRadius",
				kind: "number",
				default: 160,
				min: 0,
				max: 400,
				step: 10,
				unit: "px",
				description: "Radius of the cursor glow.",
			},
			{
				name: "sparkle",
				kind: "boolean",
				default: false,
				description: "Add a sparkle shimmer.",
			},
			{
				name: "waveAmplitude",
				kind: "number",
				default: 0,
				min: 0,
				max: 20,
				step: 0.5,
				description: "Ambient wave motion.",
			},
			{
				name: "gradientFrom",
				kind: "color",
				default: "#a855f7",
				description: "Dot gradient start.",
			},
			{
				name: "gradientTo",
				kind: "color",
				default: "#b497cf",
				description: "Dot gradient end.",
			},
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Cursor glow color.",
			},
		],
	},
	{
		slug: "strands",
		name: "Strands",
		category: "Backgrounds",
		tier: "pro",
		description:
			"Glowing wavy light-strands with an optional glass refraction lens.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/strands/Strands.tsx",
			},
		],
		props: [
			{
				name: "count",
				kind: "number",
				default: 13,
				min: 3,
				max: 40,
				step: 1,
				description: "Number of strands.",
			},
			{
				name: "scale",
				label: "size",
				kind: "number",
				default: 1.1,
				min: 0.5,
				max: 3,
				step: 0.05,
				description:
					"Field size — lower zooms out, higher magnifies the strands.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wave amplitude.",
			},
			{
				name: "waviness",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Waviness of the strands.",
			},
			{
				name: "thickness",
				kind: "number",
				default: 1.55,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Strand thickness.",
			},
			{
				name: "strandWidth",
				label: "width %",
				kind: "number",
				default: 100,
				min: 10,
				max: 100,
				step: 1,
				description:
					"Horizontal reach as a percentage — 100 spans to the glass rim.",
			},
			{
				name: "glow",
				kind: "number",
				default: 0.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glow strength.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1.65,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Vertical spread.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color intensity.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
			{
				name: "glass",
				kind: "boolean",
				default: true,
				description: "Overlay a glass refraction lens.",
			},
			{
				name: "refraction",
				kind: "number",
				default: 1.3,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glass refraction strength.",
			},
			{
				name: "dispersion",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Chromatic dispersion.",
			},
		],
	},
	{
		slug: "ribbons",
		name: "Ribbons",
		category: "Backgrounds",
		tier: "pro",
		description: "Flowing translucent ribbons drifting across a canvas.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ribbons/Ribbons.tsx",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#0037ff",
				description: "Ribbon color.",
			},
			{
				name: "colorAlpha",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Ribbon opacity.",
			},
			{
				name: "ribbonCount",
				kind: "number",
				default: 4,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of ribbons on screen.",
			},
			{
				name: "strokeSize",
				kind: "number",
				default: 1,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Outline thickness.",
			},
			{
				name: "horizontalSpeed",
				kind: "number",
				default: 200,
				min: 10,
				max: 300,
				step: 10,
				description: "Drift speed across the canvas.",
			},
			{
				name: "parallaxAmount",
				kind: "number",
				default: -0.2,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Scroll parallax factor.",
			},
			{
				name: "verticalPosition",
				kind: "enum",
				default: "random",
				options: ["top", "middle", "bottom", "random"],
				description: "Where ribbons spawn vertically.",
			},
			{
				name: "animateSections",
				kind: "boolean",
				default: false,
				description: "Wiggle ribbon segments over time.",
			},
		],
	},
	{
		slug: "world-map-ascii",
		name: "WorldMap ASCII",
		category: "Backgrounds",
		tier: "pro",
		description:
			"A dot-matrix world map whose particles scatter from the cursor.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/world-map-ascii/WorldMapAscii.tsx",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Particle color.",
			},
			{
				name: "particleSize",
				kind: "number",
				default: 0.7,
				min: 0.3,
				max: 3,
				step: 0.1,
				unit: "px",
				description: "Dot radius.",
			},
			{
				name: "density",
				kind: "number",
				default: 8,
				min: 1,
				max: 9,
				step: 1,
				description: "Particle density — higher packs more particles.",
			},
			{
				name: "mouseRadius",
				kind: "number",
				default: 80,
				min: 0,
				max: 300,
				step: 10,
				unit: "px",
				description: "Cursor interaction radius; 0 disables the scatter.",
			},
			{
				name: "drift",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Idle wobble amplitude.",
			},
		],
	},
];
