import type { ComponentEntry, Variant } from "../types";

/** Upstream credit for entries adapted from React Bits (reactbits.dev, MIT).
 *  Rendered on the component page; the served source is comment-stripped, so
 *  the visible credit lives here, not in a code header. */
const REACTBITS = {
	name: "React Bits",
	url: "https://reactbits.dev",
};

/** lib/utils.ts ships with every entry whose source imports `cn`. Its own
 *  packages (clsx, tailwind-merge) are the host entry's to declare — the check
 *  walks into this file and finds them there (§V41). */
const UTILS_VARIANT: Variant = {
	lang: "ts",
	style: "tailwind",
	file: "lib/utils.ts",
	role: "util",
	label: "utils.ts",
};

/** Backgrounds — full-canvas / ambient visual systems. */
export const backgrounds: ComponentEntry[] = [
	{
		slug: "waves",
		name: "Waves",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"A woven field of flowing waves rendered on a WebGL line shader.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation", "Hardware acceleration"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/waves/waves.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Line color of the waves.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.5,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Wave displacement strength.",
			},
			{
				name: "distance",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 1.5,
				step: 0.05,
				description: "Z-spread between the layered lines.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation of the field.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity of the waves.",
			},
			{
				name: "enableMouseInteraction",
				kind: "boolean",
				default: true,
				description: "Let the cursor bend the field.",
			},
		],
	},
	{
		slug: "grainient",
		attribution: REACTBITS,
		name: "Grainient",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"An animated grainy mesh-gradient rendered on a WebGL2 shader.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation", "Compositing"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/grainient/grainient.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "timeSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Overall animation speed.",
			},
			{
				name: "warpStrength",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Domain-warp intensity.",
			},
			{
				name: "warpFrequency",
				kind: "number",
				default: 2,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Warp detail frequency.",
			},
			{
				name: "blendSoftness",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Softness of the gradient blend.",
			},
			{
				name: "noiseScale",
				kind: "number",
				default: 1.2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Scale of the underlying noise.",
			},
			{
				name: "grainAmount",
				kind: "number",
				default: 0.12,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Film-grain intensity.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1,
				min: 0.5,
				max: 2,
				step: 0.05,
				description: "Output contrast.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1.1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Output saturation.",
			},
			{
				name: "zoom",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.05,
				description: "Camera zoom.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#f754f1",
				description: "First gradient color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#6d28d9",
				description: "Second gradient color.",
			},
			{
				name: "color3",
				kind: "color",
				default: "#22d3ee",
				description: "Third gradient color.",
			},
		],
	},
	{
		slug: "light-rays",
		attribution: REACTBITS,
		name: "LightRays",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"Volumetric god-rays from a configurable origin, optionally mouse-following.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation", "Hover effect"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/light-rays/light-rays.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "raysColor",
				kind: "color",
				default: "#a855f7",
				description: "Ray color.",
			},
			{
				name: "raysSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "lightSpread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread of the rays.",
			},
			{
				name: "rayLength",
				kind: "number",
				default: 2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Length of the rays.",
			},
			{
				name: "pulsating",
				kind: "boolean",
				default: false,
				description: "Pulse the ray intensity.",
			},
			{
				name: "fadeDistance",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 2,
				step: 0.05,
				description: "Distance over which rays fade.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "followMouse",
				kind: "boolean",
				default: true,
				description:
					"Aim the rays toward the pointer. While on, the overlay claims touch input (a finger drag steers the rays instead of scrolling) and so intercepts clicks beneath it; off restores click-through.",
			},
			{
				name: "mouseInfluence",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the cursor steers the rays.",
			},
			{
				name: "noiseAmount",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Noise texture over the rays.",
			},
			{
				name: "distortion",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wavy distortion of the rays.",
			},
		],
	},
	{
		slug: "mask-blur",
		name: "MaskBlur",
		category: "Backgrounds",
		tier: "free",
		description:
			"Progressive edge blur — stacked backdrop-filter layers dissolve content toward a chosen edge.",
		cookbook: ["Blur", "Mask", "Compositing"],
		dependencies: ["motion", "clsx", "tailwind-merge"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/mask-blur/mask-blur.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "position",
				kind: "enum",
				default: "bottom",
				options: ["top", "bottom", "left", "right"],
				description: "Edge the blur attaches to.",
			},
			{
				name: "strength",
				kind: "number",
				default: 1,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Base blur multiplier applied to every layer.",
			},
			{
				name: "divCount",
				kind: "number",
				default: 5,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of stacked blur layers (higher = smoother ramp).",
			},
			{
				name: "exponential",
				kind: "boolean",
				default: true,
				description: "Exponential progression for a stronger blur at the edge.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Opacity applied to each blur layer.",
			},
			{
				name: "target",
				kind: "enum",
				default: "parent",
				options: ["parent", "page"],
				description: "Attach to the parent container or the viewport (fixed).",
			},
			{
				name: "tinted",
				kind: "boolean",
				default: false,
				description: "Wash the blurred edge with a faint amethyst accent.",
			},
		],
	},
	{
		slug: "side-rays",
		attribution: REACTBITS,
		name: "SideRays",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Corner-anchored two-color light rays with adjustable tilt and blend.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/side-rays/side-rays.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "rayColor1",
				kind: "color",
				default: "#a855f7",
				description: "First ray color.",
			},
			{
				name: "rayColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Second ray color.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 2,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Ray brightness.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread.",
			},
			{
				name: "tilt",
				kind: "number",
				default: 0,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Tilt of the ray bundle.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "blend",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Blend between the two colors.",
			},
			{
				name: "falloff",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Edge falloff.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
		],
	},
	{
		slug: "dot-field",
		attribution: REACTBITS,
		name: "DotField",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"An interactive dot grid that bulges and glows around the cursor.",
		dependencies: [],
		cookbook: ["Hover effect", "Idle animation", "Compositing"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/dot-field/dot-field.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "dotRadius",
				kind: "number",
				default: 1.5,
				min: 0.5,
				max: 5,
				step: 0.5,
				unit: "px",
				description: "Radius of each dot.",
			},
			{
				name: "dotSpacing",
				kind: "number",
				default: 25,
				min: 10,
				max: 50,
				step: 1,
				unit: "px",
				description: "Spacing between dots.",
			},
			{
				name: "cursorRadius",
				kind: "number",
				default: 500,
				min: 100,
				max: 800,
				step: 10,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "cursorForce",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Strength of the cursor push.",
			},
			{
				name: "bulgeOnly",
				kind: "boolean",
				default: true,
				description: "Bulge toward the cursor only (no repel).",
			},
			{
				name: "bulgeStrength",
				kind: "number",
				default: 67,
				min: 0,
				max: 150,
				step: 1,
				description: "Bulge displacement strength.",
			},
			{
				name: "glowRadius",
				kind: "number",
				default: 160,
				min: 0,
				max: 400,
				step: 10,
				unit: "px",
				description: "Radius of the cursor glow.",
			},
			{
				name: "sparkle",
				kind: "boolean",
				default: false,
				description: "Add a sparkle shimmer.",
			},
			{
				name: "waveAmplitude",
				kind: "number",
				default: 0,
				min: 0,
				max: 20,
				step: 0.5,
				description: "Ambient wave motion.",
			},
			{
				name: "gradientFrom",
				kind: "color",
				default: "#a855f7",
				description: "Dot gradient start.",
			},
			{
				name: "gradientTo",
				kind: "color",
				default: "#b497cf",
				description: "Dot gradient end.",
			},
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Cursor glow color.",
			},
		],
	},
	{
		slug: "strands",
		attribution: REACTBITS,
		name: "Strands",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Glowing wavy light-strands with an optional glass refraction lens.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation", "Blur"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/strands/strands.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "count",
				kind: "number",
				default: 13,
				min: 3,
				max: 40,
				step: 1,
				description: "Number of strands.",
			},
			{
				name: "scale",
				kind: "number",
				default: 0.9,
				min: 0.5,
				max: 3,
				step: 0.05,
				description:
					"Field size — lower zooms out, higher magnifies the strands.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wave amplitude.",
			},
			{
				name: "waviness",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Waviness of the strands.",
			},
			{
				name: "thickness",
				kind: "number",
				default: 1.55,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Strand thickness.",
			},
			{
				name: "strandWidth",
				kind: "number",
				default: 100,
				min: 10,
				max: 100,
				step: 1,
				description:
					"Horizontal reach as a percentage — 100 spans to the glass rim.",
			},
			{
				name: "glow",
				kind: "number",
				default: 0.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glow strength.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1.65,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Vertical spread.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color intensity.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
			{
				name: "glass",
				kind: "boolean",
				default: true,
				description: "Overlay a glass refraction lens.",
			},
			{
				name: "refraction",
				kind: "number",
				default: 1.3,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glass refraction strength.",
			},
			{
				name: "dispersion",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Chromatic dispersion.",
			},
		],
	},
	{
		slug: "ribbons",
		attribution: REACTBITS,
		name: "Ribbons",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description: "Flowing translucent ribbons drifting across a canvas.",
		dependencies: [],
		cookbook: ["Loop", "Float", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ribbons/ribbons.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#0037ff",
				description: "Ribbon color.",
			},
			{
				name: "colorAlpha",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Ribbon opacity.",
			},
			{
				name: "ribbonCount",
				kind: "number",
				default: 4,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of ribbons on screen.",
			},
			{
				name: "strokeSize",
				kind: "number",
				default: 1,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Outline thickness.",
			},
			{
				name: "horizontalSpeed",
				kind: "number",
				default: 200,
				min: 10,
				max: 300,
				step: 10,
				description: "Drift speed across the canvas.",
			},
			{
				name: "parallaxAmount",
				kind: "number",
				default: -0.2,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Scroll parallax factor.",
			},
			{
				name: "verticalPosition",
				kind: "enum",
				default: "random",
				options: ["top", "middle", "bottom", "random"],
				description: "Where ribbons spawn vertically.",
			},
			{
				name: "animateSections",
				kind: "boolean",
				default: false,
				description: "Wiggle ribbon segments over time.",
			},
		],
	},
	{
		slug: "world-map-ascii",
		name: "WorldMap ASCII",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A dot-matrix world map whose particles scatter from the cursor.",
		dependencies: [],
		cookbook: ["Hover effect", "Idle animation", "Loop"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/world-map-ascii/world-map-ascii.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Particle color.",
			},
			{
				name: "particleSize",
				kind: "number",
				default: 0.7,
				min: 0.3,
				max: 3,
				step: 0.1,
				unit: "px",
				description: "Dot radius.",
			},
			{
				name: "density",
				kind: "number",
				default: 8,
				min: 1,
				max: 9,
				step: 1,
				description: "Particle density — higher packs more particles.",
			},
			{
				name: "mouseRadius",
				kind: "number",
				default: 80,
				min: 0,
				max: 300,
				step: 10,
				unit: "px",
				description: "Cursor interaction radius; 0 disables the scatter.",
			},
			{
				name: "drift",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Idle wobble amplitude.",
			},
		],
	},
	{
		slug: "constellation",
		name: "Constellation",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A constellation network — drifting particles link by proximity, chase and flee the cursor, and glow.",
		dependencies: [],
		cookbook: ["Idle animation", "Hover effect", "Float", "Loop"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/constellation/constellation.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "density",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 2.5,
				step: 0.1,
				description: "Particle density relative to area.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.8,
				min: 0.1,
				max: 3,
				step: 0.05,
				description: "Top drift speed of particles.",
			},
			{
				name: "connectDistance",
				kind: "number",
				default: 120,
				min: 40,
				max: 250,
				step: 5,
				unit: "px",
				description: "Max distance for particle-to-particle lines.",
			},
			{
				name: "cursorDistance",
				kind: "number",
				default: 150,
				min: 0,
				max: 300,
				step: 10,
				unit: "px",
				description: "Cursor link + repel radius; 0 disables.",
			},
			{
				name: "repelForce",
				kind: "number",
				default: 2,
				min: 0,
				max: 6,
				step: 0.5,
				description: "Push strength inside the cursor radius.",
			},
			{
				name: "lineOpacity",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Opacity multiplier on connection lines.",
			},
			{
				name: "glow",
				kind: "number",
				default: 10,
				min: 0,
				max: 30,
				step: 1,
				description: "Particle glow blur.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#a855f7",
				description: "First particle color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#ff9207",
				description: "Second particle color.",
			},
			{
				name: "color3",
				kind: "color",
				default: "#22d3ee",
				description:
					"Third particle color — lines between mixed pairs blend as gradients.",
			},
		],
	},
	{
		slug: "plus-grid",
		name: "PlusGrid",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A canvas field of '+' glyphs — scroll or pointer motion injects a traveling wave that ripples and decays across the grid.",
		cookbook: ["Ripple", "Scroll-driven animation", "Hover effect", "Loop"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/plus-grid/plus-grid.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "gapX",
				kind: "number",
				default: 42,
				min: 24,
				max: 96,
				step: 2,
				unit: "px",
				description: "Horizontal gap between glyphs.",
			},
			{
				name: "gapY",
				kind: "number",
				default: 38,
				min: 24,
				max: 96,
				step: 2,
				unit: "px",
				description: "Vertical gap between glyphs.",
			},
			{
				name: "fontSize",
				kind: "number",
				default: 20,
				min: 10,
				max: 36,
				step: 1,
				unit: "px",
				description: "Glyph size.",
			},
			{
				name: "baseOpacity",
				kind: "number",
				default: 0.5,
				min: 0.05,
				max: 1,
				step: 0.05,
				description: "Resting opacity of the field.",
			},
			{
				name: "waveAmplitude",
				kind: "number",
				default: 12,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Peak displacement at full wave energy.",
			},
			{
				name: "waveFrequency",
				kind: "number",
				default: 0.35,
				min: 0.05,
				max: 1,
				step: 0.05,
				description: "Ripple tightness across columns.",
			},
			{
				name: "waveDecay",
				kind: "number",
				default: 0.96,
				min: 0.9,
				max: 0.995,
				step: 0.005,
				description: "Energy decay per tick — low snaps back, high lingers.",
			},
			{
				name: "autoPulse",
				kind: "boolean",
				default: true,
				description: "Fire a wave pulse every few seconds.",
			},
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Glyph color.",
			},
		],
	},
	{
		slug: "barcode",
		name: "Barcode",
		category: "Backgrounds",
		tier: "free",
		description:
			"A procedural barcode whose bars light up like piano notes — looping on autoplay or scrubbed by scroll.",
		dependencies: ["gsap"],
		cookbook: [
			"Loop",
			"Scroll-driven animation",
			"Stagger",
			"Stepped animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/barcode/barcode.tsx",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "autoplay",
				options: ["autoplay", "scrub"],
				description:
					"Autoplay loops the note timeline; scrub ties it to scroll position.",
			},
			{
				name: "restOpacity",
				kind: "number",
				default: 0.6,
				min: 0.1,
				max: 1,
				step: 0.05,
				description: "Opacity a bar settles at after its note.",
			},
			{
				name: "peakOpacity",
				kind: "number",
				default: 1,
				min: 0.5,
				max: 1,
				step: 0.05,
				description: "Opacity at the peak of a note strike.",
			},
			{
				name: "noteDuration",
				kind: "number",
				default: 1.6,
				min: 0.4,
				max: 4,
				step: 0.1,
				unit: "s",
				description: "Length of one note's swell and fade.",
			},
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0.25,
				max: 3,
				step: 0.05,
				description: "Playback rate of the autoplay loop.",
				disabledWhen: { prop: "mode", equals: "scrub" },
			},
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Bar color.",
			},
		],
	},
	{
		slug: "aurora",
		name: "Aurora",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"Flowing curtains of amethyst light drifting across a starless night sky — an fbm-warped WebGL2 field where luminous bands ripple, fold, and dissolve into fine grain, like a polar aurora seen from the dark side of the world.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation", "Float"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/aurora/aurora.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "baseColor",
				kind: "color",
				default: "#05010a",
				description: "Deep background the curtains glow against.",
			},
			{
				name: "auroraColor",
				kind: "color",
				default: "#a855f7",
				description: "Primary amethyst light of the bands.",
			},
			{
				name: "auroraColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Secondary tint the curtain edges shift toward.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Drift speed of the flowing bands.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description: "Overall brightness of the aurora.",
			},
			{
				name: "bands",
				kind: "number",
				default: 3,
				min: 1,
				max: 6,
				step: 1,
				description: "Number of layered light curtains.",
			},
			{
				name: "warp",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Turbulence of the fbm domain-warp folding the curtains.",
			},
			{
				name: "coverage",
				kind: "number",
				default: 0.6,
				min: 0.2,
				max: 1,
				step: 0.05,
				description: "Vertical reach of the curtains up the sky.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.08,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Subtle film grain over the field.",
			},
		],
	},
	{
		slug: "starfield",
		name: "Starfield",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Depth-layered stars drifting through a slow warp, each layer parallaxing at its own pace, with the occasional shooting star streaking a bright amethyst tail across the dark before the field settles back to its patient glimmer.",
		dependencies: [],
		cookbook: ["Parallax", "Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/starfield/starfield.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "starColor",
				kind: "color",
				default: "#ffffff",
				description: "Color of the star field.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "Tints a minority of stars and every shooting-star tail.",
			},
			{
				name: "density",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.1,
				description: "Star count relative to the pane area.",
			},
			{
				name: "layers",
				kind: "number",
				default: 3,
				min: 1,
				max: 5,
				step: 1,
				description:
					"Parallax depth layers — nearer layers drift faster and brighter.",
			},
			{
				name: "driftSpeed",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Speed of the slow directional warp across the field.",
			},
			{
				name: "twinkle",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Strength of per-star brightness twinkle.",
			},
			{
				name: "shootingStars",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How often streaks appear; 0 disables them.",
			},
			{
				name: "glow",
				kind: "number",
				default: 8,
				min: 0,
				max: 30,
				step: 1,
				unit: "px",
				description: "Glow blur around each star.",
			},
		],
	},
	{
		slug: "cinders",
		name: "Cinders",
		category: "Backgrounds",
		tier: "free",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"A dark field of embers and ash rising on the draft, aglow with amethyst.",
		dependencies: [],
		cookbook: ["Loop", "Float", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/cinders/cinders.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "emberCount",
				kind: "number",
				default: 140,
				min: 20,
				max: 400,
				step: 10,
				description: "Number of embers and ash motes in the field.",
			},
			{
				name: "riseSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Upward drift speed of the embers.",
			},
			{
				name: "turbulence",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Sideways sway as the motes rise.",
			},
			{
				name: "emberSize",
				kind: "number",
				default: 2,
				min: 0.5,
				max: 6,
				step: 0.5,
				unit: "px",
				description: "Base radius of each mote.",
			},
			{
				name: "glow",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Halo size around each spark.",
			},
			{
				name: "draftStrength",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				description: "How strongly the cursor stirs a draft.",
			},
			{
				name: "emberColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst ember glow color.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#0a0510",
				description: "Dark field the motes rise against.",
			},
		],
	},
	{
		slug: "shadowflame",
		name: "Shadowflame",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"A black flame with an amethyst core, its body folded from domain-warped noise.",
		dependencies: ["ogl"],
		cookbook: ["Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/shadowflame/shadowflame.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "coreColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst core of the flame.",
			},
			{
				name: "flameColor",
				kind: "color",
				default: "#630475",
				description: "Dark body of the black flame.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#05010a",
				description: "The void the flame rises against.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Rise speed of the flame.",
			},
			{
				name: "warp",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Domain-warp turbulence folding the flame.",
			},
			{
				name: "detail",
				kind: "number",
				default: 4,
				min: 1,
				max: 6,
				step: 1,
				description: "Number of noise octaves.",
			},
			{
				name: "shimmer",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Rising heat-shimmer distortion.",
			},
			{
				name: "height",
				kind: "number",
				default: 0.95,
				min: 0.2,
				max: 1.6,
				step: 0.05,
				description:
					"How far up the frame the flame reaches. Above 1 the taper never completes inside the frame, so the flame runs off the top edge instead of dying out.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Film grain over the field.",
			},
			{
				name: "flameWidth",
				kind: "number",
				default: 1.6,
				min: 0.3,
				max: 2,
				step: 0.05,
				description: "Horizontal spread of the flame.",
			},
			{
				name: "sparkCount",
				kind: "number",
				default: 60,
				min: 0,
				max: 200,
				step: 5,
				description: "Number of rising fire sparks (0 turns them off).",
			},
			{
				name: "sparkSize",
				kind: "number",
				default: 1.2,
				min: 0.5,
				max: 3,
				step: 0.1,
				unit: "px",
				description: "Size of each rising spark.",
			},
			{
				name: "sparkSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Rise speed of the sparks.",
			},
		],
	},
	{
		slug: "moire",
		name: "Moire",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-07-31",
		pausable: true,
		description:
			"Two lattices stacked at a fraction of a degree apart, beating against each other into live interference fringes. Every layer is band-limited in the shader, so what you see is the interference and not the sampling.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Idle animation",
			"Rotate",
			"Hover effect",
			"Hardware acceleration",
			"Linear",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/moire/moire.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "lattice",
				kind: "enum",
				default: "lines",
				options: ["lines", "grid", "dots", "rings"],
				description:
					"Shape of the two stacked layers. Lines beat into banding, grid into a woven plaid, dots into a rosette, rings into a bullseye that walks as you move.",
			},
			{
				name: "pitch",
				kind: "number",
				default: 9,
				min: 3,
				max: 40,
				step: 0.5,
				unit: "px",
				description:
					"Spacing of one lattice cell, in CSS pixels. Widen it and the beat frequency drops — the fringes get broader and travel slower even though nothing else changed.",
			},
			{
				name: "angle",
				kind: "number",
				default: 3.2,
				min: 0,
				max: 45,
				step: 0.1,
				unit: "°",
				description:
					"Rotation between the two layers. This is the whole effect: at 0° they stack invisibly, and a tenth of a degree either side sweeps the fringes across the entire field.",
			},
			{
				name: "drift",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"How far the angle and offset breathe on their own. 0 holds one still interference pattern, which is the honest setting to put behind body copy.",
			},
			{
				name: "separation",
				kind: "number",
				default: 6,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description:
					"Offset between the layers — a second beat axis independent of angle, so the fringes shift without rotating.",
			},
			{
				name: "thickness",
				kind: "number",
				default: 0.16,
				min: 0.05,
				max: 0.95,
				step: 0.01,
				description:
					"How much of a lattice cell is ink. Kept low by default so the field stays dark enough to put content on; push it past 0.5 and the two layers cover almost everything, which is a wall rather than a background.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 2.5,
				step: 0.05,
				unit: "×",
				description:
					"How hard the fringes clip toward light and dark, expanded around the pattern's own mean rather than mid-grey. Above about 1.6 the soft beat becomes hard banding.",
			},
			{
				name: "pointerInfluence",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"How much the cursor twists and shifts the top lattice. 0 leaves a field that ignores you entirely.",
			},
			{
				name: "inkColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst of the lattice lines themselves.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#08050e",
				description: "The dark field the two lattices sit on.",
			},
		],
	},
	{
		slug: "contour",
		name: "Contour",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			"Iso-lines of a drifting height field — a topographic map of terrain that will not hold still, with every line band-limited so what you see is the ground and not the sampling.",
		dependencies: ["ogl"],
		cookbook: [
			"Idle animation",
			"Hover effect",
			"Compositing",
			"Hardware acceleration",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/contour/contour.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "scale",
				kind: "number",
				default: 2.6,
				min: 0.5,
				max: 8,
				step: 0.1,
				description:
					"Feature size of the terrain. Low is a wide landscape read from altitude; high zooms into a single ridge. It changes how many lines cross the frame without changing how many the height range is cut into, which is the difference between flying higher and re-surveying.",
			},
			{
				name: "levels",
				kind: "number",
				default: 14,
				min: 4,
				max: 40,
				step: 1,
				description:
					"Contour steps across the height range — the vertical resolution of the map. This is the control that would alias: push it up and the spacing walks toward one line per pixel, where the line frequency beats against the sampling grid. The shader measures its own derivative and fades the lines out on any slope too steep to hold them, falling back to the elevation tint — which is what a paper map does when the interval is wrong for the terrain. The top of the range is soft, never false.",
			},
			{
				name: "warp",
				kind: "number",
				default: 0.55,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"How hard the field is domain-warped before the lines are cut from it. Zero gives smooth blobs that read as a heightmap of nothing in particular; high folds the terrain back over itself into ridges and cirques.",
			},
			{
				name: "drift",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1.5,
				step: 0.05,
				unit: "×",
				description:
					"Speed of the drift. The field is sampled at an offset that orbits rather than one that accumulates, so this changes the pace without ever handing the shader an unbounded number to lose precision on.",
			},
			{
				name: "lineWidth",
				kind: "number",
				default: 1.4,
				min: 0.4,
				max: 4,
				step: 0.1,
				unit: "px",
				description:
					"Line weight, held in pixels rather than field units — the map keeps the same hand at any scale, and the anti-aliasing band widens with it instead of being outrun by it.",
			},
			{
				name: "majorEvery",
				kind: "number",
				default: 5,
				min: 0,
				max: 10,
				step: 1,
				description:
					"Emphasise every Nth line, the way a real contour map indexes elevation. Zero draws them all alike, which is the setting that proves the point: without an index line the field reads as stripes rather than as ground.",
			},
			{
				name: "bandOpacity",
				kind: "number",
				default: 0.18,
				min: 0,
				max: 1,
				step: 0.02,
				description:
					"Tint of the band between two lines, by elevation. It is what turns a line drawing into a map — the eye reads height from the fill long before it counts the lines.",
			},
			{
				name: "pointerLift",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How much the cursor raises the ground under it. The lift is added to the height before the lines are cut, so the contours crowd around it exactly as they would around a real hill — nothing is drawn on top.",
			},
			{
				name: "inkColor",
				kind: "color",
				default: "#e9e7ef",
				description: "The contour lines and the elevation tint.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description:
					"The emphasised line. Only the index lines take it, so the accent counts elevation rather than colouring the whole drawing.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#0a0b0c",
				description: "The paper the map is drawn on.",
			},
		],
	},
	{
		slug: "cathode",
		name: "Cathode",
		category: "Backgrounds",
		tier: "free",
		addedAt: "2026-08-06",
		description:
			"A cathode-ray tube showing nothing worth watching: a beam that turns around at each edge, phosphor that holds after it has passed, and a hum bar rolling up the glass.",
		dependencies: ["ogl"],
		cookbook: ["Alternate (yoyo)", "Loop", "Idle animation", "Compositing"],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/cathode/cathode.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "signal",
				kind: "enum",
				default: "sweep",
				options: ["sweep", "bars", "snow", "grid"],
				description:
					"What the tube is showing. Sweep is a single beam that reverses at each edge rather than jumping back — a beam that wrapped would read as a dropped frame, one that turns around reads as a mechanism. The rest are the test patterns a set falls back to when there is nothing on the line.",
			},
			{
				name: "sweepSpeed",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				disabledWhen: { prop: "signal", equals: "bars" },
				description:
					"Speed of the beam across the face. At zero it parks and the phosphor settles, which is the clearest way to see what persistence is actually drawing.",
			},
			{
				name: "scanlineDensity",
				kind: "number",
				default: 2.2,
				min: 0.5,
				max: 6,
				step: 0.1,
				unit: "px",
				description:
					"Pixels per scanline. Below about two the grille is past Nyquist, and rather than aliasing into a pattern that moves when the window does, the modulation fades out — a small canvas loses its scanlines instead of gaining moiré.",
			},
			{
				name: "scanlineDepth",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How hard the scanlines and the aperture grille cut into the image. The grille rides at a third of this — a shadow mask you can actually resolve is a shadow mask that has stopped being a background.",
			},
			{
				name: "curvature",
				kind: "number",
				default: 0.18,
				min: 0,
				max: 0.6,
				step: 0.02,
				description:
					"Barrel distortion of the tube face. The glass edge is a soft falloff rather than a clip, because a hard rim aliases along its whole length and the rim is the one place the eye is guaranteed to go.",
			},
			{
				name: "bloom",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"Halation around bright areas. Four analytic taps of the signal rather than a blur pass — the signal has a closed form in every mode, so a glow costs arithmetic instead of a second render target.",
			},
			{
				name: "persistence",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 0.95,
				step: 0.05,
				description:
					"How long the phosphor holds after the beam has passed. Computed as an exponential in the distance already swept rather than by keeping the previous frame — which is what phosphor decay is, and it avoids the float render target that is the one thing the loop verifier cannot see through.",
			},
			{
				name: "rollSpeed",
				kind: "number",
				default: 0.25,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Speed of the hum bar rolling up the frame. It carries its own decay tail, so persistence still means something on a signal that never moves.",
			},
			{
				name: "chromaOffset",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "px",
				description:
					"Convergence error between the colour guns. Held in pixels and converted through the face width, so the fringe reads the same on a strip as on a full page.",
			},
			{
				name: "phosphorColor",
				kind: "color",
				default: "#7ef0c0",
				description:
					"The phosphor. Every signal borrows it except the colour bars, which carry their own hue — that is the whole point of a test card.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#050607",
				description: "The dead glass outside the picture.",
			},
		],
	},
	{
		slug: "dither",
		name: "Dither",
		category: "Backgrounds",
		tier: "free",
		addedAt: "2026-08-06",
		description:
			"A live field crushed to one bit through an ordered threshold matrix. The only background here that looks better the cheaper it gets, and the only one that runs the same on a decade-old laptop as on a workstation.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Stepped animation",
			"Idle animation",
			"Compositing",
			"Hardware acceleration",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/dither/dither.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "pattern",
				kind: "enum",
				default: "bayer8",
				options: ["bayer2", "bayer4", "bayer8", "halftone", "noise"],
				description:
					"Which threshold matrix decides each cell. Bayer is the ordered one — a fixed lattice, so the texture is stable and never crawls between frames. Halftone rotates the grid forty-five degrees and clusters instead of scattering, which is what a printing press does. Noise drops the lattice entirely and pays for it with a pattern that shimmers the moment anything moves.",
			},
			{
				name: "levels",
				kind: "number",
				default: 2,
				min: 2,
				max: 8,
				step: 1,
				description:
					"Tones per channel after quantisation. Two is the honest one-bit case. Above four this stops being dithering and starts being a slightly cheap gradient — worth dragging once to see exactly where the effect stops earning its name.",
			},
			{
				name: "pixelSize",
				kind: "number",
				default: 3,
				min: 1,
				max: 12,
				step: 1,
				unit: "px",
				description:
					"Size of one dither cell, held in CSS pixels rather than device pixels. Held in device pixels the grid would halve on a retina screen and the effect would vanish on exactly the displays people judge it on.",
			},
			{
				name: "field",
				kind: "enum",
				default: "plasma",
				options: ["plasma", "ridges", "tunnel", "drift"],
				description:
					"What is being quantised underneath. The dither is indifferent to it — that is the point of a threshold matrix — but the four differ sharply in how much smooth gradient they hand it, and a pattern only shows its character on a gradient.",
			},
			{
				name: "fieldSpeed",
				kind: "number",
				default: 0.3,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Rate the field evolves. At zero it parks, which is the clearest way to see the threshold matrix itself rather than the image passing through it.",
			},
			{
				name: "fieldScale",
				kind: "number",
				default: 2.4,
				min: 0.5,
				max: 8,
				step: 0.1,
				description:
					"Size of the field's features relative to the container. Small enough and the whole panel is one tone with nothing for the dither to resolve; large enough and every cell disagrees with its neighbour and the pattern turns to static.",
			},
			{
				name: "frameHold",
				kind: "number",
				default: 0,
				min: 0,
				max: 8,
				step: 1,
				unit: "frames",
				description:
					"How many frames the field is held before it advances. Zero runs at display rate; three gives the deliberate stutter of a machine that could not keep up. The frame is still drawn either way and the held time is spent in one go when the hold expires — so this is a look, not a saving, and not a speed control in disguise.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 3,
				step: 0.05,
				description:
					"Contrast applied around mid-grey before quantisation. This is the real control over how much of the field survives: at two levels there is exactly one threshold, so pushing contrast up does not brighten the image, it decides where the edge between black and white falls.",
			},
			{
				name: "inkColor",
				kind: "color",
				default: "#e8e4d8",
				description:
					"The colour a lit cell takes. Warm off-white rather than pure white on purpose — a true #ffffff against near-black is the one pairing that makes the grid buzz.",
			},
			{
				name: "paperColor",
				kind: "color",
				default: "#0b0b0d",
				description: "The colour an unlit cell takes.",
			},
		],
	},
	{
		slug: "turing",
		name: "Turing",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			"Gray-Scott reaction-diffusion on the GPU. Two reagents, four terms, and coral, labyrinths and colonies that settle and stop all fall out of the arithmetic — a background that grows rather than loops, and never reaches the same frame twice.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Idle animation",
			"Hover effect",
			"Compositing",
			"Frame rate (FPS)",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/turing/turing.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "feed",
				kind: "number",
				default: 0.05,
				min: 0.01,
				max: 0.09,
				step: 0.001,
				description:
					"Rate at which fresh reagent arrives everywhere. Feed and kill together pick the creature, and these coordinates were measured rather than inherited: 0.050/0.062 keeps colonising and is the default, 0.030/0.062 settles into stable spots and then genuinely stops, 0.039/0.058 floods to a dense labyrinth, and 0.022/0.051 oscillates without ever settling. Push feed past about 0.055 at this kill and the colonies die outright — the living band is a few thousandths wide, which is why the step is this fine.",
			},
			{
				name: "kill",
				kind: "number",
				default: 0.062,
				min: 0.045,
				max: 0.07,
				step: 0.001,
				description:
					"Rate at which the reacted product is removed. Pull it down and the pattern floods until it fills the plate; push it up and it starves back to nothing. The edge of the living band is a cliff rather than a slope, so this control does nothing and then does everything.",
			},
			{
				name: "diffusion",
				kind: "number",
				default: 1,
				min: 0.4,
				max: 1.4,
				step: 0.02,
				description:
					"How fast the substrate spreads relative to the activator, which is held at half. One is the canonical two-to-one. Turing's result is that a perfectly uniform system develops structure the moment one reagent outruns the other; this is that ratio, and below about 0.6 there is nothing to see because nothing outruns anything.",
			},
			{
				name: "steps",
				kind: "number",
				default: 16,
				min: 1,
				max: 32,
				step: 1,
				description:
					"Solver iterations per displayed frame, and the only reason this is watchable. The pattern needs a couple of thousand steps before it is worth looking at; at one step per frame that is most of a minute of staring at dots. Sixteen gets there in seconds and looks identical on arrival, because this is a time-scale control rather than a quality one. It is also the honest performance dial — every step is a full pass over the grid.",
			},
			{
				name: "gridSize",
				kind: "enum",
				default: "512",
				options: ["256", "384", "512", "768"],
				description:
					"Resolution of the simulation grid, deliberately held apart from the canvas — a window drag resizes only the display pass, so dragging the browser never wipes a pattern that took thirty seconds to grow. Bigger is finer filigree over the same area, not more area.",
			},
			{
				name: "seed",
				kind: "enum",
				default: "spots",
				options: ["spots", "ring", "stripe", "noise"],
				description:
					"How the plate is inoculated. Each one ends up somewhere different at identical feed and kill, which is the honest demonstration that this system has no single attractor — the initial condition is a real parameter, not a formality.",
			},
			{
				name: "brush",
				kind: "number",
				default: 26,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description:
					"Radius the pointer inoculates. Measured against the grid rather than the canvas, so the blob covers the same share of the pattern on a narrow strip as on a full page. The dose is one impulse per frame regardless of how many solver steps run, so this control and the step count stay independent.",
			},
			{
				name: "sharpness",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Where the palette ramp cuts the continuous field. The chemistry is smooth everywhere; coral does not look like coral until you cut it, and this is the cut. At zero you are looking at the raw concentration, which is the most informative view and the least striking one.",
			},
			{
				name: "colorLow",
				kind: "color",
				default: "#0a0a12",
				description: "The plate, where nothing has taken hold.",
			},
			{
				name: "colorHigh",
				kind: "color",
				default: "#a855f7",
				description:
					"The colony. The membrane picks it up too, at a third strength, so the boundary reads as the same organism rather than as an outline drawn around it.",
			},
		],
	},
	{
		slug: "quicksilver",
		name: "Quicksilver",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			"Molten chrome. Every other shader background emits light; this one reflects a studio that does not exist, synthesised from the surface normal — sharp softbox edges, a conductor's Fresnel wash, thin-film iridescence, and a wake that keeps moving where you dragged.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Idle animation",
			"Hover effect",
			"Compositing",
			"Hardware acceleration",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/quicksilver/quicksilver.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "flowSpeed",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"How fast the surface churns. At zero the metal sets, and a still frame is the only honest way to see how much of what you are looking at is the height field and how much is the light sitting on it.",
			},
			{
				name: "warp",
				kind: "number",
				default: 0.55,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"How far the noise drags its own coordinates before it is sampled again. Low is rolled sheet metal; past about one the surface folds back through itself and stops reading as a liquid at all.",
			},
			{
				name: "stir",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"How hard the pointer drags the metal. Eight recent impulses are kept alive at once, each with its own direction and age, which is why this leaves a wake rather than a dent — and why the whole component still costs one pass and no render target.",
			},
			{
				name: "viscosity",
				kind: "number",
				default: 0.6,
				min: 0.05,
				max: 1,
				step: 0.05,
				description:
					"How long a stir survives after the pointer has left. Low is mercury and settles almost before you have finished the gesture; high holds the wake long enough that you can write in it.",
			},
			{
				name: "fresnel",
				kind: "number",
				default: 2.2,
				min: 0.5,
				max: 6,
				step: 0.1,
				description:
					"Schlick exponent on the rim response. Low mirrors the whole surface evenly and reads as painted plastic; high keeps the bright reflection at the grazing angles, which is where metal actually puts it.",
			},
			{
				name: "iridescence",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Thin-film interference over the reflection, and the whole difference between chrome and oil on water. The hue comes from the film's optical thickness over the viewing cosine, so it tracks the surface angle instead of being a rainbow painted across the panel.",
			},
			{
				name: "roughness",
				kind: "number",
				default: 0.18,
				min: 0,
				max: 1,
				step: 0.02,
				description:
					"How soft the reflected studio edges are. This is not a blur: a rough conductor reflects the same room over a wider cone, so what widens is the light-to-dark transition. Zero is a mirror and shows every artefact in the height field, and a little roughness is what lets procedural metal survive being looked at closely.",
			},
			{
				name: "tint",
				kind: "color",
				default: "#c8d2e0",
				description:
					"The base metal. Conductors tint what they reflect, and this washes out toward white at the grazing angles rather than staying constant — which is the part most fake chrome gets wrong.",
			},
			{
				name: "sheenColor",
				kind: "color",
				default: "#a855f7",
				description: "The colour carried by the grazing-angle sheen.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#05060a",
				description:
					"The floor of the reflected environment, and what the vignette falls away to — so the panel edge reads as the room ending rather than as a mask laid over it.",
			},
		],
	},
];
