import type { ComponentEntry } from "../types";

/** Backgrounds — full-canvas / ambient visual systems. */
export const backgrounds: ComponentEntry[] = [
	{
		slug: "threads",
		name: "Threads",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"A woven field of flowing threads rendered on a WebGL line shader.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/threads/Threads.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Line color of the threads.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.5,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Wave displacement strength.",
			},
			{
				name: "distance",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 1.5,
				step: 0.05,
				description: "Z-spread between the layered lines.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation of the field.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity of the threads.",
			},
			{
				name: "enableMouseInteraction",
				kind: "boolean",
				default: true,
				description: "Let the cursor bend the field.",
			},
		],
	},
	{
		slug: "grainient",
		name: "Grainient",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"An animated grainy mesh-gradient rendered on a WebGL2 shader.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/grainient/Grainient.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "timeSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Overall animation speed.",
			},
			{
				name: "warpStrength",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Domain-warp intensity.",
			},
			{
				name: "warpFrequency",
				kind: "number",
				default: 2,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Warp detail frequency.",
			},
			{
				name: "blendSoftness",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Softness of the gradient blend.",
			},
			{
				name: "noiseScale",
				kind: "number",
				default: 1.2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Scale of the underlying noise.",
			},
			{
				name: "grainAmount",
				kind: "number",
				default: 0.12,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Film-grain intensity.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1,
				min: 0.5,
				max: 2,
				step: 0.05,
				description: "Output contrast.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1.1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Output saturation.",
			},
			{
				name: "zoom",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.05,
				description: "Camera zoom.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#f754f1",
				description: "First gradient color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#6d28d9",
				description: "Second gradient color.",
			},
			{
				name: "color3",
				kind: "color",
				default: "#22d3ee",
				description: "Third gradient color.",
			},
		],
	},
	{
		slug: "light-rays",
		name: "LightRays",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"Volumetric god-rays from a configurable origin, optionally mouse-following.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/light-rays/LightRays.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "raysColor",
				kind: "color",
				default: "#a855f7",
				description: "Ray color.",
			},
			{
				name: "raysSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "lightSpread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread of the rays.",
			},
			{
				name: "rayLength",
				kind: "number",
				default: 2,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Length of the rays.",
			},
			{
				name: "pulsating",
				kind: "boolean",
				default: false,
				description: "Pulse the ray intensity.",
			},
			{
				name: "fadeDistance",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 2,
				step: 0.05,
				description: "Distance over which rays fade.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "followMouse",
				kind: "boolean",
				default: true,
				description: "Aim the rays toward the cursor.",
			},
			{
				name: "mouseInfluence",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the cursor steers the rays.",
			},
			{
				name: "noiseAmount",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Noise texture over the rays.",
			},
			{
				name: "distortion",
				kind: "number",
				default: 0.2,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wavy distortion of the rays.",
			},
		],
	},
	{
		slug: "gradual-blur",
		name: "GradualBlur",
		category: "Backgrounds",
		tier: "free",
		description:
			"Progressive edge blur — stacked backdrop-filter layers dissolve content toward a chosen edge.",
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/gradual-blur/GradualBlur.tsx",
			},
		],
		props: [
			{
				name: "position",
				kind: "enum",
				default: "bottom",
				options: ["top", "bottom", "left", "right"],
				description: "Edge the blur attaches to.",
			},
			{
				name: "strength",
				kind: "number",
				default: 1,
				min: 0,
				max: 6,
				step: 0.1,
				description: "Base blur multiplier applied to every layer.",
			},
			{
				name: "divCount",
				label: "Div Count",
				kind: "number",
				default: 5,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of stacked blur layers (higher = smoother ramp).",
			},
			{
				name: "exponential",
				kind: "boolean",
				default: true,
				description: "Exponential progression for a stronger blur at the edge.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 1,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Opacity applied to each blur layer.",
			},
			{
				name: "target",
				kind: "enum",
				default: "parent",
				options: ["parent", "page"],
				description: "Attach to the parent container or the viewport (fixed).",
			},
			{
				name: "tinted",
				kind: "boolean",
				default: false,
				description: "Wash the blurred edge with a faint amethyst accent.",
			},
		],
	},
	{
		slug: "side-rays",
		name: "SideRays",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Corner-anchored two-color light rays with adjustable tilt and blend.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/side-rays/SideRays.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "rayColor1",
				kind: "color",
				default: "#a855f7",
				description: "First ray color.",
			},
			{
				name: "rayColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Second ray color.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 2,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Ray brightness.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Angular spread.",
			},
			{
				name: "tilt",
				kind: "number",
				default: 0,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Tilt of the ray bundle.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "blend",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Blend between the two colors.",
			},
			{
				name: "falloff",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Edge falloff.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
		],
	},
	{
		slug: "dot-field",
		name: "DotField",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"An interactive dot grid that bulges and glows around the cursor.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/dot-field/DotField.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "dotRadius",
				kind: "number",
				default: 1.5,
				min: 0.5,
				max: 5,
				step: 0.5,
				unit: "px",
				description: "Radius of each dot.",
			},
			{
				name: "dotSpacing",
				kind: "number",
				default: 25,
				min: 10,
				max: 50,
				step: 1,
				unit: "px",
				description: "Spacing between dots.",
			},
			{
				name: "cursorRadius",
				kind: "number",
				default: 500,
				min: 100,
				max: 800,
				step: 10,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "cursorForce",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 1,
				step: 0.01,
				description: "Strength of the cursor push.",
			},
			{
				name: "bulgeOnly",
				kind: "boolean",
				default: true,
				description: "Bulge toward the cursor only (no repel).",
			},
			{
				name: "bulgeStrength",
				kind: "number",
				default: 67,
				min: 0,
				max: 150,
				step: 1,
				description: "Bulge displacement strength.",
			},
			{
				name: "glowRadius",
				kind: "number",
				default: 160,
				min: 0,
				max: 400,
				step: 10,
				unit: "px",
				description: "Radius of the cursor glow.",
			},
			{
				name: "sparkle",
				kind: "boolean",
				default: false,
				description: "Add a sparkle shimmer.",
			},
			{
				name: "waveAmplitude",
				kind: "number",
				default: 0,
				min: 0,
				max: 20,
				step: 0.5,
				description: "Ambient wave motion.",
			},
			{
				name: "gradientFrom",
				kind: "color",
				default: "#a855f7",
				description: "Dot gradient start.",
			},
			{
				name: "gradientTo",
				kind: "color",
				default: "#b497cf",
				description: "Dot gradient end.",
			},
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Cursor glow color.",
			},
		],
	},
	{
		slug: "strands",
		name: "Strands",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Glowing wavy light-strands with an optional glass refraction lens.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/strands/Strands.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "count",
				kind: "number",
				default: 13,
				min: 3,
				max: 40,
				step: 1,
				description: "Number of strands.",
			},
			{
				name: "scale",
				label: "size",
				kind: "number",
				default: 1.1,
				min: 0.5,
				max: 3,
				step: 0.05,
				description:
					"Field size — lower zooms out, higher magnifies the strands.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Animation speed.",
			},
			{
				name: "amplitude",
				kind: "number",
				default: 1.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Wave amplitude.",
			},
			{
				name: "waviness",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Waviness of the strands.",
			},
			{
				name: "thickness",
				kind: "number",
				default: 1.55,
				min: 0.2,
				max: 4,
				step: 0.05,
				description: "Strand thickness.",
			},
			{
				name: "strandWidth",
				label: "width %",
				kind: "number",
				default: 100,
				min: 10,
				max: 100,
				step: 1,
				description:
					"Horizontal reach as a percentage — 100 spans to the glass rim.",
			},
			{
				name: "glow",
				kind: "number",
				default: 0.25,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glow strength.",
			},
			{
				name: "spread",
				kind: "number",
				default: 1.65,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Vertical spread.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color intensity.",
			},
			{
				name: "saturation",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Color saturation.",
			},
			{
				name: "opacity",
				kind: "number",
				default: 0.9,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Overall opacity.",
			},
			{
				name: "glass",
				kind: "boolean",
				default: true,
				description: "Overlay a glass refraction lens.",
			},
			{
				name: "refraction",
				kind: "number",
				default: 1.3,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glass refraction strength.",
			},
			{
				name: "dispersion",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Chromatic dispersion.",
			},
		],
	},
	{
		slug: "ribbons",
		name: "Ribbons",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description: "Flowing translucent ribbons drifting across a canvas.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ribbons/Ribbons.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#0037ff",
				description: "Ribbon color.",
			},
			{
				name: "colorAlpha",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Ribbon opacity.",
			},
			{
				name: "ribbonCount",
				kind: "number",
				default: 4,
				min: 1,
				max: 12,
				step: 1,
				description: "Number of ribbons on screen.",
			},
			{
				name: "strokeSize",
				kind: "number",
				default: 1,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Outline thickness.",
			},
			{
				name: "horizontalSpeed",
				kind: "number",
				default: 200,
				min: 10,
				max: 300,
				step: 10,
				description: "Drift speed across the canvas.",
			},
			{
				name: "parallaxAmount",
				kind: "number",
				default: -0.2,
				min: -1,
				max: 1,
				step: 0.05,
				description: "Scroll parallax factor.",
			},
			{
				name: "verticalPosition",
				kind: "enum",
				default: "random",
				options: ["top", "middle", "bottom", "random"],
				description: "Where ribbons spawn vertically.",
			},
			{
				name: "animateSections",
				kind: "boolean",
				default: false,
				description: "Wiggle ribbon segments over time.",
			},
		],
	},
	{
		slug: "world-map-ascii",
		name: "WorldMap ASCII",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A dot-matrix world map whose particles scatter from the cursor.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/world-map-ascii/WorldMapAscii.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Particle color.",
			},
			{
				name: "particleSize",
				kind: "number",
				default: 0.7,
				min: 0.3,
				max: 3,
				step: 0.1,
				unit: "px",
				description: "Dot radius.",
			},
			{
				name: "density",
				kind: "number",
				default: 8,
				min: 1,
				max: 9,
				step: 1,
				description: "Particle density — higher packs more particles.",
			},
			{
				name: "mouseRadius",
				kind: "number",
				default: 80,
				min: 0,
				max: 300,
				step: 10,
				unit: "px",
				description: "Cursor interaction radius; 0 disables the scatter.",
			},
			{
				name: "drift",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Idle wobble amplitude.",
			},
		],
	},
	{
		slug: "constellation",
		name: "Constellation",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A constellation network — drifting particles link by proximity, chase and flee the cursor, and glow.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/constellation/Constellation.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "density",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 2.5,
				step: 0.1,
				description: "Particle density relative to area.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.8,
				min: 0.1,
				max: 3,
				step: 0.05,
				description: "Top drift speed of particles.",
			},
			{
				name: "connectDistance",
				label: "Link distance",
				kind: "number",
				default: 120,
				min: 40,
				max: 250,
				step: 5,
				unit: "px",
				description: "Max distance for particle-to-particle lines.",
			},
			{
				name: "cursorDistance",
				label: "Cursor radius",
				kind: "number",
				default: 150,
				min: 0,
				max: 300,
				step: 10,
				unit: "px",
				description: "Cursor link + repel radius; 0 disables.",
			},
			{
				name: "repelForce",
				kind: "number",
				default: 2,
				min: 0,
				max: 6,
				step: 0.5,
				description: "Push strength inside the cursor radius.",
			},
			{
				name: "lineOpacity",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Opacity multiplier on connection lines.",
			},
			{
				name: "glow",
				kind: "number",
				default: 10,
				min: 0,
				max: 30,
				step: 1,
				description: "Particle glow blur.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#a855f7",
				description: "First particle color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#ff9207",
				description: "Second particle color.",
			},
			{
				name: "color3",
				kind: "color",
				default: "#22d3ee",
				description:
					"Third particle color — lines between mixed pairs blend as gradients.",
			},
		],
	},
	{
		slug: "plus-grid",
		name: "PlusGrid",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"A canvas field of '+' glyphs — scroll or pointer motion injects a traveling wave that ripples and decays across the grid.",
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/plus-grid/PlusGrid.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "gapX",
				label: "Gap X",
				kind: "number",
				default: 42,
				min: 24,
				max: 96,
				step: 2,
				unit: "px",
				description: "Horizontal gap between glyphs.",
			},
			{
				name: "gapY",
				label: "Gap Y",
				kind: "number",
				default: 38,
				min: 24,
				max: 96,
				step: 2,
				unit: "px",
				description: "Vertical gap between glyphs.",
			},
			{
				name: "fontSize",
				kind: "number",
				default: 20,
				min: 10,
				max: 36,
				step: 1,
				unit: "px",
				description: "Glyph size.",
			},
			{
				name: "baseOpacity",
				kind: "number",
				default: 0.5,
				min: 0.05,
				max: 1,
				step: 0.05,
				description: "Resting opacity of the field.",
			},
			{
				name: "waveAmplitude",
				kind: "number",
				default: 12,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Peak displacement at full wave energy.",
			},
			{
				name: "waveFrequency",
				kind: "number",
				default: 0.35,
				min: 0.05,
				max: 1,
				step: 0.05,
				description: "Ripple tightness across columns.",
			},
			{
				name: "waveDecay",
				label: "Decay",
				kind: "number",
				default: 0.96,
				min: 0.9,
				max: 0.995,
				step: 0.005,
				description: "Energy decay per tick — low snaps back, high lingers.",
			},
			{
				name: "autoPulse",
				kind: "boolean",
				default: true,
				description: "Fire a wave pulse every few seconds.",
			},
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Glyph color.",
			},
		],
	},
	{
		slug: "barcode",
		name: "Barcode",
		category: "Backgrounds",
		tier: "free",
		description:
			"A procedural barcode whose bars light up like piano notes — looping on autoplay or scrubbed by scroll.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/barcode/Barcode.tsx",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "autoplay",
				options: ["autoplay", "scrub"],
				description:
					"Autoplay loops the note timeline; scrub ties it to scroll position.",
			},
			{
				name: "restOpacity",
				label: "Rest opacity",
				kind: "number",
				default: 0.6,
				min: 0.1,
				max: 1,
				step: 0.05,
				description: "Opacity a bar settles at after its note.",
			},
			{
				name: "peakOpacity",
				label: "Peak opacity",
				kind: "number",
				default: 1,
				min: 0.5,
				max: 1,
				step: 0.05,
				description: "Opacity at the peak of a note strike.",
			},
			{
				name: "noteDuration",
				label: "Note length",
				kind: "number",
				default: 1.6,
				min: 0.4,
				max: 4,
				step: 0.1,
				unit: "s",
				description: "Length of one note's swell and fade.",
			},
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0.25,
				max: 3,
				step: 0.05,
				description: "Playback rate of the autoplay loop.",
				disabledWhen: { prop: "mode", equals: "scrub" },
			},
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Bar color.",
			},
		],
	},
	{
		slug: "aurora",
		name: "Aurora",
		category: "Backgrounds",
		tier: "free",
		pausable: true,
		description:
			"Flowing curtains of amethyst light drifting across a starless night sky — an fbm-warped WebGL2 field where luminous bands ripple, fold, and dissolve into fine grain, like a polar aurora seen from the dark side of the world.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/aurora/Aurora.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "baseColor",
				label: "Night sky",
				kind: "color",
				default: "#05010a",
				description: "Deep background the curtains glow against.",
			},
			{
				name: "auroraColor",
				label: "Curtain",
				kind: "color",
				default: "#a855f7",
				description: "Primary amethyst light of the bands.",
			},
			{
				name: "auroraColor2",
				label: "Highlight",
				kind: "color",
				default: "#22d3ee",
				description: "Secondary tint the curtain edges shift toward.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Drift speed of the flowing bands.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description: "Overall brightness of the aurora.",
			},
			{
				name: "bands",
				kind: "number",
				default: 3,
				min: 1,
				max: 6,
				step: 1,
				description: "Number of layered light curtains.",
			},
			{
				name: "warp",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Turbulence of the fbm domain-warp folding the curtains.",
			},
			{
				name: "coverage",
				kind: "number",
				default: 0.6,
				min: 0.2,
				max: 1,
				step: 0.05,
				description: "Vertical reach of the curtains up the sky.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.08,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Subtle film grain over the field.",
			},
		],
	},
	{
		slug: "starfield",
		name: "Starfield",
		category: "Backgrounds",
		tier: "pro",
		pausable: true,
		description:
			"Depth-layered stars drifting through a slow warp, each layer parallaxing at its own pace, with the occasional shooting star streaking a bright amethyst tail across the dark before the field settles back to its patient glimmer.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/starfield/Starfield.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "starColor",
				label: "Stars",
				kind: "color",
				default: "#ffffff",
				description: "Color of the star field.",
			},
			{
				name: "accentColor",
				label: "Accent",
				kind: "color",
				default: "#a855f7",
				description: "Tints a minority of stars and every shooting-star tail.",
			},
			{
				name: "density",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.1,
				description: "Star count relative to the pane area.",
			},
			{
				name: "layers",
				kind: "number",
				default: 3,
				min: 1,
				max: 5,
				step: 1,
				description:
					"Parallax depth layers — nearer layers drift faster and brighter.",
			},
			{
				name: "driftSpeed",
				label: "Warp drift",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Speed of the slow directional warp across the field.",
			},
			{
				name: "twinkle",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Strength of per-star brightness twinkle.",
			},
			{
				name: "shootingStars",
				label: "Shooting stars",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How often streaks appear; 0 disables them.",
			},
			{
				name: "glow",
				kind: "number",
				default: 8,
				min: 0,
				max: 30,
				step: 1,
				unit: "px",
				description: "Glow blur around each star.",
			},
		],
	},
	{
		slug: "cinders",
		name: "Cinders",
		category: "Backgrounds",
		tier: "free",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"A dark field of embers and ash rising on the draft, aglow with amethyst.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/cinders/Cinders.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "emberCount",
				kind: "number",
				default: 140,
				min: 20,
				max: 400,
				step: 10,
				description: "Number of embers and ash motes in the field.",
			},
			{
				name: "riseSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Upward drift speed of the embers.",
			},
			{
				name: "turbulence",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Sideways sway as the motes rise.",
			},
			{
				name: "emberSize",
				kind: "number",
				default: 2,
				min: 0.5,
				max: 6,
				step: 0.5,
				unit: "px",
				description: "Base radius of each mote.",
			},
			{
				name: "glow",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Halo size around each spark.",
			},
			{
				name: "draftStrength",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				description: "How strongly the cursor stirs a draft.",
			},
			{
				name: "emberColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst ember glow color.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#0a0510",
				description: "Dark field the motes rise against.",
			},
		],
	},
	{
		slug: "shadowflame",
		name: "Shadowflame",
		category: "Backgrounds",
		tier: "pro",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"A black flame with an amethyst core, its body folded from domain-warped noise.",
		dependencies: ["ogl"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/shadowflame/Shadowflame.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "coreColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst core of the flame.",
			},
			{
				name: "flameColor",
				kind: "color",
				default: "#630475",
				description: "Dark body of the black flame.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#05010a",
				description: "The void the flame rises against.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Rise speed of the flame.",
			},
			{
				name: "warp",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Domain-warp turbulence folding the flame.",
			},
			{
				name: "detail",
				kind: "number",
				default: 4,
				min: 1,
				max: 6,
				step: 1,
				description: "Number of noise octaves.",
			},
			{
				name: "shimmer",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Rising heat-shimmer distortion.",
			},
			{
				name: "height",
				kind: "number",
				default: 0.7,
				min: 0.2,
				max: 1,
				step: 0.05,
				description: "How far up the frame the flame reaches.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Film grain over the field.",
			},
			{
				name: "flameWidth",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 2,
				step: 0.05,
				description: "Horizontal spread of the flame.",
			},
			{
				name: "sparkCount",
				kind: "number",
				default: 60,
				min: 0,
				max: 200,
				step: 5,
				description: "Number of rising fire sparks (0 turns them off).",
			},
			{
				name: "sparkSize",
				kind: "number",
				default: 1.2,
				min: 0.5,
				max: 3,
				step: 0.1,
				unit: "px",
				description: "Size of each rising spark.",
			},
			{
				name: "sparkSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Rise speed of the sparks.",
			},
		],
	},
];
