import type { ComponentEntry } from "../types";

/** Micro-interactions — hover, focus, and dialog motion primitives. */
export const microInteractions: ComponentEntry[] = [
	{
		slug: "pixel-transition",
		name: "PixelTransition",
		category: "Micro-interactions",
		tier: "free",
		description:
			"Reveal a second layer through a random pixelated dissolve on hover.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/pixel-transition/PixelTransition.tsx",
			},
		],
		props: [
			{
				name: "gridSize",
				kind: "number",
				default: 7,
				min: 2,
				max: 20,
				step: 1,
				description: "Pixel grid resolution.",
			},
			{
				name: "pixelColor",
				kind: "color",
				default: "#a855f7",
				description: "Color of the dissolve pixels.",
			},
			{
				name: "animationStepDuration",
				kind: "number",
				default: 0.3,
				min: 0.1,
				max: 1,
				step: 0.05,
				unit: "s",
				description: "Duration of the dissolve.",
			},
			{
				name: "once",
				kind: "boolean",
				default: false,
				description: "Play only once instead of on every hover.",
			},
		],
	},
	{
		slug: "border-glow",
		name: "BorderGlow",
		category: "Micro-interactions",
		tier: "free",
		description: "A cursor-proximity gradient border with an outer glow.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/border-glow/BorderGlow.tsx",
			},
		],
		props: [
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Glow color.",
			},
			{
				name: "glowRadius",
				kind: "number",
				default: 12,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Outer glow radius.",
			},
			{
				name: "glowIntensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glow brightness.",
			},
			{
				name: "coneSpread",
				kind: "number",
				default: 35,
				min: 5,
				max: 50,
				step: 1,
				description: "Angular spread of the glow cone.",
			},
			{
				name: "edgeSensitivity",
				kind: "number",
				default: 30,
				min: 0,
				max: 80,
				step: 1,
				description: "How close to the edge the glow activates.",
			},
			{
				name: "borderRadius",
				kind: "number",
				default: 16,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Corner radius.",
			},
			{
				name: "fillOpacity",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Border fill opacity.",
			},
			{
				name: "animated",
				kind: "boolean",
				default: false,
				description: "Play an intro sweep on mount.",
			},
		],
	},
	{
		slug: "spotlight-shell",
		name: "SpotlightShell",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A card shell with 3D magnetic tilt, radial glow, and a shimmer sweep.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/spotlight-shell/SpotlightShell.tsx",
			},
		],
		props: [
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "Accent color for the glow and accent line.",
			},
		],
	},
	{
		slug: "animated-hamburger",
		name: "AnimatedHamburger",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A three-bar hamburger that morphs to an X, driven by an open prop.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/animated-hamburger/AnimatedHamburger.tsx",
			},
		],
		props: [
			{
				name: "open",
				kind: "boolean",
				default: false,
				description: "Toggle between the hamburger and the X.",
			},
		],
	},
	{
		slug: "morph-dialog",
		name: "MorphDialog",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A dialog that morphs open from its trigger via shared-layout animation, with elements that travel between card and panel.",
		dependencies: ["motion", "lucide-react"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/morph-dialog/MorphDialog.tsx",
			},
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 320,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the morph.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 10,
				max: 60,
				step: 1,
				description: "Spring damping — lower rings longer.",
			},
			{
				name: "radius",
				kind: "number",
				default: 16,
				min: 0,
				max: 32,
				step: 1,
				unit: "px",
				description: "Panel corner radius.",
			},
			{
				name: "blurBackdrop",
				kind: "boolean",
				default: true,
				description: "Frosted blur on the backdrop scrim.",
			},
			{
				name: "autoFocus",
				kind: "boolean",
				default: true,
				description: "Focus the first focusable element on open.",
			},
		],
	},
	{
		slug: "grow-dialog",
		name: "GrowDialog",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A dialog that grows out of the clicked element and shrinks back into it, entirely inside a portal — never behind page content.",
		dependencies: ["motion", "lucide-react"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/grow-dialog/GrowDialog.tsx",
			},
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 320,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the grow.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 10,
				max: 60,
				step: 1,
				description: "Spring damping — lower rings longer.",
			},
			{
				name: "radius",
				kind: "number",
				default: 16,
				min: 0,
				max: 32,
				step: 1,
				unit: "px",
				description: "Panel corner radius.",
			},
			{
				name: "blurBackdrop",
				kind: "boolean",
				default: true,
				description: "Frosted blur on the backdrop scrim.",
			},
			{
				name: "autoFocus",
				kind: "boolean",
				default: true,
				description: "Focus the first focusable element on open.",
			},
		],
	},
	{
		slug: "flip-card",
		name: "FlipCard",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A grid card that flips out of its cell — GSAP Flip carries it to viewport center while it rotates to reveal its back face, then returns on close.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/flip-card/FlipCard.tsx",
			},
		],
		props: [
			{
				name: "flipDuration",
				label: "Flip duration",
				kind: "number",
				default: 0.5,
				min: 0.2,
				max: 1.2,
				step: 0.05,
				unit: "s",
				description:
					"Duration of the Flip flight; rotation timing derives from it.",
			},
			{
				name: "perspective",
				kind: "number",
				default: 1200,
				min: 400,
				max: 2400,
				step: 100,
				unit: "px",
				description: "3D perspective depth on each card.",
			},
			{
				name: "expandedWidth",
				label: "Expanded width",
				kind: "number",
				default: 400,
				min: 280,
				max: 640,
				step: 10,
				unit: "px",
				description: "Expanded card width (clamped to the viewport).",
			},
			{
				name: "expandedHeight",
				label: "Expanded height",
				kind: "number",
				default: 480,
				min: 320,
				max: 720,
				step: 10,
				unit: "px",
				description: "Expanded card height (clamped to the viewport).",
			},
			{
				name: "backdropBlur",
				label: "Backdrop blur",
				kind: "number",
				default: 2,
				min: 0,
				max: 16,
				step: 1,
				unit: "px",
				description: "Backdrop scrim blur while a card is open.",
			},
		],
	},
];
