import type { ComponentEntry } from "../types";

/** Micro-interactions — hover, focus, and dialog motion primitives. */
export const microInteractions: ComponentEntry[] = [
	{
		slug: "pixel-transition",
		name: "PixelTransition",
		category: "Micro-interactions",
		tier: "free",
		description:
			"Reveal a second layer through a random pixelated dissolve on hover.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/pixel-transition/PixelTransition.tsx",
			},
		],
		props: [
			{
				name: "gridSize",
				kind: "number",
				default: 7,
				min: 2,
				max: 20,
				step: 1,
				description: "Pixel grid resolution.",
			},
			{
				name: "pixelColor",
				kind: "color",
				default: "#a855f7",
				description: "Color of the dissolve pixels.",
			},
			{
				name: "animationStepDuration",
				kind: "number",
				default: 0.3,
				min: 0.1,
				max: 1,
				step: 0.05,
				unit: "s",
				description: "Duration of the dissolve.",
			},
			{
				name: "once",
				kind: "boolean",
				default: false,
				description: "Play only once instead of on every hover.",
			},
		],
	},
	{
		slug: "border-glow",
		name: "BorderGlow",
		category: "Micro-interactions",
		tier: "free",
		description: "A cursor-proximity gradient border with an outer glow.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/border-glow/BorderGlow.tsx",
			},
		],
		props: [
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Glow color.",
			},
			{
				name: "glowRadius",
				kind: "number",
				default: 12,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Outer glow radius.",
			},
			{
				name: "glowIntensity",
				kind: "number",
				default: 1,
				min: 0,
				max: 2,
				step: 0.05,
				description: "Glow brightness.",
			},
			{
				name: "coneSpread",
				kind: "number",
				default: 35,
				min: 5,
				max: 50,
				step: 1,
				description: "Angular spread of the glow cone.",
			},
			{
				name: "edgeSensitivity",
				kind: "number",
				default: 30,
				min: 0,
				max: 80,
				step: 1,
				description: "How close to the edge the glow activates.",
			},
			{
				name: "borderRadius",
				kind: "number",
				default: 16,
				min: 0,
				max: 40,
				step: 1,
				unit: "px",
				description: "Corner radius.",
			},
			{
				name: "fillOpacity",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Border fill opacity.",
			},
			{
				name: "animated",
				kind: "boolean",
				default: false,
				description: "Play an intro sweep on mount.",
			},
		],
	},
	{
		slug: "spotlight-shell",
		name: "SpotlightShell",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A card shell with 3D magnetic tilt, radial glow, and a shimmer sweep.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/spotlight-shell/SpotlightShell.tsx",
			},
		],
		props: [
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "Accent color for the glow and accent line.",
			},
		],
	},
	{
		slug: "animated-hamburger",
		name: "AnimatedHamburger",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A three-bar hamburger that morphs to an X, driven by a toggle prop.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/animated-hamburger/AnimatedHamburger.tsx",
			},
		],
		props: [
			{
				name: "toggle",
				kind: "boolean",
				default: false,
				description: "Toggle between the hamburger and the X.",
			},
		],
	},
	{
		slug: "morph-dialog",
		name: "MorphDialog",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A dialog that morphs open from its trigger via shared-layout animation, with elements that travel between card and panel.",
		dependencies: ["motion", "lucide-react"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/morph-dialog/MorphDialog.tsx",
			},
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 320,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the morph.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 10,
				max: 60,
				step: 1,
				description: "Spring damping — lower rings longer.",
			},
			{
				name: "radius",
				kind: "number",
				default: 16,
				min: 0,
				max: 32,
				step: 1,
				unit: "px",
				description: "Panel corner radius.",
			},
			{
				name: "blurBackdrop",
				kind: "boolean",
				default: true,
				description: "Frosted blur on the backdrop scrim.",
			},
			{
				name: "autoFocus",
				kind: "boolean",
				default: true,
				description: "Focus the first focusable element on open.",
			},
		],
	},
	{
		slug: "grow-dialog",
		name: "GrowDialog",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A dialog that grows out of the clicked element and shrinks back into it, entirely inside a portal — never behind page content.",
		dependencies: ["motion", "lucide-react"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/grow-dialog/GrowDialog.tsx",
			},
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 320,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the grow.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 10,
				max: 60,
				step: 1,
				description: "Spring damping — lower rings longer.",
			},
			{
				name: "radius",
				kind: "number",
				default: 16,
				min: 0,
				max: 32,
				step: 1,
				unit: "px",
				description: "Panel corner radius.",
			},
			{
				name: "blurBackdrop",
				kind: "boolean",
				default: true,
				description: "Frosted blur on the backdrop scrim.",
			},
			{
				name: "autoFocus",
				kind: "boolean",
				default: true,
				description: "Focus the first focusable element on open.",
			},
		],
	},
	{
		slug: "flip-card",
		name: "FlipCard",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A grid card that flips out of its cell — GSAP Flip carries it to viewport center while it rotates to reveal its back face, then returns on close.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/flip-card/FlipCard.tsx",
			},
		],
		props: [
			{
				name: "flipDuration",
				label: "Flip duration",
				kind: "number",
				default: 0.5,
				min: 0.2,
				max: 1.2,
				step: 0.05,
				unit: "s",
				description:
					"Duration of the Flip flight; rotation timing derives from it.",
			},
			{
				name: "perspective",
				kind: "number",
				default: 1200,
				min: 400,
				max: 2400,
				step: 100,
				unit: "px",
				description: "3D perspective depth on each card.",
			},
			{
				name: "expandedWidth",
				label: "Expanded width",
				kind: "number",
				default: 400,
				min: 280,
				max: 640,
				step: 10,
				unit: "px",
				description: "Expanded card width (clamped to the viewport).",
			},
			{
				name: "expandedHeight",
				label: "Expanded height",
				kind: "number",
				default: 480,
				min: 320,
				max: 720,
				step: 10,
				unit: "px",
				description: "Expanded card height (clamped to the viewport).",
			},
			{
				name: "backdropBlur",
				label: "Backdrop blur",
				kind: "number",
				default: 2,
				min: 0,
				max: 16,
				step: 1,
				unit: "px",
				description: "Backdrop scrim blur while a card is open.",
			},
		],
	},
	{
		slug: "blueprint-card",
		name: "BlueprintCard",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A technical-drawing card — dashed envelope, accent rules, corner nodes, and a soft glow that draw in on mount.",
		dependencies: [],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/blueprint-card/BlueprintCard.tsx",
			},
		],
		props: [
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "Accent color for the frame, nodes, and glow.",
			},
			{
				name: "dashed",
				kind: "boolean",
				default: true,
				description: "Dashed outer border; solid when off.",
			},
			{
				name: "dotSize",
				label: "Node size",
				kind: "number",
				default: 4,
				min: 2,
				max: 10,
				step: 1,
				unit: "px",
				description: "Diameter of the corner nodes.",
			},
			{
				name: "glowIntensity",
				label: "Glow intensity",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.5,
				step: 0.01,
				description: "Strength of the bottom gradient glow.",
			},
			{
				name: "animated",
				kind: "boolean",
				default: true,
				description: "Draw the frame in on mount.",
			},
		],
	},
	{
		slug: "corner-letters",
		name: "CornerLetters",
		category: "Micro-interactions",
		tier: "free",
		description:
			"Four glyphs pinned to the container corners that blur-and-scale in on mount and dissolve out on exit.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/corner-letters/CornerLetters.tsx",
			},
		],
		props: [
			{
				name: "visible",
				kind: "boolean",
				default: true,
				description: "Mounts and unmounts the glyphs — toggle to replay.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 120,
				min: 40,
				max: 400,
				step: 5,
				description: "Spring stiffness of the entrance.",
			},
			{
				name: "blur",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Blur the glyphs travel from and to.",
			},
			{
				name: "scaleFrom",
				label: "Scale from",
				kind: "number",
				default: 1.5,
				min: 1,
				max: 3,
				step: 0.05,
				description: "Starting scale of each glyph.",
			},
			{
				name: "offset",
				kind: "number",
				default: 4,
				min: 0,
				max: 32,
				step: 1,
				unit: "px",
				description: "Inset from the corners.",
			},
			{
				name: "size",
				kind: "number",
				default: 32,
				min: 16,
				max: 64,
				step: 2,
				unit: "px",
				description: "Glyph font size.",
			},
			{
				name: "color",
				kind: "color",
				default: "#a855f7",
				description: "Glyph color.",
			},
		],
	},
	{
		slug: "hover-list",
		name: "HoverList",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A display-type list where a shared accent block springs between rows on hover while the text indents and inverts.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/hover-list/HoverList.tsx",
			},
		],
		props: [
			{
				name: "highlightColor",
				label: "Highlight",
				kind: "color",
				default: "#a855f7",
				description: "Color of the sliding highlight block.",
			},
			{
				name: "invertedColor",
				label: "Hovered text",
				kind: "color",
				default: "#000000",
				description: "Text and icon color while a row is highlighted.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 300,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the sliding highlight.",
			},
			{
				name: "damping",
				kind: "number",
				default: 30,
				min: 10,
				max: 60,
				step: 1,
				description: "Spring damping — lower rings longer.",
			},
			{
				name: "indent",
				kind: "number",
				default: 32,
				min: 0,
				max: 80,
				step: 2,
				unit: "px",
				description: "How far the row content slides right on hover.",
			},
			{
				name: "textSize",
				label: "Text size",
				kind: "enum",
				default: "md",
				options: ["sm", "md", "lg"],
				description: "Display type scale of the rows.",
			},
			{
				name: "showIcon",
				label: "Crosshair",
				kind: "boolean",
				default: true,
				description: "Rotate a crosshair icon in on hover.",
			},
			{
				name: "rounded",
				kind: "number",
				default: 0,
				min: 0,
				max: 24,
				step: 1,
				unit: "px",
				description: "Corner radius of the highlight block.",
			},
		],
	},
	{
		slug: "preloader",
		name: "Preloader",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A percentage-counting load overlay — spinning ring, eased counter, and a fade-out that reveals the page beneath.",
		dependencies: ["gsap"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/preloader/Preloader.tsx",
			},
		],
		props: [
			{
				name: "duration",
				kind: "number",
				default: 3,
				min: 1,
				max: 8,
				step: 0.1,
				unit: "s",
				description: "Simulated load time.",
			},
			{
				name: "ringColor",
				label: "Ring color",
				kind: "color",
				default: "#a855f7",
				description: "Color of the spinner, counter, and label.",
			},
			{
				name: "overlayColor",
				label: "Overlay",
				kind: "color",
				default: "#000000",
				description: "Overlay background color.",
			},
			{
				name: "ringSize",
				label: "Ring size",
				kind: "number",
				default: 128,
				min: 64,
				max: 200,
				step: 4,
				unit: "px",
				description: "Ring diameter.",
			},
			{
				name: "spinSpeed",
				label: "Spin speed",
				kind: "number",
				default: 1.5,
				min: 0.5,
				max: 4,
				step: 0.1,
				unit: "s",
				description: "Seconds per spinner revolution.",
			},
			{
				name: "holdDelay",
				label: "Hold at 100%",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 2,
				step: 0.1,
				unit: "s",
				description: "Pause at 100% before the fade.",
			},
			{
				name: "fadeDuration",
				label: "Fade duration",
				kind: "number",
				default: 0.6,
				min: 0.2,
				max: 1.5,
				step: 0.05,
				unit: "s",
				description: "Duration of the fade-out.",
			},
			{
				name: "showLabel",
				label: "Label",
				kind: "boolean",
				default: true,
				description: "Show the caption under the counter.",
			},
		],
	},
	{
		slug: "circle-menu",
		name: "CircleMenu",
		category: "Micro-interactions",
		tier: "free",
		description:
			"A menu overlay that blooms open as a clip-path circle spring while items stagger in with blur and rotation, then collapses back to its pill.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/circle-menu/CircleMenu.tsx",
			},
		],
		props: [
			{
				name: "openStiffness",
				label: "Open spring",
				kind: "number",
				default: 20,
				min: 5,
				max: 120,
				step: 1,
				description: "Bloom spring stiffness — low values settle slowly.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 0.09,
				min: 0,
				max: 0.2,
				step: 0.01,
				unit: "s",
				description: "Delay between each item's entrance.",
			},
			{
				name: "blur",
				label: "Item blur",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Blur the items travel from and to.",
			},
			{
				name: "overlayColor",
				label: "Overlay",
				kind: "color",
				default: "#0a0a0c",
				description: "Overlay background color.",
			},
			{
				name: "overlayOpacity",
				label: "Overlay opacity",
				kind: "number",
				default: 0.92,
				min: 0.5,
				max: 1,
				step: 0.01,
				description: "Overlay background opacity.",
			},
		],
	},
	{
		slug: "magnetic-button",
		name: "MagneticButton",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A button that leans into your cursor — caught in a magnetic field it slides toward the pointer while an amethyst aura swells with proximity, then snaps home on a spring and answers every click with a dark ripple bursting outward from the point of contact.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/magnetic-button/MagneticButton.tsx",
			},
		],
		props: [
			{
				name: "pullStrength",
				label: "Pull",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Fraction of the cursor offset the button follows.",
			},
			{
				name: "radius",
				kind: "number",
				default: 120,
				min: 40,
				max: 300,
				step: 10,
				unit: "px",
				description: "Field radius where the magnetic pull begins.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 260,
				min: 100,
				max: 600,
				step: 10,
				description: "Spring stiffness of the pull and return.",
			},
			{
				name: "damping",
				kind: "number",
				default: 18,
				min: 8,
				max: 60,
				step: 1,
				description: "Spring damping — lower overshoots and rings.",
			},
			{
				name: "auraColor",
				label: "Aura",
				kind: "color",
				default: "#a855f7",
				description: "Color of the proximity glow.",
			},
			{
				name: "auraSize",
				label: "Aura size",
				kind: "number",
				default: 80,
				min: 0,
				max: 200,
				step: 5,
				unit: "px",
				description: "Spread of the aura at full proximity.",
			},
			{
				name: "ripple",
				kind: "boolean",
				default: true,
				description: "Emit a dark ripple burst on click.",
			},
			{
				name: "rippleColor",
				label: "Ripple",
				kind: "color",
				default: "#0a0a0c",
				description: "Color of the click ripple.",
				disabledWhen: { prop: "ripple", equals: false },
			},
		],
	},
	{
		slug: "shadow-cursor",
		name: "ShadowCursor",
		category: "Micro-interactions",
		tier: "pro",
		description:
			"A custom cursor with a shadow at its heel — a precise dot leads while a lagging blade trails on a spring, and when it crosses an interactive element the trail pools and swells around it, inverting whatever lies beneath. Scoped entirely to its own stage; the page cursor is never touched.",
		dependencies: ["motion"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/shadow-cursor/ShadowCursor.tsx",
			},
		],
		props: [
			{
				name: "dotSize",
				label: "Dot",
				kind: "number",
				default: 8,
				min: 4,
				max: 24,
				step: 1,
				unit: "px",
				description: "Size of the leading precise dot.",
			},
			{
				name: "trailSize",
				label: "Trail",
				kind: "number",
				default: 36,
				min: 12,
				max: 80,
				step: 2,
				unit: "px",
				description: "Size of the lagging trailing ring.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 150,
				min: 50,
				max: 500,
				step: 10,
				description: "Spring stiffness of the trailing ring — higher lags less.",
			},
			{
				name: "damping",
				kind: "number",
				default: 15,
				min: 8,
				max: 40,
				step: 1,
				description: "Spring damping of the trailing ring.",
			},
			{
				name: "cursorColor",
				label: "Color",
				kind: "color",
				default: "#a855f7",
				description: "Color of the dot and trailing ring.",
			},
			{
				name: "blendMode",
				label: "Blend",
				kind: "enum",
				default: "difference",
				options: ["difference", "screen", "exclusion", "normal"],
				description: "Mix-blend-mode of the cursor over content beneath it.",
			},
			{
				name: "poolScale",
				label: "Pool",
				kind: "number",
				default: 2,
				min: 1,
				max: 4,
				step: 0.1,
				unit: "×",
				description: "How much the trail swells when over an interactive element.",
			},
		],
	},
];
