import type { ComponentEntry, Variant } from "../types";

/** lib/utils.ts ships with every entry whose source imports `cn`. Its own
 *  packages (clsx, tailwind-merge) are the host entry's to declare — the check
 *  walks into this file and finds them there (§V41). */
const UTILS_VARIANT: Variant = {
	lang: "ts",
	style: "tailwind",
	file: "lib/utils.ts",
	role: "util",
	label: "utils.ts",
};

/** FileExplorer is assembled from its whole directory, not one file. Listed as a
 *  mapped array rather than 23 literals so the entry stays readable; the set is
 *  the component's transitive closure, which `check:registry` verifies. It
 *  carries its own `cn` in ./util, so it takes no UTILS_VARIANT. */
const FILE_EXPLORER_PEERS: Variant[] = [
	"AutoScroll.tsx",
	"Breadcrumb.tsx",
	"ContextMenu.tsx",
	"DetailPanel.tsx",
	"EmptyState.tsx",
	"FileGrid.tsx",
	"FileList.tsx",
	"FolderTree.tsx",
	"InlineRename.tsx",
	"StorageMeter.tsx",
	"Thumbnail.tsx",
	"Toolbar.tsx",
	"UndoSnackbar.tsx",
	"types.ts",
	"useFileExplorer.ts",
	"useFileStore.ts",
	"useObjectUrl.ts",
	"util.ts",
	"store/index.ts",
	"store/types.ts",
	"store/idb-store.ts",
	"store/memory-store.ts",
	"store/opfs-store.ts",
].map((name) => ({
	lang: "ts",
	style: "tailwind",
	file: `components/registry/file-explorer/${name}`,
	role: "peer",
	label: name,
}));

/** ApprovalFlow is six files, not one. Same mapped-array shape as the explorer
 *  above, and the same reason: the Code panel gets one tab per variant, so the
 *  set is kept deliberately small and the reading order here is the order a
 *  buyer should open them in. It imports `cn`, so it takes UTILS_VARIANT and
 *  declares clsx + tailwind-merge itself (§V41). */
const APPROVAL_FLOW_PEERS: Variant[] = [
	"types.ts",
	"useApprovalFlow.ts",
	"StepPanel.tsx",
	"OptionRow.tsx",
	"DecidedRail.tsx",
].map((name) => ({
	lang: "ts",
	style: "tailwind",
	file: `components/registry/approval-flow/${name}`,
	role: "peer",
	label: name,
}));

/** Power-User Systems — composite, stateful showcase pieces. */
export const powerUserSystems: ComponentEntry[] = [
	{
		slug: "sakura-tree",
		name: "SakuraTree",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A painterly toon-shaded 3D cherry-blossom scene with wind-driven falling petals.",
		dependencies: ["three", "@react-three/fiber", "clsx", "tailwind-merge"],
		cookbook: ["Loop", "Float", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/sakura-tree/SakuraTree.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "windSpeed",
				kind: "number",
				default: 3,
				min: 0,
				max: 10,
				step: 0.5,
				description: "Branch sway and petal drift speed.",
			},
			{
				name: "fallingPetals",
				kind: "number",
				default: 129,
				min: 0,
				max: 300,
				step: 1,
				description:
					"Number of petals drifting through the air. Fades out and disables when bloom is zero.",
				disabledWhen: { prop: "bloomAmount", equals: 0 },
			},
			{
				name: "bloomAmount",
				kind: "number",
				default: 0.85,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Canopy fullness, bare branches to full blossom.",
			},
			{
				name: "weather",
				kind: "enum",
				default: "clear",
				options: ["clear", "breezy", "overcast", "storm"],
				description:
					"Bundles ambient light, fog density and a wind multiplier.",
			},
			{
				name: "windDirection",
				kind: "number",
				default: 45,
				min: 0,
				max: 360,
				step: 15,
				unit: "°",
				description: "Compass direction the petals drift toward.",
			},
			{
				name: "cameraDistance",
				kind: "number",
				default: 8,
				min: 4,
				max: 12,
				step: 0.5,
				description: "Orbit radius — how far the camera sits from the tree.",
			},
		],
	},
	{
		slug: "command-palette",
		name: "CommandPalette",
		category: "Power-User Systems",
		tier: "pro",
		description:
			"A cmdk command menu with a plain or liquid-glass surface and hotkey trigger.",
		dependencies: ["cmdk", "motion", "clsx", "tailwind-merge"],
		cookbook: ["Enter / Exit", "Scale in", "Blur"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/command-palette/CommandPalette.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "components/ui/auto-mask-vertical.tsx",
				role: "peer",
				label: "auto-mask-vertical.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "hotkey",
				kind: "enum",
				default: "cmd+k",
				options: ["cmd+k", "ctrl+k", "/"],
				description:
					"Shortcut that opens the palette. cmd+k falls back to Ctrl+K on non-Apple platforms.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: true,
				description: "Wrap keyboard selection at the list ends.",
			},
			{
				name: "glass",
				kind: "boolean",
				default: false,
				description: "Liquid-glass surface instead of a solid panel.",
			},
		],
	},
	{
		slug: "physics-engine",
		name: "PhysicsEngine",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A from-scratch 2D rigid-body physics lab — fixed-timestep impulse solver, drag-to-throw bodies, force and velocity overlays, and a live energy readout on a blueprint grid.",
		cookbook: [
			"Drag",
			"Momentum",
			"Velocity",
			"Mass",
			"Bounce",
			"Frame rate (FPS)",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/physics-engine/PhysicsEngine.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
			},
		],
		props: [
			{
				name: "scene",
				kind: "enum",
				default: "playground",
				options: ["playground", "stack", "wrecking-ball", "projectile"],
				description:
					"Preset world. Switching rebuilds the scene deterministically from a fixed seed.",
			},
			{
				name: "gravity",
				kind: "number",
				default: 9.8,
				min: 0,
				max: 30,
				step: 0.1,
				unit: "m/s²",
				description:
					"Uniform downward gravity. 0 is zero-g — throw bodies and watch them coast.",
			},
			{
				name: "restitution",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Bounciness of every collision, applied live to existing bodies. Impacts below 1 m/s are absorbed so stacks can settle.",
			},
			{
				name: "friction",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Coulomb friction coefficient for all contacts, applied live. 0 is ice; boxes need around 0.3 to stack.",
			},
			{
				name: "timeScale",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Simulation speed. Physics always steps at a fixed 120 Hz — this scales how much simulated time each frame consumes. 0 freezes time.",
			},
			{
				name: "bodyCount",
				kind: "number",
				default: 14,
				min: 4,
				max: 40,
				step: 1,
				description:
					"How many bodies the playground rains and how tall the stack and wrecking-ball towers build. Projectile ignores it.",
			},
			{
				name: "sizeVariation",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Spread of playground body sizes — 0 rains uniform bodies, 1 mixes pebbles with boulders. Density is fixed, so bigger really is heavier.",
			},
			{
				name: "showVectors",
				kind: "boolean",
				default: false,
				description:
					"Velocity (green, solid) and net-force (red, dashed) arrows anchored at each body's center of mass, scaled to magnitude.",
			},
			{
				name: "trails",
				kind: "boolean",
				default: true,
				description:
					"Fading motion trails behind moving bodies — read parabolas and pendulum arcs at a glance.",
			},
			{
				name: "showEnergy",
				kind: "boolean",
				default: true,
				description:
					"Live HUD readout of kinetic, potential, and total energy in joules, computed from solver state every step — never faked.",
			},
			{
				name: "tint",
				kind: "color",
				default: "#a855f7",
				description:
					"Accent color for dynamic bodies, trails, and the grab spring. Grid and chrome follow the theme.",
			},
		],
	},
	{
		slug: "black-hole",
		name: "BlackHole",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A real-time Schwarzschild black hole raytraced per-pixel in a WebGL2 shader — null geodesics bend a lensed accretion disk over the event horizon, with Doppler beaming, gravitational redshift, a photon ring, and a lensed starfield, all under a cinematic orbit.",
		dependencies: ["ogl", "clsx", "tailwind-merge"],
		cookbook: ["Orbit", "Loop", "Drag", "Frame rate (FPS)"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/black-hole/BlackHole.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "steps",
				kind: "number",
				default: 300,
				min: 60,
				max: 600,
				step: 10,
				description:
					"Geodesic integration steps per ray. Higher sharpens the lensing and photon ring; lower runs faster. The single heaviest cost in the shader.",
			},
			{
				name: "diskInner",
				kind: "number",
				default: 3,
				min: 2,
				max: 6,
				step: 0.1,
				unit: "Rs",
				description:
					"Inner disk radius in Schwarzschild radii. 3 Rs is the ISCO — the innermost stable circular orbit around a non-spinning hole.",
			},
			{
				name: "diskOuter",
				kind: "number",
				default: 12,
				min: 6,
				max: 24,
				step: 0.5,
				unit: "Rs",
				description:
					"Outer edge of the accretion disk, in Schwarzschild radii.",
			},
			{
				name: "diskBrightness",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Overall emission of the accretion disk.",
			},
			{
				name: "ringColor",
				kind: "color",
				default: "#ff9e38",
				description:
					"Recolors the accretion disk. White keeps the physical blackbody gradient (gold → white → blue) and the Doppler asymmetry; pick a hue to tint the ring without dimming it.",
			},
			{
				name: "dopplerMax",
				kind: "number",
				default: 1,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Relativistic Doppler beaming and redshift strength. 0 flattens the disk to symmetric; 1 is the physical approaching-side-brighter, receding-side-dimmer asymmetry.",
			},
			{
				name: "starBrightness",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"Brightness of the gravitationally lensed background stars and Milky Way band.",
			},
			{
				name: "skyFloor",
				kind: "number",
				default: 0.02,
				min: 0,
				max: 0.2,
				step: 0.005,
				description:
					"Ambient deep-space glow filling the void behind the stars. Tinted by the halo color.",
			},
			{
				name: "rotationSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 4,
				step: 0.1,
				unit: "×",
				description:
					"Speed of the cinematic camera orbit and the disk's differential swirl. 0 stops both.",
			},
			{
				name: "fov",
				kind: "number",
				default: 85,
				min: 30,
				max: 150,
				step: 1,
				unit: "°",
				description:
					"Observer camera field of view. Wider pushes the hole smaller and exaggerates the lensing curvature; narrower zooms in and flattens the perspective.",
			},
			{
				name: "bloomStrength",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"Intensity of the HDR bloom that blooms the bright disk and photon ring. 0 disables the bloom passes entirely.",
			},
			{
				name: "bloomRadius",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 2,
				step: 0.05,
				unit: "×",
				description: "Spread of the bloom blur. Disabled when bloom is 0.",
				disabledWhen: { prop: "bloomStrength", equals: 0 },
			},
			{
				name: "vignette",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Darkening toward the frame edges.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Animated fine film grain over the final image.",
			},
			{
				name: "chromaticAberration",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Lens-edge color fringing, strongest toward the corners.",
			},
			{
				name: "autoOrbit",
				kind: "boolean",
				default: true,
				description:
					"Spin the camera continuously left-to-right around the hole at a fixed distance. Drag to take manual 360° control; the orbit resumes a few seconds after you let go and keeps spinning around your current view — it never resets the angle. Off freezes the current view, which you can still drag.",
			},
			{
				name: "debug",
				kind: "enum",
				default: "off",
				options: ["off", "steps", "disk", "min-r", "escape-dir", "redshift"],
				description:
					"Diagnostic shader outputs — step-count heatmap, disk-hit mask, closest-approach radius, escape direction, and the redshift factor.",
			},
			{
				name: "tint",
				kind: "color",
				default: "#a855f7",
				description:
					"Accent that tints only the outer halo, photon ring, sky floor, and hero-star glow. The accretion disk keeps its physical blackbody color.",
			},
		],
	},
	{
		slug: "vortex-bloom",
		name: "VortexBloom",
		category: "Power-User Systems",
		tier: "free",
		pausable: true,
		description:
			"A molten-gold-and-obsidian vortex funnel spiraling into a luminous SDF core — lotus, gem, or flame — raymarched per-pixel in a WebGL2 shader, with a GPU dust field spiraling down the flow toward the throat, all under a draggable orbit and a real two-pass bloom.",
		dependencies: ["ogl", "clsx", "tailwind-merge"],
		cookbook: ["Orbit", "Loop", "Drag", "Blur"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/vortex-bloom/VortexBloom.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "primary",
				kind: "color",
				default: "#f0a830",
				description:
					"Molten-gold high tone — the color of the swirling streaks and the throat glints.",
			},
			{
				name: "secondary",
				kind: "color",
				default: "#120e1a",
				description:
					"Obsidian deep tone — the funnel's shadowed lanes and the void behind it.",
			},
			{
				name: "accent",
				kind: "color",
				default: "#ffe7a3",
				description:
					"Luminous core-emission tint. Drives the color of the convergence bloom and the dust as it reaches the core.",
			},
			{
				name: "coreObject",
				kind: "enum",
				default: "lotus",
				options: ["lotus", "gem", "flame"],
				description:
					"The centerpiece sitting at the vortex's convergence — a layered petal lotus, a faceted crystal, or an animated flame plume. Swapping it never moves the point the dust flows toward.",
			},
			{
				name: "coreScale",
				kind: "number",
				default: 1.5,
				min: 0.5,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Scales the centerpiece — lotus, gem, or flame — up or down without moving the convergence the dust flows toward.",
			},
			{
				name: "stemLength",
				kind: "number",
				default: 1.4,
				min: 0,
				max: 3,
				step: 0.1,
				description:
					"Length of the lotus stalk hanging into the flow beneath the flower. Lotus only; 0 removes it.",
			},
			{
				name: "vortexIntensity",
				kind: "number",
				default: 7,
				min: 1,
				max: 10,
				step: 0.5,
				description:
					"Swirl speed, streak turbulence, and dust inflow speed. Higher winds the funnel tighter and faster.",
			},
			{
				name: "glowIntensity",
				kind: "number",
				default: 8,
				min: 1,
				max: 10,
				step: 0.5,
				description:
					"Core emission and HDR bloom strength. Drives how hard the convergence and the dust bloom.",
			},
			{
				name: "particleDensity",
				kind: "number",
				default: 200,
				min: 0,
				max: 1200,
				step: 50,
				description:
					"Dust grains spiraling down the flow. Capped at 1200 to hold 60fps on a mid-range GPU.",
			},
			{
				name: "particleSpeed",
				kind: "number",
				default: 0,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"How fast the dust grains stream down the flow toward the core, independent of the swirl speed.",
			},
			{
				name: "smokeAmount",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 2,
				step: 0.05,
				description:
					"Soft, low-frequency atmospheric haze drifting behind the ribbons. 0 leaves crisp streaks on obsidian; higher fills the frame with smoke.",
			},
			{
				name: "cameraAutoRotate",
				kind: "boolean",
				default: true,
				description:
					"Continuously orbit the funnel. Drag to take 360° control; the orbit resumes around your current view a moment after you let go.",
			},
			{
				name: "rotationSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 4,
				step: 0.1,
				unit: "×",
				description: "Speed of the cinematic camera orbit.",
				disabledWhen: { prop: "cameraAutoRotate", equals: false },
			},
			{
				name: "fov",
				kind: "number",
				default: 60,
				min: 30,
				max: 120,
				step: 1,
				unit: "°",
				description:
					"Observer field of view. Wider exaggerates the whirlpool's depth; narrower flattens it.",
			},
			{
				name: "verticalOffset",
				kind: "number",
				default: 0,
				min: -1,
				max: 1,
				step: 0.05,
				description:
					"Slides the whole vortex up or down in the frame without moving the camera — recenter the eye where you want it.",
			},
			{
				name: "chromaticAberration",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Lens-edge color fringing, strongest toward the corners.",
			},
			{
				name: "vignette",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Darkening toward the frame edges.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.02,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Animated fine film grain over the final image.",
			},
		],
	},
	{
		slug: "flock-field",
		name: "FlockField",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A murmuration of hundreds of boids wheeling as one — separation, alignment, and cohesion resolved every frame through a spatial hash for the crowd, banking toward or scattering from your cursor, smeared into long trails of amethyst and cyan as the flock folds across the dark.",
		dependencies: [],
		cookbook: ["Loop", "Idle animation", "Hover effect", "Follow-through"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/flock-field/FlockField.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "count",
				kind: "number",
				default: 300,
				min: 50,
				max: 1000,
				step: 10,
				description:
					"Number of boids in the flock. Spatial-hash lookup keeps it near-linear.",
			},
			{
				name: "speed",
				kind: "number",
				default: 2.5,
				min: 0.5,
				max: 6,
				step: 0.1,
				description: "Maximum boid speed, px per frame.",
			},
			{
				name: "separation",
				kind: "number",
				default: 1.2,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Weight of steering away from close neighbors.",
			},
			{
				name: "alignment",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Weight of matching neighbors' heading.",
			},
			{
				name: "cohesion",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				description: "Weight of steering toward the neighbor center of mass.",
			},
			{
				name: "neighborRadius",

				kind: "number",
				default: 60,
				min: 20,
				max: 150,
				step: 5,
				unit: "px",
				description:
					"How far a boid sees neighbors; sets the spatial-hash cell size.",
			},
			{
				name: "separationRadius",

				kind: "number",
				default: 24,
				min: 5,
				max: 60,
				step: 1,
				unit: "px",
				description: "Distance under which boids actively push apart.",
			},
			{
				name: "cursorMode",

				kind: "enum",
				default: "repel",
				options: ["attract", "repel", "off"],
				description:
					"Whether the cursor draws the flock in, scatters it, or is ignored.",
			},
			{
				name: "cursorForce",
				kind: "number",
				default: 1.5,
				min: 0,
				max: 5,
				step: 0.1,
				description: "Strength of the cursor's pull or push.",
				disabledWhen: { prop: "cursorMode", equals: "off" },
			},
			{
				name: "cursorRadius",
				kind: "number",
				default: 160,
				min: 40,
				max: 400,
				step: 10,
				unit: "px",
				description: "Radius of the cursor's influence.",
				disabledWhen: { prop: "cursorMode", equals: "off" },
			},
			{
				name: "trail",
				kind: "number",
				default: 0.85,
				min: 0,
				max: 0.95,
				step: 0.05,
				description:
					"Motion-trail persistence — 0 is crisp, high smears long tails.",
			},
			{
				name: "color1",
				kind: "color",
				default: "#a855f7",
				description: "Slow-boid color.",
			},
			{
				name: "color2",
				kind: "color",
				default: "#22d3ee",
				description: "Fast-boid color — boids grade between the two by speed.",
			},
		],
	},
	{
		slug: "smoke-field",
		name: "SmokeField",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A real-time GPU fluid you can stir — semi-Lagrangian advection, a Jacobi pressure solve, and vorticity confinement run every frame across ping-ponged float buffers, injecting a dark amethyst plume that curls, billows, and bleeds through the frame wherever you drag.",
		dependencies: ["ogl"],
		cookbook: ["Drag", "Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/smoke-field/SmokeField.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "dyeColor",
				kind: "color",
				default: "#a855f7",
				description: "Color of the dye injected into the fluid.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#05010a",
				description: "Background the plume rises against.",
			},
			{
				name: "quality",
				kind: "enum",
				default: "medium",
				options: ["low", "medium", "high"],
				description:
					"Bundles simulation and dye buffer resolution. Higher is finer and costlier.",
			},
			{
				name: "pressureIterations",
				kind: "number",
				default: 25,
				min: 10,
				max: 60,
				step: 5,
				description:
					"Jacobi pressure passes per frame — higher makes the flow tighter and more incompressible.",
			},
			{
				name: "velocityFade",
				kind: "number",
				default: 0.98,
				min: 0.9,
				max: 1,
				step: 0.005,
				description: "How long motion persists before it dissipates.",
			},
			{
				name: "densityFade",
				kind: "number",
				default: 0.97,
				min: 0.9,
				max: 1,
				step: 0.005,
				description: "How long the dye lingers before fading out.",
			},
			{
				name: "curl",
				kind: "number",
				default: 20,
				min: 0,
				max: 50,
				step: 1,
				description:
					"Vorticity-confinement strength — swirl detail. 0 skips the curl passes.",
			},
			{
				name: "splatRadius",
				kind: "number",
				default: 0.2,
				min: 0.05,
				max: 0.5,
				step: 0.01,
				description: "Size of the dye and force splat under the pointer.",
			},
			{
				name: "splatForce",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description: "Velocity impulse imparted by a pointer drag.",
			},
			{
				name: "autoPlume",
				kind: "boolean",
				default: true,
				description:
					"Continuously inject a rising plume at the base when idle.",
			},
			{
				name: "buoyancy",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				description:
					"Upward force lifting the dye, so smoke rises. 0 lets it drift neutrally.",
			},
			{
				name: "exposure",
				kind: "number",
				default: 1.2,
				min: 0.5,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Brightness of the rendered dye.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.04,
				min: 0,
				max: 0.3,
				step: 0.01,
				description: "Animated grain over the final image.",
			},
		],
	},
	{
		slug: "ripple-field",
		name: "RippleField",
		category: "Power-User Systems",
		tier: "pro",
		pausable: true,
		description:
			"A pool of dark, moonlit water you disturb by hand — a leapfrog solve of the 2D wave equation runs on a ping-ponged float field, ringing every pointer move outward, reflecting the swell off the walls, and lighting the surface with gradient-normal refraction, curvature-focused caustics, and a Fresnel glint riding each wavefront.",
		dependencies: ["ogl"],
		cookbook: ["Ripple", "Drag", "Loop"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ripple-field/RippleField.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "waterColor",
				kind: "color",
				default: "#F7FAFF",
				description:
					"Amethyst tint of the water — specular glints, caustics, and crest light.",
			},
			{
				name: "deepColor",
				kind: "color",
				default: "#1227E1",
				description: "Deep pool base color the surface sits over.",
			},
			{
				name: "quality",
				kind: "enum",
				default: "medium",
				options: ["low", "medium", "high"],
				description:
					"Simulation grid resolution. Higher is crisper and costlier.",
			},
			{
				name: "tension",
				kind: "number",
				default: 0.35,
				min: 0.05,
				max: 0.49,
				step: 0.01,
				description:
					"Wave propagation speed. Higher spreads ripples faster; the leapfrog solve caps below 0.5 to stay stable.",
			},
			{
				name: "damping",
				kind: "number",
				default: 0.99,
				min: 0.9,
				max: 0.999,
				step: 0.001,
				description:
					"Per-step energy retention — toward 1 the ripples ring on longer.",
			},
			{
				name: "splatForce",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Displacement a pointer drag or ambient drop carves into the surface.",
			},
			{
				name: "splatRadius",
				kind: "number",
				default: 0.03,
				min: 0.005,
				max: 0.1,
				step: 0.005,
				description:
					"Size of the surface dimple under the pointer, in screen fractions.",
			},
			{
				name: "refraction",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"How strongly the surface slope bends the pool floor beneath the ripples.",
			},
			{
				name: "specular",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Intensity of the specular and Fresnel glints on each wavefront.",
			},
			{
				name: "glossiness",
				kind: "number",
				default: 96,
				min: 8,
				max: 200,
				step: 4,
				description:
					"Specular tightness — higher is a sharper, glassier highlight.",
			},
			{
				name: "caustics",
				kind: "number",
				default: 1.5,
				min: 0,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Brightness of the caustic threads where converging wavefronts focus light.",
			},
			{
				name: "autoRipple",
				kind: "boolean",
				default: true,
				description:
					"Randomly drop into the pool when idle so it never sits perfectly still.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0,
				min: 0,
				max: 0.2,
				step: 0.01,
				description: "Animated fine grain over the final image.",
			},
		],
	},
	{
		slug: "file-explorer",
		name: "FileExplorer",
		category: "Power-User Systems",
		tier: "pro",
		description:
			"A persistent three-pane file manager that stores real image, video, and blob uploads 100% client-side — OPFS when available, IndexedDB everywhere else — with nested folders, search, sort, drag-and-drop upload, move, and a live preview panel.",
		dependencies: ["lucide-react", "motion", "react-resizable-panels"],
		cookbook: ["Drag", "Layout animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/file-explorer/FileExplorer.tsx",
			},
			...FILE_EXPLORER_PEERS,
		],
		props: [
			{
				name: "defaultView",
				kind: "enum",
				default: "grid",
				options: ["grid", "list"],
				description:
					"Initial content layout. The toolbar toggle overrides it live.",
			},
			{
				name: "thumbnailSize",
				kind: "number",
				default: 112,
				min: 72,
				max: 220,
				step: 4,
				unit: "px",
				description: "Grid tile edge length. Larger tiles, fewer columns.",
			},
			{
				name: "density",
				kind: "enum",
				default: "comfortable",
				options: ["comfortable", "compact"],
				description:
					"Row height and padding for the list view and folder rail.",
			},
			{
				name: "sortBy",
				kind: "enum",
				default: "name",
				options: ["name", "date", "size", "type"],
				description:
					"Initial sort field. The toolbar sort menu overrides it live.",
			},
			{
				name: "sortDir",
				kind: "enum",
				default: "asc",
				options: ["asc", "desc"],
				description: "Initial sort direction.",
			},
			{
				name: "showFolderRail",
				kind: "boolean",
				default: true,
				description: "Show the left folder-tree rail.",
			},
			{
				name: "showDetails",
				kind: "boolean",
				default: true,
				description: "Open the detail panel when a single file is selected.",
			},
			{
				name: "showHidden",
				kind: "boolean",
				default: false,
				description: "Reveal entries whose name starts with a dot.",
			},
			{
				name: "allowUpload",
				kind: "boolean",
				default: true,
				description:
					"Enable drag-and-drop and the Add button. Off makes the explorer read-only for new files.",
			},
			{
				name: "allowDelete",
				kind: "boolean",
				default: true,
				description:
					"Enable delete, rename, and move. Off locks the store's contents.",
			},
			{
				name: "undoWindowMs",
				kind: "number",
				default: 5000,
				min: 0,
				max: 15000,
				step: 500,
				unit: "ms",
				description: "Grace period to undo a delete. 0 deletes immediately.",
				disabledWhen: { prop: "allowDelete", equals: false },
			},
			{
				name: "accent",
				kind: "color",
				default: "#a855f7",
				description: "Selection highlight, active folder, and focus accent.",
			},
		],
	},
	{
		slug: "umbral-orrery",
		name: "UmbralOrrery",
		category: "Power-User Systems",
		tier: "free",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"An orrery of moons casting real eclipse shadows across a shadowed world; drag to orbit.",
		dependencies: ["three", "@react-three/fiber", "clsx", "tailwind-merge"],
		cookbook: ["Orbit", "Loop", "Drag"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/umbral-orrery/UmbralOrrery.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "moonCount",
				kind: "number",
				default: 3,
				min: 1,
				max: 6,
				step: 1,
				description: "Number of orbiting moons.",
			},
			{
				name: "orbitSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Global orbit speed.",
			},
			{
				name: "sunIntensity",
				kind: "number",
				default: 2,
				min: 0,
				max: 5,
				step: 0.1,
				description: "Sun brightness, which drives shadow contrast.",
			},
			{
				name: "tilt",
				kind: "number",
				default: 0.3,
				min: 0,
				max: 1.2,
				step: 0.05,
				unit: "rad",
				description: "Inclination of the orbital planes.",
			},
			{
				name: "planetSize",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 2,
				step: 0.1,
				description: "Radius of the shadowed planet.",
			},
			{
				name: "moonSize",
				kind: "number",
				default: 0.35,
				min: 0.1,
				max: 0.8,
				step: 0.05,
				description: "Radius of the moons.",
			},
			{
				name: "sunColor",
				kind: "color",
				default: "#f0a830",
				description: "Warm color of the sun and its light.",
			},
			{
				name: "glowColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst atmosphere rim on the planet.",
			},
			{
				name: "cameraDistance",
				kind: "number",
				default: 8,
				min: 4,
				max: 16,
				step: 0.5,
				description: "Camera orbit radius.",
			},
		],
	},
	{
		slug: "parallax-rail",
		name: "ParallaxRail",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-07-26",
		description:
			"A pinned section where scrolling down drives content sideways across depth planes moving at different rates.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Parallax",
			"Scroll-driven animation",
			"Translate",
			"Orchestration",
			"Mask",
			"Compositing",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/parallax-rail/ParallaxRail.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "planes",
				kind: "number",
				default: 3,
				min: 1,
				max: 3,
				step: 1,
				description: "How many depth planes to render.",
			},
			{
				name: "travel",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 2.5,
				step: 0.1,
				unit: "×",
				description: "Multiplier on the front rail's travel across the pin.",
			},
			{
				name: "depthSpread",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much slower the backmost plane moves than the front.",
			},
			{
				name: "damping",
				kind: "number",
				default: 30,
				min: 10,
				max: 90,
				step: 5,
				description:
					"Spring damping on the scrub — higher tracks scroll exactly.",
			},
			{
				name: "fadeEdges",
				kind: "number",
				default: 0.12,
				min: 0,
				max: 0.4,
				step: 0.02,
				description: "Width of the soft mask at each rail edge.",
			},
			{
				name: "railGap",
				kind: "number",
				default: 24,
				min: 8,
				max: 64,
				step: 4,
				unit: "px",
				description: "Vertical gap between planes.",
			},
		],
	},
	{
		slug: "elastic",
		name: "Elastic",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-07-26",
		description:
			"Throw the top card and the speed you released it at carries into the spring — throw it far enough and it cycles to the back of the deck instead of coming home.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Spring",
			"Swipe to dismiss",
			"Stiffness / Tension",
			"Damping",
			"Mass",
			"Momentum",
			"Velocity",
			"Interruptible animation",
			"Rubber-banding",
			"Drag",
			"Bounce",
			"Follow-through",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/elastic/Elastic.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 320,
				min: 60,
				max: 800,
				step: 20,
				description: "How strongly the spring pulls home. Higher is snappier.",
			},
			{
				name: "damping",
				kind: "number",
				default: 22,
				min: 5,
				max: 60,
				step: 1,
				description: "How fast it settles. Lower overshoots and oscillates.",
			},
			{
				name: "mass",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 4,
				step: 0.1,
				description: "How heavy the card feels. More mass is more sluggish.",
			},
			{
				name: "bounds",
				kind: "number",
				default: 140,
				min: 40,
				max: 400,
				step: 10,
				unit: "px",
				description: "How far the card may travel from home.",
			},
			{
				name: "rubberBand",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description: "Give past the bounds, hard wall → loose.",
			},
			{
				name: "flickPower",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 3,
				step: 0.1,
				unit: "×",
				description: "Multiplier on the release velocity handed to the spring.",
			},
			{
				name: "cards",
				kind: "number",
				default: 3,
				min: 1,
				max: 5,
				step: 1,
				description: "How many cards in the stack.",
			},
			{
				name: "throwThreshold",
				kind: "number",
				default: 90,
				min: 20,
				max: 260,
				step: 10,
				unit: "px",
				description:
					"Throw distance past which the card cycles to the back instead of springing home. Capped at 90% of bounds so it stays reachable.",
			},
		],
	},
	{
		slug: "masonry",
		name: "Masonry",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-07-27",
		description:
			"A Pinterest-style grid where every item drops into the shortest column, packed by measurement rather than by a shared row baseline.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Layout animation",
			"Stagger",
			"Scroll reveal",
			"Spatial consistency",
			"Layout thrashing",
			"will-change",
			"Compositing",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/masonry/Masonry.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "minColumnWidth",
				kind: "number",
				default: 240,
				min: 120,
				max: 480,
				step: 10,
				unit: "px",
				description:
					"Target column width. The column count is derived from the container, not the viewport.",
			},
			{
				name: "maxColumns",
				kind: "number",
				default: 4,
				min: 1,
				max: 8,
				step: 1,
				description:
					"Ceiling on the derived column count, however wide the container gets.",
			},
			{
				name: "gap",
				kind: "number",
				default: 16,
				min: 0,
				max: 48,
				step: 2,
				unit: "px",
				description: "Space between columns and between stacked items.",
			},
			{
				name: "packing",
				kind: "enum",
				default: "balanced",
				options: ["balanced", "sequential"],
				description:
					"Balanced packs into the shortest column; sequential keeps strict left-to-right order.",
			},
			{
				name: "transition",
				kind: "number",
				default: 320,
				min: 0,
				max: 800,
				step: 20,
				unit: "ms",
				description: "How long an item takes to glide to a new slot. 0 snaps.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 45,
				min: 0,
				max: 120,
				step: 5,
				unit: "ms",
				description: "Delay added per item as a batch reveals.",
				disabledWhen: { prop: "revealOnScroll", equals: false },
			},
			{
				name: "revealOnScroll",
				kind: "boolean",
				default: true,
				description: "Fade and rise each item in as it enters the viewport.",
			},
			{
				name: "revealDistance",
				kind: "number",
				default: 16,
				min: 0,
				max: 64,
				step: 4,
				unit: "px",
				description: "How far an item rises on reveal.",
				disabledWhen: { prop: "revealOnScroll", equals: false },
			},
		],
	},
	{
		slug: "rubiks-cube",
		name: "RubiksCube",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-02",
		pausable: true,
		description:
			"A Rubik's cube that scrambles and solves itself on an endless loop while spinning like a planet. Two independent rotation layers, and every quarter-turn is quantised back to exact integers, so an hour of turns drifts by nothing at all.",
		dependencies: ["three", "@react-three/fiber", "clsx", "tailwind-merge"],
		cookbook: ["Rotate", "Orbit", "Loop", "Drag", "Easing", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/rubiks-cube/RubiksCube.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "autoRotate",
				kind: "boolean",
				default: true,
				description:
					"Spin the whole cube on its own axis, independently of the solve loop. Off leaves the cube still while it keeps scrambling and solving.",
			},
			{
				name: "rotationSpeed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"Multiplier on the ambient spin rate. A drag re-aims the spin axis but never changes this — direction is yours, speed is the component's.",
				disabledWhen: { prop: "autoRotate", equals: false },
			},
			{
				name: "moveDuration",
				kind: "number",
				default: 380,
				min: 120,
				max: 1200,
				step: 10,
				unit: "ms",
				description:
					"How long one quarter-turn takes. The ease overshoots slightly and settles back, which is the mechanical click a real cube makes.",
			},
			{
				name: "scrambleMoveCount",
				kind: "number",
				default: 12,
				min: 1,
				max: 30,
				step: 1,
				description:
					"Quarter-turns per scramble. The solve is this sequence replayed backwards and negated, so a longer scramble buys a longer solve for free.",
			},
			{
				name: "pauseBetweenCycles",
				kind: "number",
				default: 700,
				min: 0,
				max: 3000,
				step: 50,
				unit: "ms",
				description:
					"Beat of stillness between scramble and solve. Zero runs the two together into one continuous churn.",
			},
			{
				name: "cameraDistance",
				kind: "number",
				default: 11,
				min: 6,
				max: 22,
				step: 0.5,
				description:
					"Orbit radius, which is what sets the cube's apparent size. Drag anywhere to orbit; elevation stops short of the poles so the cube never tumbles sideways.",
			},
			{
				name: "gap",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 0.3,
				step: 0.01,
				description:
					"Space between cubies, in cubie widths. Widen it and the black core shows through the seams, exactly as a real cube's does.",
			},
			{
				name: "palette",
				kind: "enum",
				default: "classic",
				options: ["classic", "amethyst", "mono", "neon"],
				description:
					"Named sticker scheme. The component also takes a `colors` record to override any individual face.",
			},
			{
				name: "bodyColor",
				kind: "color",
				default: "#16161c",
				description:
					"Plastic behind the stickers, and the core seen through the seams.",
			},
			{
				name: "background",
				kind: "color",
				default: "#0b0d14",
				description: "The dark field the cube turns in.",
			},
			{
				name: "glossy",
				kind: "boolean",
				default: true,
				description:
					"Wet-lacquer clearcoat plus a faint oil-slick sheen, lit by a small studio environment. Off leaves flat matte plastic.",
			},
			{
				name: "glow",
				kind: "boolean",
				default: false,
				description:
					"Emissive stickers plus an additive amethyst halo at the silhouette. Off by default: it is a flourish, not the point.",
			},
		],
	},
	{
		slug: "approval-flow",
		name: "ApprovalFlow",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			'A step-by-step approval checklist for agent permissions — radio and checkbox groups, an "Other…" escape hatch that grows a field in place, and per-step validation that blocks the commit. Answering a step sends the chosen option flying into a running record of what you have already decided, so the screen accumulates a decision trail instead of replacing itself.',
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Morph",
			"Shared element transition",
			"Layout animation",
			"Stepped animation",
			"Direction-aware transition",
			"Shake / Wiggle",
			"Spatial consistency",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/approval-flow/ApprovalFlow.tsx",
			},
			...APPROVAL_FLOW_PEERS,
			UTILS_VARIANT,
		],
		props: [
			{
				name: "layout",
				kind: "enum",
				default: "rail",
				options: ["rail", "inline"],
				description:
					"Where the record of decided steps sits. A rail parks it beside the live step on wide screens; inline stacks it above.",
			},
			{
				name: "morphDuration",
				kind: "number",
				default: 420,
				min: 120,
				max: 1200,
				step: 10,
				unit: "ms",
				description:
					"Step change, option reveal and the escape hatch growing open. The flight into the record is a spring and ignores this — stiffness and damping own that one.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 380,
				min: 80,
				max: 800,
				step: 10,
				description:
					"How hard the chosen option is pulled toward its slot in the record.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 8,
				max: 80,
				step: 1,
				description:
					"How fast that flight settles. Low values let the label overshoot its slot before landing.",
			},
			{
				name: "density",
				kind: "enum",
				default: "comfortable",
				options: ["comfortable", "compact"],
				description: "Row height, padding and glyph size throughout.",
			},
			{
				name: "revealStagger",
				kind: "number",
				default: 45,
				min: 0,
				max: 200,
				step: 5,
				unit: "ms",
				description:
					"Delay added per option as a step's list arrives. 0 lands the whole group at once.",
			},
			{
				name: "shakeIntensity",
				kind: "number",
				default: 6,
				min: 0,
				max: 16,
				step: 1,
				unit: "px",
				description:
					"Travel of the shake when a step is rejected. 0 disables it — the message and the red border still fire, because a rejection with no signal at all is a dead end.",
			},
			{
				name: "shakeCycles",
				kind: "number",
				default: 3,
				min: 1,
				max: 6,
				step: 1,
				description:
					"Round trips in that shake. Each one decays, and the last always ends on centre.",
				disabledWhen: { prop: "shakeIntensity", equals: 0 },
			},
			{
				name: "showProgress",
				kind: "boolean",
				default: true,
				description: "Completion bar and step count above the live step.",
			},
			{
				name: "autoAdvance",
				kind: "boolean",
				default: false,
				description:
					"Commit a single-choice step the moment it is answered. Never applies to the escape hatch, which needs a sentence first, and it is forced off under reduced motion.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description:
					"Selection, checked glyph, progress fill and the approve button.",
			},
			{
				name: "dangerColor",
				kind: "color",
				default: "#f87171",
				description: "Invalid row border and the rejection message.",
			},
		],
	},
	{
		slug: "diff-review",
		name: "DiffReview",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			"A review surface for a patch an agent has proposed — accept or reject each hunk, fold long runs of unchanged lines away, and flip between unified and split. Switching views does not redraw the diff: every line is a shared element that flies from the stream into its column and back, so you never lose the line you were reading.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Morph",
			"Shared element transition",
			"Layout animation",
			"Crossfade",
			"Stagger",
			"Accordion / Collapse",
			"Spatial consistency",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/diff-review/DiffReview.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "defaultView",
				kind: "enum",
				default: "unified",
				options: ["unified", "split"],
				description:
					"Starting layout. One interleaved stream, or the old file beside the new one. The toolbar toggle overrides it live.",
			},
			{
				name: "morphDuration",
				kind: "number",
				default: 380,
				min: 120,
				max: 1200,
				step: 10,
				unit: "ms",
				description:
					"Hunk fold, verdict change and the first reveal of a line. The flight between views is a spring and ignores this — stiffness and damping own that one.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 420,
				min: 80,
				max: 800,
				step: 10,
				description:
					"How hard a line is pulled toward its slot in the other view.",
			},
			{
				name: "damping",
				kind: "number",
				default: 38,
				min: 8,
				max: 80,
				step: 1,
				description:
					"How fast that flight settles. Low values let a line overshoot its column before landing.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 14,
				min: 0,
				max: 80,
				step: 2,
				unit: "ms",
				description:
					"Delay added per line as a hunk first appears. Capped at twelve lines in, so expanding a long fold never leaves the last row waiting in plain sight.",
			},
			{
				name: "density",
				kind: "enum",
				default: "comfortable",
				options: ["comfortable", "compact"],
				description: "Row height and type size throughout.",
			},
			{
				name: "showLineNumbers",
				kind: "boolean",
				default: true,
				description:
					"Old and new line numbers in the gutter. Split view shows one per side; unified shows the surviving number.",
			},
			{
				name: "contextLines",
				kind: "number",
				default: 3,
				min: 0,
				max: 10,
				step: 1,
				description:
					"Unchanged lines kept on the side of a run that faces a change. The rest fold behind an expander — except a fold that would hide a single line, which costs a row to save a row.",
			},
			{
				name: "collapseDecided",
				kind: "boolean",
				default: true,
				description:
					"Fold a hunk's body away once it has a verdict, leaving the header and an Undo. Off keeps every hunk open so you can re-read what you just ruled on.",
			},
			{
				name: "addColor",
				kind: "color",
				default: "#4ade80",
				description:
					"Added lines, their gutter sign, and an accepted hunk's edge.",
			},
			{
				name: "delColor",
				kind: "color",
				default: "#f87171",
				description:
					"Removed lines, their gutter sign, and a rejected hunk's edge.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description:
					"Active view toggle, fold expanders, focus rings and the reviewed counter once every hunk has been ruled on.",
			},
		],
	},
	{
		slug: "ledger",
		name: "Ledger",
		category: "Power-User Systems",
		tier: "free",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"A live activity log for a working agent. Consecutive events from the same source fold into one block instead of stacking as identical rows, the window holds a fixed number and lets the rest fall off the top, and the scroll stays pinned to the newest line only until you scroll away from it — after that it keeps running and tells you how far behind you are.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Loop",
			"Idle animation",
			"Pulse",
			"Fade in / Fade out",
			"Slide in",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ledger/Ledger.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0.1,
				max: 3,
				step: 0.1,
				unit: "×",
				description:
					"Multiplier on the whole cadence — typing and the gaps between events together.",
			},
			{
				name: "charsPerSecond",
				kind: "number",
				default: 90,
				min: 10,
				max: 400,
				step: 10,
				description:
					"Typing rate before jitter. The full text of an event is in the accessibility tree from the moment it arrives, so only the eye waits for this.",
			},
			{
				name: "entryGap",
				kind: "number",
				default: 520,
				min: 0,
				max: 3000,
				step: 20,
				unit: "ms",
				description: "Pause between one event landing and the next starting.",
			},
			{
				name: "jitter",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Spread on the per-event rate, metronome to wildly uneven. A fast burst draws a longer breath after it, so the unevenness reads as work rather than as noise. Seeded, not random — the same run is reproducible every mount.",
			},
			{
				name: "maxEntries",
				kind: "number",
				default: 9,
				min: 3,
				max: 24,
				step: 1,
				description:
					"Events retained before the oldest falls off the top, under a fade that keeps the window reading as a view onto a longer log.",
			},
			{
				name: "group",
				kind: "boolean",
				default: true,
				description:
					"Fold consecutive same-source events into one block with a count. The block wears the worst severity in it, so a denial folded in among routine reads still shows red.",
			},
			{
				name: "showTimestamps",
				kind: "boolean",
				default: true,
				description:
					"Elapsed stream time beside each block. Measured from the component's own clock, never from the wall clock, so it is identical on every replay.",
			},
			{
				name: "caret",
				kind: "boolean",
				default: true,
				description:
					"Blinking block caret on the line currently being written.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: true,
				description:
					"Wrap to the first event when the source list runs out. Off lets the stream halt itself once, and the header reads complete.",
			},
			{
				name: "density",
				kind: "enum",
				default: "comfortable",
				options: ["comfortable", "compact"],
				description: "Row height and type size throughout.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description:
					"Live indicator, caret, catch-up pill and the ok severity.",
			},
			{
				name: "warnColor",
				kind: "color",
				default: "#f0a830",
				description: "The warn severity.",
			},
			{
				name: "denyColor",
				kind: "color",
				default: "#f87171",
				description: "The deny severity.",
			},
		],
	},
	{
		slug: "rotunda",
		name: "Rotunda",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-06",
		description:
			"Real HTML panels on a drag-spun 3D cylinder. A hand-rolled perspective projection written onto DOM elements rather than a canvas — so the text stays selectable, the links stay clickable, and a screen reader still reads every panel while the ring turns.",
		dependencies: [],
		cookbook: [
			"Drag",
			"Momentum",
			"Damping",
			"Perspective",
			"3D tilt / Flip",
			"Spatial consistency",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/rotunda/Rotunda.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "radius",
				kind: "number",
				default: 380,
				min: 160,
				max: 900,
				step: 10,
				unit: "px",
				description:
					"Distance from the axis to each panel face. Together with the number of panels this decides whether the ring closes: too small for the count and the faces intersect, which is the one way this arrangement can look broken rather than tight.",
			},
			{
				name: "perspective",
				kind: "number",
				default: 1200,
				min: 400,
				max: 3000,
				step: 50,
				unit: "px",
				description:
					"Depth of the projection, and the control that decides whether this reads as expensive or as a cheap paper fan. Near enough and the front panel distorts violently; far enough and the ring flattens into a row of cards.",
			},
			{
				name: "autoSpin",
				kind: "number",
				default: 0.06,
				min: 0,
				max: 1,
				step: 0.01,
				unit: "×",
				description:
					"Idle rotation while nothing is being dragged. It stops the instant the pointer arrives and does not restart until it leaves, because a carousel that keeps moving under your cursor is a carousel you cannot read.",
			},
			{
				name: "friction",
				kind: "number",
				default: 0.94,
				min: 0.8,
				max: 0.995,
				step: 0.005,
				description:
					"How much of a fling survives, and the whole feel of the throw. Applied per second rather than per frame, so the same gesture coasts the same distance on a 60Hz and a 120Hz display — the naive per-frame form silently halves the throw on better hardware.",
			},
			{
				name: "snap",
				kind: "boolean",
				default: true,
				description:
					"Settle to the nearest panel once a fling drops below walking pace. Off, the ring stops wherever it stops — honest for a texture, wrong for a menu.",
			},
			{
				name: "snapStiffness",
				kind: "number",
				default: 140,
				min: 20,
				max: 400,
				step: 10,
				disabledWhen: { prop: "snap", equals: false },
				description:
					"How hard the ring is pulled to the nearest face. Damping is derived from it at the critical ratio, so raising this arrives faster without ever adding the overshoot that would read as a wobble on a menu.",
			},
			{
				name: "depthDim",
				kind: "number",
				default: 0.65,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How far the back of the ring dims toward the background. Depth cueing sells the illusion harder than the rotation does, because a CSS transform gives you no occlusion to work with.",
			},
			{
				name: "depthBlur",
				kind: "number",
				default: 3,
				min: 0,
				max: 10,
				step: 0.5,
				unit: "px",
				description:
					"Blur on panels past the halfway point. Applied to an inner wrapper rather than the panel itself: a filter on a child of a preserve-3d parent establishes a containing block and flattens the entire ring into a stack.",
			},
			{
				name: "faceCamera",
				kind: "boolean",
				default: false,
				description:
					"Keep every panel square to the viewer rather than tangent to the ring. This turns the carousel into a card rack, and it is the right choice the moment the panels carry real copy you expect anyone to read off-centre.",
			},
			{
				name: "dragSensitivity",
				kind: "number",
				default: 0.35,
				min: 0.05,
				max: 1.5,
				step: 0.05,
				unit: "°/px",
				description:
					"Degrees of rotation per pixel of drag. The honest test is whether the panel under your finger stays under your finger — too low and the ring feels geared down, too high and a small gesture spins it past the panel you were reaching for.",
			},
		],
	},
	{
		slug: "ascii-engine",
		name: "AsciiEngine",
		category: "Power-User Systems",
		tier: "free",
		addedAt: "2026-08-07",
		description:
			"A lit, raymarched 3D solid rendered at exactly one pixel per character cell, then quantised into a glyph ramp drawn once with fillText. Drag to orbit it through a full three-sixty. Real geometry underneath, terminal on top — and no scene graph, no mesh, and no second library to get there.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Rotate",
			"Drag",
			"Momentum",
			"Stepped animation",
			"Idle animation",
			"Compositing",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/ascii-engine/AsciiEngine.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "solid",
				kind: "enum",
				default: "torus-knot",
				options: ["torus-knot", "cube", "sphere", "gyroid", "column"],
				description:
					"Which distance field is raymarched into the first pass. A field rather than a mesh: the silhouette stays exact at any cell size because it is evaluated instead of rasterised, which is why this needs no scene graph and no geometry upload.",
			},
			{
				name: "charset",
				kind: "enum",
				default: "classic",
				options: ["classic", "blocks", "minimal", "binary", "dots"],
				description:
					"The glyph ramp, darkest to lightest. The atlas is drawn once with fillText into an offscreen canvas and uploaded as a single texture, so the shader just indexes it and a longer ramp costs nothing per frame.",
			},
			{
				name: "cellSize",
				kind: "number",
				default: 10,
				min: 4,
				max: 28,
				step: 1,
				unit: "px",
				description:
					"Width of one character cell, and the real resolution control. The first pass renders at exactly one texel per cell, so halving this quadruples the raymarch and changes nothing else — which makes it the honest performance dial rather than a cosmetic one.",
			},
			{
				name: "spinSpeed",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Rotation speed of the solid. At zero it parks, which is the only way to judge whether the ramp is actually resolving the form or just flickering convincingly.",
			},
			{
				name: "tilt",
				kind: "number",
				default: 0.4,
				min: -1,
				max: 1,
				step: 0.05,
				description:
					"Resting camera elevation. Dragging orbits from here rather than replacing it, so this control still means something after you have spun the solid around — and the pitch is clamped short of the poles, because a camera that rolls over the top reads as a bug rather than as a rotation you asked for.",
			},
			{
				name: "zoom",
				kind: "number",
				default: 1,
				min: 0.4,
				max: 2.5,
				step: 0.05,
				unit: "×",
				description:
					"How much of the frame the solid fills. It narrows the field of view rather than moving the camera in — dollying would clip the near face of the solid long before its silhouette filled the frame, which looks like a broken near plane rather than a close-up.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 1.1,
				min: 0.2,
				max: 3,
				step: 0.05,
				description:
					"Gamma on the luminance before it picks a glyph, and what decides whether the solid reads as a form or as noise. The ramp has ten steps at most and the lighting has to spread across all of them — too little and the shape collapses into two characters.",
			},
			{
				name: "edgeBoost",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"How much of the silhouette is added back before quantising. Pure luminance loses the outline — a ten-step ramp cannot carry both the shading and the contour, so without this the form dissolves into its own gradient.",
			},
			{
				name: "glow",
				kind: "number",
				default: 0.3,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"Bloom bleeding off the lit glyphs, driven by the cell's luminance rather than by the glyph's own coverage — so a bright cell glows whether it landed on a full block or a full stop.",
			},
			{
				name: "inkColor",
				kind: "color",
				default: "#7ef0c0",
				description: "The phosphor the glyphs are printed in.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#04060a",
				description: "The dead terminal behind them.",
			},
		],
	},
	{
		slug: "swarm",
		name: "Swarm",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-07",
		description:
			"Up to a quarter of a million particles integrated entirely on the GPU, morphing between words and solids, with a drag-orbit camera. Position and velocity live in floating-point textures and never come back to the CPU; text targets are sampled once out of an offscreen canvas, so the shape can be any string with no font atlas.",
		dependencies: ["ogl"],
		cookbook: [
			"Loop",
			"Morph",
			"Stagger",
			"Interpolation / Tween",
			"Idle animation",
			"Hover effect",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/swarm/Swarm.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "density",
				kind: "enum",
				default: "65k",
				options: ["16k", "65k", "131k", "262k"],
				description:
					"Particle count, as discrete steps rather than a slider. Each value reallocates four floating-point targets and rebuilds the geometry, and a slider would do that on every pixel of a drag. Sixty-five thousand is where letterforms close up. The simulation is nearly free above that — the cost is all fill rate — so the top step is for a machine you already know the answer about.",
			},
			{
				name: "shape",
				kind: "enum",
				default: "auto",
				options: ["auto", "text", "sphere", "torus", "grid", "disperse"],
				description:
					"What the cloud is heading for. Auto walks the list on a timer; the rest hold. Targets are sampled out of an offscreen 2D canvas, so the text form is whatever string you pass — the GPU never sees a glyph, only a texture of positions.",
			},
			{
				name: "morphSpeed",
				kind: "number",
				default: 1.1,
				min: 0.05,
				max: 3,
				step: 0.05,
				unit: "×",
				disabledWhen: { prop: "shape", equals: "disperse" },
				description:
					"How hard each particle is pulled toward its target. This is an acceleration, not a duration — the cloud arrives when the pull and the damping agree, which is why it never snaps. It also has to win against the turbulence: too low against a high curl and the letterforms never resolve, they just hover.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				disabledWhen: { prop: "shape", equals: "disperse" },
				description:
					"How much of the morph is spread across the cloud instead of happening at once. At zero every particle leaves and arrives together and it reads as a slide; near one the shape assembles over time and you can watch it build. The phase comes from each particle's own texel, so it does not reshuffle between shapes.",
			},
			{
				name: "curl",
				kind: "number",
				default: 0.3,
				min: 0,
				max: 2,
				step: 0.05,
				description:
					"Curl-noise turbulence applied on the way. Curl of a vector field is divergence-free by construction, so it stirs the cloud without ever thinning it or piling it up — which is the entire reason to use curl noise rather than plain noise on a velocity field, where the cloud slowly develops holes.",
			},
			{
				name: "damping",
				kind: "number",
				default: 0.9,
				min: 0.5,
				max: 0.995,
				step: 0.005,
				description:
					"How much velocity survives each step, applied per second rather than per frame. Below about 0.8 particles arrive dead and the shape has no life in it; above 0.97 they orbit their targets forever and never settle.",
			},
			{
				name: "repel",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"How hard the pointer pushes particles away on hover. Dragging orbits the camera instead — sharing one gesture between the two would mean every attempt to look around also blew a hole in what you were looking at. The falloff is exponential in squared distance, so the hole has a soft edge and the cloud closes behind your cursor rather than leaving a permanent scar.",
			},
			{
				name: "pointSize",
				kind: "number",
				default: 1.6,
				min: 0.5,
				max: 5,
				step: 0.1,
				unit: "px",
				description:
					"Point sprite width, and the real performance control. Doubling it costs four times the shading at any density — at a quarter of a million particles the simulation is trivial and the fill rate is what falls over, which is the opposite of where most people expect the cost to be.",
			},
			{
				name: "zoom",
				kind: "number",
				default: 1,
				min: 0.4,
				max: 2.5,
				step: 0.05,
				unit: "×",
				description:
					"How close the camera sits to the cloud. Sprite size scales with it: leaving the points fixed makes a zoomed-in cloud read as sparser rather than nearer, which is the tell that a zoom is really a viewport crop.",
			},
			{
				name: "particleColor",
				kind: "color",
				default: "#a855f7",
				description: "The colour of a settled particle.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#67e8f9",
				description:
					"The colour of a moving one. Particles are blended between the two by their own speed, so the palette is a readout of the simulation rather than decoration laid over it.",
			},
			{
				name: "backgroundColor",
				kind: "color",
				default: "#04040a",
				description:
					"The void behind the cloud. Points blend additively, so this wants to stay genuinely dark — anything lighter and the dense core clips to white before the count is visible.",
			},
		],
	},
	{
		slug: "mirage",
		name: "Mirage",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-07",
		description:
			"Live, fully interactive HTML seen through moving air. An animated turbulence field displaces the real DOM subtree per pixel — no snapshot, no canvas replica — so the text stays selectable, the button still takes focus and the link is still a link while the whole panel shimmers.",
		dependencies: [],
		cookbook: [
			"Hover effect",
			"Blur",
			"Mask",
			"Idle animation",
			"Compositing",
			"Hardware acceleration",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/mirage/Mirage.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "haze",
				options: ["haze", "liquify", "shatter", "tear"],
				description:
					"How the air moves. The four differ by the anisotropy of the noise rather than by strength: equal frequencies on both axes give soup, and a strongly biased axis is what makes a tear read as a tear instead of as more haze.",
			},
			{
				name: "intensity",
				kind: "number",
				default: 0.4,
				min: 0,
				max: 2,
				step: 0.05,
				description:
					"How far the content is pushed. This is genuine per-pixel displacement rather than a transform — a transform can only move the whole box, which is why skew-based heat haze never convinces. Past about one the text stops being readable, which is a legitimate look and a terrible default.",
			},
			{
				name: "speed",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Rate the field drifts. The noise is rasterised once as a seamless tile and scrolled, never re-seeded — stepping a turbulence seed swaps in an entirely unrelated field each time, which reads as a component tearing itself apart rather than as air moving. The wrap at one tile is invisible because the tile is seamless.",
			},
			{
				name: "scale",
				kind: "number",
				default: 2.2,
				min: 0.3,
				max: 4,
				step: 0.1,
				description:
					"Size of the turbulence cells, measured against a scrolling tile rather than against the element — so the same setting is the same air whether the panel is a card or a page. This sizes the tile itself, because a tile can hold no feature larger than its own period and the noise lattice only wraps on a whole number of cells; free the cell count instead and the field stops tiling, which shows up as the whole panel jumping to a different distortion once a wrap. Small cells shred the glyphs and large ones move the whole block as a unit; the interesting band is where a cell is roughly the height of a line of text.",
			},
			{
				name: "chroma",
				kind: "number",
				default: 0.25,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Strength of the colour cast the shimmer carries, gathered where the pointer is. Hot air refracts, so a little colour separation is the cue that sells it as air rather than as a wobbling image.",
			},
			{
				name: "trigger",
				kind: "enum",
				default: "always",
				options: ["always", "hover"],
				description:
					"What turns the effect on. Whichever you pick it eases rather than switches — a displacement that snaps on reads as the element being swapped out, one that rises reads as air beginning to move.",
			},
			{
				name: "edgeHold",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How much of the element's own silhouette is protected. Displacing evenly moves the border too, so a rounded card dissolves into an amoeba and the one edge a reader uses to locate it is the first thing destroyed. This tapers the push toward neutral near the boundary — at zero the outline shreds, and past about half the shimmer is confined to the middle of the panel.",
			},
			{
				name: "tintColor",
				kind: "color",
				default: "#a855f7",
				description: "The colour the shimmer carries.",
			},
		],
	},
	{
		slug: "submerge",
		name: "Submerge",
		category: "Power-User Systems",
		tier: "pro",
		addedAt: "2026-08-07",
		description:
			"Live content held under water. A slow current bends it continuously, a press drops a stone and a drag leaves a wake that trails behind the cursor — and the text underneath stays selectable, the button still answers and the link is still a link, because the water bends the real tree rather than a picture of it.",
		dependencies: [],
		cookbook: [
			"Ripple",
			"Hover effect",
			"Damping",
			"Idle animation",
			"Compositing",
			"Hardware acceleration",
		],
		pausable: true,
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/submerge/Submerge.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
		],
		props: [
			{
				name: "depth",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How deep the content sits. It drives the colour wash and adds to the bend, because the further under a surface something lies the further the same slope carries the light across it. Past about 0.8 the water starts winning and the content stops being the subject.",
			},
			{
				name: "flow",
				kind: "number",
				default: 1.25,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Speed of the ambient current. The field is rasterised once as a seamless tile and scrolled rather than regenerated — regenerating costs a PNG encode per frame, which is why so many browser water effects settle for a static distortion instead.",
			},
			{
				name: "turbulence",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.05,
				description:
					"How hard the current bends the content. This is genuine per-pixel displacement of the live tree, not a transform — a transform can only move the whole box, which is the reason skewed 'underwater' text never convinces.",
			},
			{
				name: "rippleForce",
				kind: "number",
				default: 0.8,
				min: 0,
				max: 2,
				step: 0.05,
				unit: "×",
				description:
					"Strength of the disturbance the pointer leaves. A press radiates an isotropic ring; a drag leaves a wake — the same wave packet stretched along travel and weighted to the rear, so the water is disturbed where the pointer has been rather than around where it is. Sources are spaced by distance travelled rather than by pointer event, so the same gesture leaves the same wake at 60Hz or 120Hz.",
			},
			{
				name: "rippleSpread",
				kind: "number",
				default: 1,
				min: 0.3,
				max: 3,
				step: 0.05,
				unit: "×",
				description:
					"How far a disturbance travels before it dies. Growth is an exponential approach rather than a square root: both decelerate, but a square root has infinite slope at zero, so every ring is born already moving and the birth itself snaps. A drag wake spreads slower than a press ring, because a trail lingers where it was left.",
			},
			{
				name: "settle",
				kind: "number",
				default: 1.6,
				min: 0.4,
				max: 5,
				step: 0.1,
				unit: "s",
				description:
					"Seconds a disturbance takes to die away. Twelve run at once and a thirteenth reuses the oldest slot, so a fast drag always shows its newest wake rather than queueing behind stale ones — and twelve is enough that eviction rarely cuts one off mid-life, which is the pop that reads as jumpy.",
			},
			{
				name: "edgeHold",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"How much of the element's own silhouette is protected. Displacing evenly moves the border too, so a rounded card dissolves into an amoeba and the one edge a reader uses to locate it is the first thing destroyed. At zero the outline shreds; past about half the water is confined to the middle.",
			},
			{
				name: "waterColor",
				kind: "color",
				default: "#bacffe",
				description: "Shallow water — the colour every ring crest carries.",
			},
			{
				name: "deepColor",
				kind: "color",
				default: "#d9e7f3",
				description:
					"Deep water. Applied as a multiply rather than an overlay, so the content keeps its own contrast instead of flattening behind a sheet of colour.",
			},
		],
	},
];
