import type { ComponentEntry, Variant } from "../types";

/** Upstream credit for entries adapted from React Bits (reactbits.dev, MIT).
 *  Rendered on the component page; the served source is comment-stripped, so
 *  the visible credit lives here, not in a code header. */
const REACTBITS = {
	name: "React Bits",
	url: "https://reactbits.dev",
};

/** lib/utils.ts ships with every entry whose source imports `cn`. Its own
 *  packages (clsx, tailwind-merge) are the host entry's to declare — the check
 *  walks into this file and finds them there (§V41). */
const UTILS_VARIANT: Variant = {
	lang: "ts",
	style: "tailwind",
	file: "lib/utils.ts",
	role: "util",
	label: "utils.ts",
};

/** Text Animations — kinetic type and number transitions. */
export const textAnimations: ComponentEntry[] = [
	{
		slug: "morphing-text",
		attribution: REACTBITS,
		name: "MorphingText",
		category: "Text Animations",
		description:
			"A gooey blur-morph that cross-dissolves between a list of words.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: ["Text morph", "Morph", "Crossfade", "Blur", "Loop"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/morphing-text/morphing-text.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "auto",
				kind: "boolean",
				default: true,
				description: "Loop through the words forever (off = morph once).",
			},
		],
	},
	{
		slug: "animated-number",
		name: "AnimatedNumber",
		category: "Text Animations",
		description:
			"Animated numeric transitions with flip, slide, fade, and bounce styles.",
		dependencies: ["motion"],
		cookbook: [
			"Number ticker",
			"Tabular numbers",
			"Bounce",
			"Slide in",
			"Fade in / Fade out",
			"3D tilt / Flip",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/animated-number/animated-number.tsx",
			},
		],
		props: [
			{
				name: "value",
				kind: "number",
				default: 999,
				min: 0,
				max: 9999,
				step: 1,
				description: "The value to display and animate to.",
			},
			{
				name: "animationType",
				kind: "enum",
				default: "flip",
				options: ["flip", "slide", "fade", "scale-bounce"],
				description: "Transition style between values.",
			},
			{
				name: "duration",
				kind: "number",
				default: 0.4,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Transition duration.",
			},
			{
				name: "staggerDelay",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.3,
				step: 0.01,
				unit: "s",
				description: "Delay between each digit's animation.",
			},
		],
	},
	{
		slug: "marquee-text",
		name: "MarqueeText",
		category: "Text Animations",
		description:
			"A marquee that scrolls only when its text overflows the container.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: ["Marquee", "Loop", "Linear"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-text/marquee-text.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-text/auto-mask-horizontal.tsx",
				role: "peer",
				label: "auto-mask-horizontal.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 35,
				min: 5,
				max: 120,
				step: 5,
				description: "Scroll speed (px/s).",
			},
			{
				name: "gap",
				kind: "number",
				default: 40,
				min: 0,
				max: 120,
				step: 4,
				unit: "px",
				description: "Gap between repetitions.",
			},
			{
				name: "pause",
				kind: "number",
				default: 5,
				min: 0,
				max: 15,
				step: 0.5,
				unit: "s",
				description: "Pause at the start before scrolling.",
			},
		],
	},
	{
		slug: "variable-proximity",
		attribution: REACTBITS,
		name: "VariableProximity",
		category: "Text Animations",
		pausable: true,
		description:
			"Text whose letters interpolate font weight by cursor proximity.",
		dependencies: ["motion"],
		cookbook: ["Hover effect", "Interpolation / Tween"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/variable-proximity/variable-proximity.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
			},
		],
		props: [
			{
				name: "radius",
				kind: "number",
				default: 80,
				min: 20,
				max: 200,
				step: 5,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "falloff",
				kind: "enum",
				default: "linear",
				options: ["linear", "exponential", "gaussian"],
				description: "How influence falls off with distance.",
			},
		],
	},
	{
		slug: "letters-pull",
		name: "LettersPull",
		category: "Text Animations",
		description:
			"A per-letter pull-up reveal — letters rise, sharpen from a blur, and fade in with a stagger.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Stagger",
			"Slide in",
			"Blur",
			"Fade in / Fade out",
			"Enter / Exit",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/letters-pull/letters-pull.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "duration",
				kind: "number",
				default: 0.5,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Per-letter animation duration.",
			},
			{
				name: "delay",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.2,
				step: 0.005,
				unit: "s",
				description: "Delay between successive letters.",
			},
			{
				name: "yValue",
				kind: "number",
				default: 10,
				min: 0,
				max: 60,
				step: 1,
				unit: "px",
				description: "Rise distance of each letter.",
			},
			{
				name: "blur",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Starting blur each letter sharpens from.",
			},
		],
	},
	{
		slug: "scramble-text",
		name: "ScrambleText",
		category: "Text Animations",
		description:
			"Ciphered glyphs boiling out of noise and resolving into words — a decode cascade that settles character by character, a hover that re-scrambles on demand, or a continuous low glitch that keeps the type restless, each freshly-resolved letter flashing accent before it cools to ink.",
		dependencies: [],
		cookbook: ["Text morph", "Stepped animation", "Hover effect", "Stagger"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/scramble-text/scramble-text.tsx",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "decode-on-mount",
				options: ["decode-on-mount", "scramble-on-hover", "continuous-glitch"],
				description:
					"Decode once on mount, re-scramble on hover, or glitch forever.",
			},
			{
				name: "charset",
				kind: "enum",
				default: "symbols",
				options: ["symbols", "alphanumeric", "katakana", "binary", "blocks"],
				description: "Pool of cipher glyphs shown before a character settles.",
			},
			{
				name: "duration",
				kind: "number",
				default: 900,
				min: 200,
				max: 3000,
				step: 50,
				unit: "ms",
				description: "Total time for the full decode cascade to resolve.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 40,
				min: 0,
				max: 100,
				step: 5,
				unit: "ms",
				description:
					"Per-character offset of the settle deadline across the string.",
			},
			{
				name: "speed",
				kind: "number",
				default: 45,
				min: 10,
				max: 120,
				step: 5,
				unit: "ms",
				description: "How often unsettled glyphs re-roll to new noise.",
			},
			{
				name: "glitchInterval",
				kind: "number",
				default: 3,
				min: 0.5,
				max: 8,
				step: 0.5,
				unit: "s",
				description:
					"Seconds between glitch bursts (continuous-glitch mode only).",
			},
			{
				name: "flashColor",
				kind: "color",
				default: "#a855f7",
				description: "Accent tint a character flashes as it resolves.",
			},
		],
	},
	{
		slug: "long-shadow",
		name: "LongShadow",
		category: "Text Animations",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Text that casts a long shadow sweeping like a sundial through the hours.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: ["Loop", "Idle animation", "Linear"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/long-shadow/long-shadow.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "shadowLength",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "Reach of the cast shadow (layer count).",
			},
			{
				name: "sweepSpeed",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "How fast the sun arcs; 0 holds a fixed shadow.",
			},
			{
				name: "angleStart",
				kind: "number",
				default: 20,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Sundial start angle.",
			},
			{
				name: "angleSweep",
				kind: "number",
				default: 140,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Total arc the sun sweeps.",
			},
			{
				name: "pingPong",
				kind: "boolean",
				default: true,
				description: "Arc back and forth (off = full rotation).",
			},
			{
				name: "fade",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the shadow dissolves along its length.",
			},
			{
				name: "skew",
				kind: "number",
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.05,
				description: "Italic lean of the cast shadow.",
			},
			{
				name: "shadowColor",
				kind: "color",
				default: "#2a1a3a",
				description: "Color of the long shadow.",
			},
		],
	},
	{
		slug: "specter",
		name: "Specter",
		category: "Text Animations",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Spectral RGB-split echoes drift off the letters and dissolve into the dark.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: ["Follow-through", "Blur", "Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/specter/specter.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "ghostCount",
				kind: "number",
				default: 3,
				min: 1,
				max: 8,
				step: 1,
				description: "Number of spectral echoes.",
			},
			{
				name: "drift",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "How far each ghost drifts before dissolving.",
			},
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Drift and dissolve cycle speed.",
			},
			{
				name: "angle",
				kind: "number",
				default: 90,
				min: 0,
				max: 360,
				step: 15,
				unit: "°",
				description: "Direction the ghosts drift toward.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				unit: "s",
				description: "Delay between successive emissions.",
			},
			{
				name: "blur",
				kind: "number",
				default: 2,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Ghost softness as it dissolves.",
			},
			{
				name: "splitColor1",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst chromatic ghost.",
			},
			{
				name: "splitColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Cyan chromatic ghost.",
			},
		],
	},
	{
		slug: "lumen",
		name: "Lumen",
		category: "Text Animations",
		addedAt: "2026-07-26",
		description:
			"Copy that lights up as you read it — words ahead sit dim and unfocused, and stay lit once you pass them.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Scroll-driven animation",
			"Scroll reveal",
			"Stagger",
			"Interpolation / Tween",
			"Blur",
			"Purposeful animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/lumen/lumen.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "dimOpacity",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				description: "Opacity of words that haven't been reached yet.",
			},
			{
				name: "fadeSpan",
				kind: "number",
				default: 6,
				min: 1,
				max: 20,
				step: 1,
				unit: "words",
				description:
					"Width of the reading band — words mid-transition at once.",
			},
			{
				name: "blurAmount",
				kind: "number",
				default: 4,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Blur on a word that hasn't been reached.",
			},
			{
				name: "startOffset",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.5,
				step: 0.05,
				description: "Point in the scroll pass where the first word brightens.",
			},
			{
				name: "endOffset",
				kind: "number",
				default: 0.6,
				min: 0.3,
				max: 1,
				step: 0.05,
				description: "Point by which the last word is fully lit.",
			},
			{
				name: "highlightColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst bloom on the leading edge.",
			},
		],
	},
	{
		slug: "redact",
		name: "Redact",
		category: "Text Animations",
		addedAt: "2026-07-31",
		description:
			"Copy that arrives fully classified under solid bars, then declassifies word by word — each bar clearing its own word and leaving an amethyst edge behind as the only evidence it was ever there.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Reveal",
			"Mask",
			"Clip-path",
			"Stagger",
			"Enter / Exit",
			"Ease-out",
			"Loop",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/redact/redact.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "wipe",
				options: ["wipe", "slide", "lift"],
				description:
					"How a bar leaves. Wipe retracts it into its own edge, slide throws it clear of the word, lift peels it off the page — wipe reads as redaction being undone, slide reads as tape being pulled.",
			},
			{
				name: "direction",
				kind: "enum",
				default: "ltr",
				options: ["ltr", "rtl", "center-out", "random"],
				description:
					"The order words declassify in. Random is the only one that reads as a machine working through a document rather than a person reading it.",
			},
			{
				name: "duration",
				kind: "number",
				default: 420,
				min: 120,
				max: 1500,
				step: 20,
				unit: "ms",
				description: "How long one bar takes to clear its own word.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 70,
				min: 0,
				max: 400,
				step: 10,
				unit: "ms",
				description:
					"Gap between one word starting to clear and the next. At 0 the whole block lifts at once and the espionage goes out of it.",
			},
			{
				name: "startDelay",
				kind: "number",
				default: 300,
				min: 0,
				max: 3000,
				step: 50,
				unit: "ms",
				description:
					"Dead air after the classified block lands before the first bar moves. The pause is what makes the reveal feel authorised.",
			},
			{
				name: "barPadding",
				kind: "number",
				default: 3,
				min: 0,
				max: 10,
				step: 0.5,
				unit: "px",
				description:
					"How far each bar overhangs its word. Drawn tight to the glyphs it reads as a highlighter; give it a couple of pixels and it reads as tape laid over the page.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: false,
				description:
					"Bring the bars back down and run the whole sweep again, forever, instead of settling on plain text.",
			},
			{
				name: "interval",
				kind: "number",
				default: 3.5,
				min: 1,
				max: 12,
				step: 0.5,
				unit: "s",
				disabledWhen: { prop: "loop", equals: false },
				description:
					"Seconds the plain text stays legible before the bars come back down.",
			},
			{
				name: "barColor",
				kind: "color",
				default: "#15101f",
				description:
					"Solid ink of the bars. Near-black on purpose — a censor bar that lets any of the word through is not a censor bar.",
			},
			{
				name: "edgeColor",
				kind: "color",
				default: "#a855f7",
				description:
					"Amethyst hairline riding the retreating edge of each bar. It is the only part of the effect the eye actually tracks.",
			},
		],
	},
	{
		slug: "split-flap",
		name: "SplitFlap",
		category: "Text Animations",
		addedAt: "2026-07-31",
		pausable: true,
		description:
			"A Solari departure board. Every column walks the charset one flap at a time until it reaches its letter, so the word is never revealed — it is arrived at, with a real hinged half falling away as the next one seats behind it.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Stepped animation",
			"Stagger",
			"3D tilt / Flip",
			"Perspective",
			"Loop",
			"Follow-through",
			"Tabular numbers",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/split-flap/split-flap.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "charset",
				kind: "enum",
				default: "alphanumeric",
				options: ["alphanumeric", "letters", "digits", "departures"],
				description:
					"Which glyphs a column walks through on its way to its letter. This is what sets the length of the journey — a digits-only board lands almost immediately, a full alphanumeric one takes its time.",
			},
			{
				name: "flapDuration",
				kind: "number",
				default: 90,
				min: 30,
				max: 300,
				step: 5,
				unit: "ms",
				description:
					"Time for one flap. Under about 50ms the column reads as a blur rather than as discrete cards, which throws away the whole point of the mechanism.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 45,
				min: 0,
				max: 300,
				step: 5,
				unit: "ms",
				description:
					"Delay between one column starting and the next. At 0 the board moves as one slab; a small offset is what makes it sound like a board even in silence.",
			},
			{
				name: "settleBounce",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"Overshoot as a flap hits its stop. This is follow-through: the card has mass, so it arrives slightly past and comes back.",
			},
			{
				name: "cardGap",
				kind: "number",
				default: 4,
				min: 0,
				max: 16,
				step: 1,
				unit: "px",
				description: "Space between one card stack and the next.",
			},
			{
				name: "seamWeight",
				kind: "number",
				default: 1,
				min: 0,
				max: 4,
				step: 0.5,
				unit: "px",
				description:
					"The hairline across the middle of a card, where the two halves meet. Kept in the DOM rather than drawn, so the browser snaps it to the pixel grid instead of letting it shimmer on fractional scaling.",
			},
			{
				name: "specular",
				kind: "number",
				default: 0.55,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Light sweeping across a moving flap, brightest edge-on. Without it a flip reads as a rectangle changing shape rather than as a surface turning.",
			},
			{
				name: "perspective",
				kind: "number",
				default: 420,
				min: 120,
				max: 1200,
				step: 20,
				unit: "px",
				description:
					"Depth of the foreshortening. Lower exaggerates the hinge and puts the viewer close to the board; higher flattens it toward a straight fold.",
			},
			{
				name: "cardColor",
				kind: "color",
				default: "#17141d",
				description:
					"Body of the cards. Its own material, not a themed surface — a departure board is a dark object in any room.",
			},
			{
				name: "glyphColor",
				kind: "color",
				default: "#e8e4ee",
				description: "The printed characters.",
			},
		],
	},
	{
		slug: "teletype",
		name: "Teletype",
		category: "Text Animations",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"A line of type arriving one character at a time, at a rate that varies and with a beat at every mark.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: ["Typewriter", "Stepped animation", "Loop", "Idle animation"],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/teletype/teletype.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "charsPerSecond",
				kind: "number",
				default: 22,
				min: 4,
				max: 90,
				step: 1,
				description:
					"Typing rate before jitter. Above roughly 40 the reader stops perceiving individual keystrokes and starts seeing a wipe.",
			},
			{
				name: "deleteRate",
				kind: "number",
				default: 2.4,
				min: 0,
				max: 6,
				step: 0.1,
				description:
					"Erase rate as a multiple of the typing rate — deleting is never as deliberate as writing. At 0 the line is not erased at all: it is cut, and the next one starts clean.",
			},
			{
				name: "hold",
				kind: "number",
				default: 1500,
				min: 0,
				max: 4000,
				step: 100,
				unit: "ms",
				description:
					"Dwell on a finished line before it is taken away. This is the only window the reader has to actually read it.",
			},
			{
				name: "gap",
				kind: "number",
				default: 420,
				min: 0,
				max: 2000,
				step: 20,
				unit: "ms",
				description:
					"Empty beat between one line clearing and the next starting.",
			},
			{
				name: "jitter",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Spread on the per-line rate. At 0 the machine is a metronome, which reads as a progress bar rendered in letters rather than as typing.",
			},
			{
				name: "punctuationPause",
				kind: "number",
				default: 220,
				min: 0,
				max: 800,
				step: 20,
				unit: "ms",
				description:
					"Extra beat after a comma, period, dash or colon. The pause a reader hears at a mark is the silence that follows it, so it lands after the glyph, never before.",
			},
			{
				name: "caret",
				kind: "enum",
				default: "block",
				options: ["block", "bar", "underscore", "none"],
				description: "Shape of the cursor trailing the text.",
			},
			{
				name: "caretBlink",
				kind: "number",
				default: 1.05,
				min: 0.2,
				max: 3,
				step: 0.05,
				unit: "s",
				disabledWhen: { prop: "caret", equals: "none" },
				description:
					"Seconds per blink cycle. The caret holds steady while characters are arriving and only blinks once the line is at rest — a terminal does the same, and the contrast is what makes the typing read as live.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: true,
				description: "Wrap to the first line when the list runs out.",
			},
			{
				name: "reserveSpace",
				kind: "boolean",
				default: true,
				description:
					"Hold the box at the size of the longest line. Turn it off to watch everything below the type walk up and down the page — which is the reason it is on.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "The caret.",
			},
		],
	},
	{
		slug: "reflow",
		name: "Reflow",
		category: "Text Animations",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"Text whose words keep their identity when the line breaks move — narrow the measure and the sentence travels instead of re-wrapping.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Layout animation",
			"Continuity transition",
			"Spatial consistency",
			"Enter / Exit",
			"Stagger",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/reflow/reflow.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "columnWidth",
				kind: "number",
				default: 100,
				min: 30,
				max: 100,
				step: 1,
				unit: "%",
				description:
					"Width of the text column as a percentage of its container — the measure. Dragging this is the reflow, with not one word changing.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 340,
				min: 40,
				max: 900,
				step: 10,
				description: "Spring tension on the travel.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 6,
				max: 80,
				step: 1,
				description: "Spring friction on the travel.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 14,
				min: 0,
				max: 120,
				step: 2,
				unit: "ms",
				description:
					"Delay between one word starting its travel and the next. The index is capped at twenty, so a long paragraph cannot leave its tail sitting still in plain sight.",
			},
			{
				name: "enterScale",
				kind: "number",
				default: 0.82,
				min: 0.2,
				max: 1,
				step: 0.02,
				description: "Size a word enters at and leaves at.",
			},
			{
				name: "wordGap",
				kind: "number",
				default: 0.3,
				min: 0.1,
				max: 0.9,
				step: 0.02,
				unit: "em",
				description:
					"Space between words. A margin rather than a space character, so a word leaving the sentence does not strand the gap that followed it.",
			},
			{
				name: "lineHeight",
				kind: "number",
				default: 1.6,
				min: 1,
				max: 2.6,
				step: 0.05,
				description: "Leading.",
			},
			{
				name: "align",
				kind: "enum",
				default: "left",
				options: ["left", "center", "right"],
				description: "Text alignment.",
			},
			{
				name: "auto",
				kind: "boolean",
				default: true,
				description: "Advance through the phrases on a timer.",
			},
			{
				name: "interval",
				kind: "number",
				default: 3600,
				min: 800,
				max: 9000,
				step: 200,
				unit: "ms",
				disabledWhen: { prop: "auto", equals: false },
				description: "Time on each phrase.",
			},
			{
				name: "traceMoves",
				kind: "boolean",
				default: false,
				description:
					"Tint a word for as long as it is travelling. A debugging affordance that earned its place — it is the only way to prove a word moved rather than being destroyed and re-created somewhere else.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				disabledWhen: { prop: "traceMoves", equals: false },
				description: "The trace tint.",
			},
		],
	},
	{
		slug: "metallic-text",
		name: "MetallicText",
		category: "Text Animations",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"Chrome poured into a headline — a metal ramp clipped to real glyphs, a specular travelling across them, and a tinted wake following a beat behind.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Mask",
			"Compositing",
			"Follow-through",
			"Idle animation",
			"Loop",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/metallic-text/metallic-text.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "sweepSpeed",
				kind: "number",
				default: 3.2,
				min: 0.5,
				max: 12,
				step: 0.1,
				unit: "s",
				description: "Time for the highlight to cross the line once.",
			},
			{
				name: "sweepWidth",
				kind: "number",
				default: 0.28,
				min: 0.05,
				max: 1,
				step: 0.01,
				description:
					"Width of the specular band as a share of the text box. Narrow reads as polished chrome, wide as brushed steel — the band is the light source, so its size is the softness of the reflection.",
			},
			{
				name: "sweepAngle",
				kind: "number",
				default: 18,
				min: -60,
				max: 60,
				step: 1,
				unit: "°",
				description:
					"Rake of the band off vertical. Stops short of ±90 on purpose: at a right angle the band lies parallel to its own travel and the sweep stops reading as movement at all.",
			},
			{
				name: "contrast",
				kind: "number",
				default: 0.7,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"Separation between the dark and light bands of the metal. This is what decides whether the text reads as chrome or as a grey gradient — the horizon between the two is the reflection of a ground plane.",
			},
			{
				name: "specular",
				kind: "number",
				default: 0.85,
				min: 0,
				max: 1.5,
				step: 0.05,
				description: "Brightness of the travelling highlight.",
			},
			{
				name: "lag",
				kind: "number",
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.01,
				description:
					"How far the wake trails the highlight. At zero the two move as one gradient; raise it and the light gains weight, because the trailing edge is still arriving when the leading edge has gone.",
			},
			{
				name: "sweep",
				kind: "enum",
				default: "alternate",
				options: ["alternate", "loop"],
				description:
					"Whether the light returns the way it came or restarts from the same edge each pass.",
			},
			{
				name: "grain",
				kind: "number",
				default: 0.12,
				min: 0,
				max: 0.5,
				step: 0.01,
				description:
					"Brushed striations along the sweep axis. Directional rather than random — milled metal has a grain direction, and noise reads as dirt on the screen instead.",
			},
			{
				name: "baseColor",
				kind: "color",
				default: "#8f94a3",
				description:
					"The metal. Also the fallback colour: where background-clip on text is unsupported the element renders as plain text in this colour rather than as an invisible headline.",
			},
			{
				name: "highlightColor",
				kind: "color",
				default: "#ffffff",
				description: "The specular.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "Tint of the wake.",
			},
		],
	},
];
