import type { ComponentEntry } from "../types";

/** Text Animations — kinetic type and number transitions. */
export const textAnimations: ComponentEntry[] = [
	{
		slug: "morphing-text",
		name: "MorphingText",
		category: "Text Animations",
		tier: "free",
		description:
			"A gooey blur-morph that cross-dissolves between a list of words.",
		dependencies: [],
		philosophy: [
			"Text morph",
			"Morph",
			"Crossfade",
			"Blur",
			"Loop",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/morphing-text/MorphingText.tsx",
			},
		],
		props: [
			{
				name: "auto",
				kind: "boolean",
				default: true,
				description: "Loop through the words forever (off = morph once).",
			},
		],
	},
	{
		slug: "animated-number",
		name: "AnimatedNumber",
		category: "Text Animations",
		tier: "free",
		description:
			"Animated numeric transitions with flip, slide, fade, and bounce styles.",
		dependencies: ["motion"],
		philosophy: [
			"Number ticker",
			"Tabular numbers",
			"Bounce",
			"Slide in",
			"Fade in / Fade out",
			"3D tilt / Flip",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/animated-number/AnimatedNumber.tsx",
			},
		],
		props: [
			{
				name: "value",
				kind: "number",
				default: 999,
				min: 0,
				max: 9999,
				step: 1,
				description: "The value to display and animate to.",
			},
			{
				name: "animationType",
				kind: "enum",
				default: "flip",
				options: ["flip", "slide", "fade", "scale-bounce"],
				description: "Transition style between values.",
			},
			{
				name: "duration",
				kind: "number",
				default: 0.4,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Transition duration.",
			},
			{
				name: "staggerDelay",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.3,
				step: 0.01,
				unit: "s",
				description: "Delay between each digit's animation.",
			},
		],
	},
	{
		slug: "marquee-text",
		name: "MarqueeText",
		category: "Text Animations",
		tier: "free",
		description:
			"A marquee that scrolls only when its text overflows the container.",
		dependencies: [],
		philosophy: [
			"Marquee",
			"Loop",
			"Linear",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-text/MarqueeText.tsx",
			},
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 35,
				min: 5,
				max: 120,
				step: 5,
				description: "Scroll speed (px/s).",
			},
			{
				name: "gap",
				kind: "number",
				default: 40,
				min: 0,
				max: 120,
				step: 4,
				unit: "px",
				description: "Gap between repetitions.",
			},
			{
				name: "pause",
				kind: "number",
				default: 5,
				min: 0,
				max: 15,
				step: 0.5,
				unit: "s",
				description: "Pause at the start before scrolling.",
			},
		],
	},
	{
		slug: "variable-proximity",
		name: "VariableProximity",
		category: "Text Animations",
		tier: "pro",
		pausable: true,
		description:
			"Text whose letters interpolate font weight by cursor proximity.",
		dependencies: ["motion"],
		philosophy: [
			"Hover effect",
			"Interpolation / Tween",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/variable-proximity/VariableProximity.tsx",
			},
		],
		props: [
			{
				name: "radius",
				kind: "number",
				default: 80,
				min: 20,
				max: 200,
				step: 5,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "falloff",
				kind: "enum",
				default: "linear",
				options: ["linear", "exponential", "gaussian"],
				description: "How influence falls off with distance.",
			},
		],
	},
	{
		slug: "scroll-velocity",
		name: "ScrollVelocity",
		category: "Text Animations",
		tier: "free",
		description:
			"A wrapping marquee whose drift speed and direction follow scroll velocity — fast scrolls whip the row along, upward scrolls reverse it.",
		dependencies: ["motion"],
		philosophy: [
			"Marquee",
			"Scroll-driven animation",
			"Velocity",
			"Spring",
			"Momentum",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/scroll-velocity/ScrollVelocity.tsx",
			},
		],
		props: [
			{
				name: "velocity",
				kind: "number",
				default: 50,
				min: -200,
				max: 200,
				step: 10,
				unit: "px/s",
				description: "Base drift speed; negative drifts the other way.",
			},
			{
				name: "damping",
				kind: "number",
				default: 50,
				min: 10,
				max: 100,
				step: 5,
				description: "Spring damping on the scroll-velocity smoothing.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 400,
				min: 100,
				max: 800,
				step: 20,
				description: "Spring stiffness on the scroll-velocity smoothing.",
			},
			{
				name: "numCopies",
				label: "Copies",
				kind: "number",
				default: 6,
				min: 2,
				max: 12,
				step: 1,
				description: "How many copies of the content tile the loop.",
			},
		],
	},
	{
		slug: "letters-pull",
		name: "LettersPull",
		category: "Text Animations",
		tier: "free",
		description:
			"A per-letter pull-up reveal — letters rise, sharpen from a blur, and fade in with a stagger.",
		dependencies: ["motion"],
		philosophy: [
			"Stagger",
			"Slide in",
			"Blur",
			"Fade in / Fade out",
			"Enter / Exit",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/letters-pull/LettersPull.tsx",
			},
		],
		props: [
			{
				name: "duration",
				kind: "number",
				default: 0.5,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Per-letter animation duration.",
			},
			{
				name: "delay",
				label: "Stagger",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.2,
				step: 0.005,
				unit: "s",
				description: "Delay between successive letters.",
			},
			{
				name: "yValue",
				label: "Y offset",
				kind: "number",
				default: 10,
				min: 0,
				max: 60,
				step: 1,
				unit: "px",
				description: "Rise distance of each letter.",
			},
			{
				name: "blur",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Starting blur each letter sharpens from.",
			},
		],
	},
	{
		slug: "word-reveal",
		name: "WordReveal",
		category: "Text Animations",
		tier: "free",
		description:
			"A scroll-scrubbed word reveal — each word brightens and rises as it enters the viewport, tied directly to scroll position.",
		dependencies: ["gsap"],
		philosophy: [
			"Scroll reveal",
			"Scroll-driven animation",
			"Stagger",
			"Reveal",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/word-reveal/WordReveal.tsx",
			},
		],
		props: [
			{
				name: "stagger",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.2,
				step: 0.005,
				unit: "s",
				description: "Offset between successive words along the scrub.",
			},
			{
				name: "yOffset",
				label: "Y offset",
				kind: "number",
				default: 30,
				min: 0,
				max: 80,
				step: 2,
				unit: "px",
				description: "Rise distance per word.",
			},
			{
				name: "fromOpacity",
				label: "Dim opacity",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 0.6,
				step: 0.05,
				description: "Resting opacity of unrevealed words.",
			},
			{
				name: "scrub",
				kind: "number",
				default: 1,
				min: 0.1,
				max: 3,
				step: 0.1,
				unit: "s",
				description: "Smoothing lag between scroll and reveal.",
			},
			{
				name: "ease",
				kind: "enum",
				default: "power2.out",
				options: ["power1.out", "power2.out", "power3.out", "none"],
				description: "Reveal easing along the scrub.",
			},
		],
	},
	{
		slug: "scramble-text",
		name: "ScrambleText",
		category: "Text Animations",
		tier: "free",
		description:
			"Ciphered glyphs boiling out of noise and resolving into words — a decode cascade that settles character by character, a hover that re-scrambles on demand, or a continuous low glitch that keeps the type restless, each freshly-resolved letter flashing accent before it cools to ink.",
		dependencies: [],
		philosophy: [
			"Text morph",
			"Stepped animation",
			"Hover effect",
			"Stagger",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/scramble-text/ScrambleText.tsx",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "decode-on-mount",
				options: ["decode-on-mount", "scramble-on-hover", "continuous-glitch"],
				description: "Decode once on mount, re-scramble on hover, or glitch forever.",
			},
			{
				name: "charset",
				kind: "enum",
				default: "symbols",
				options: ["symbols", "alphanumeric", "katakana", "binary", "blocks"],
				description: "Pool of cipher glyphs shown before a character settles.",
			},
			{
				name: "duration",
				kind: "number",
				default: 900,
				min: 200,
				max: 3000,
				step: 50,
				unit: "ms",
				description: "Total time for the full decode cascade to resolve.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 40,
				min: 0,
				max: 100,
				step: 5,
				unit: "ms",
				description: "Per-character offset of the settle deadline across the string.",
			},
			{
				name: "speed",
				label: "Reroll rate",
				kind: "number",
				default: 45,
				min: 10,
				max: 120,
				step: 5,
				unit: "ms",
				description: "How often unsettled glyphs re-roll to new noise.",
			},
			{
				name: "glitchInterval",
				label: "Glitch interval",
				kind: "number",
				default: 3,
				min: 0.5,
				max: 8,
				step: 0.5,
				unit: "s",
				description: "Seconds between glitch bursts (continuous-glitch mode only).",
			},
			{
				name: "flashColor",
				label: "Flash",
				kind: "color",
				default: "#a855f7",
				description: "Accent tint a character flashes as it resolves.",
			},
		],
	},
	{
		slug: "long-shadow",
		name: "LongShadow",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Text that casts a long shadow sweeping like a sundial through the hours.",
		dependencies: ["motion"],
		philosophy: [
			"Loop",
			"Idle animation",
			"Linear",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/long-shadow/LongShadow.tsx",
			},
		],
		props: [
			{
				name: "shadowLength",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "Reach of the cast shadow (layer count).",
			},
			{
				name: "sweepSpeed",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "How fast the sun arcs; 0 holds a fixed shadow.",
			},
			{
				name: "angleStart",
				kind: "number",
				default: 20,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Sundial start angle.",
			},
			{
				name: "angleSweep",
				kind: "number",
				default: 140,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Total arc the sun sweeps.",
			},
			{
				name: "pingPong",
				kind: "boolean",
				default: true,
				description: "Arc back and forth (off = full rotation).",
			},
			{
				name: "fade",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the shadow dissolves along its length.",
			},
			{
				name: "skew",
				kind: "number",
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.05,
				description: "Italic lean of the cast shadow.",
			},
			{
				name: "shadowColor",
				kind: "color",
				default: "#2a1a3a",
				description: "Color of the long shadow.",
			},
		],
	},
	{
		slug: "specter",
		name: "Specter",
		category: "Text Animations",
		tier: "pro",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Spectral RGB-split echoes drift off the letters and dissolve into the dark.",
		dependencies: ["motion"],
		philosophy: [
			"Follow-through",
			"Blur",
			"Loop",
			"Idle animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/specter/Specter.tsx",
			},
		],
		props: [
			{
				name: "ghostCount",
				kind: "number",
				default: 3,
				min: 1,
				max: 8,
				step: 1,
				description: "Number of spectral echoes.",
			},
			{
				name: "drift",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "How far each ghost drifts before dissolving.",
			},
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Drift and dissolve cycle speed.",
			},
			{
				name: "angle",
				kind: "number",
				default: 90,
				min: 0,
				max: 360,
				step: 15,
				unit: "°",
				description: "Direction the ghosts drift toward.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				unit: "s",
				description: "Delay between successive emissions.",
			},
			{
				name: "blur",
				kind: "number",
				default: 2,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Ghost softness as it dissolves.",
			},
			{
				name: "splitColor1",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst chromatic ghost.",
			},
			{
				name: "splitColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Cyan chromatic ghost.",
			},
		],
	},
	{
		slug: "lumen",
		name: "Lumen",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-07-26",
		description:
			"Copy that lights up as you read it — words ahead sit dim and unfocused, and stay lit once you pass them.",
		dependencies: ["motion"],
		philosophy: [
			"Scroll-driven animation",
			"Scroll reveal",
			"Stagger",
			"Interpolation / Tween",
			"Blur",
			"Purposeful animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/lumen/Lumen.tsx",
			},
		],
		props: [
			{
				name: "dimOpacity",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				description: "Opacity of words that haven't been reached yet.",
			},
			{
				name: "fadeSpan",
				kind: "number",
				default: 6,
				min: 1,
				max: 20,
				step: 1,
				unit: "words",
				description: "Width of the reading band — words mid-transition at once.",
			},
			{
				name: "blurAmount",
				kind: "number",
				default: 4,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Blur on a word that hasn't been reached.",
			},
			{
				name: "startOffset",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.5,
				step: 0.05,
				description: "Point in the scroll pass where the first word brightens.",
			},
			{
				name: "endOffset",
				kind: "number",
				default: 0.6,
				min: 0.3,
				max: 1,
				step: 0.05,
				description: "Point by which the last word is fully lit.",
			},
			{
				name: "highlightColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst bloom on the leading edge.",
			},
		],
	},
];
