import type { ComponentEntry, Variant } from "../types";

/** lib/utils.ts ships with every entry whose source imports `cn`. Its own
 *  packages (clsx, tailwind-merge) are the host entry's to declare — the check
 *  walks into this file and finds them there (§V41). */
const UTILS_VARIANT: Variant = {
	lang: "ts",
	style: "tailwind",
	file: "lib/utils.ts",
	role: "util",
	label: "utils.ts",
};

/** Text Animations — kinetic type and number transitions. */
export const textAnimations: ComponentEntry[] = [
	{
		slug: "morphing-text",
		name: "MorphingText",
		category: "Text Animations",
		tier: "free",
		description:
			"A gooey blur-morph that cross-dissolves between a list of words.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Text morph",
			"Morph",
			"Crossfade",
			"Blur",
			"Loop",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/morphing-text/MorphingText.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "auto",
				kind: "boolean",
				default: true,
				description: "Loop through the words forever (off = morph once).",
			},
		],
	},
	{
		slug: "animated-number",
		name: "AnimatedNumber",
		category: "Text Animations",
		tier: "free",
		description:
			"Animated numeric transitions with flip, slide, fade, and bounce styles.",
		dependencies: ["motion"],
		cookbook: [
			"Number ticker",
			"Tabular numbers",
			"Bounce",
			"Slide in",
			"Fade in / Fade out",
			"3D tilt / Flip",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/animated-number/AnimatedNumber.tsx",
			},
		],
		props: [
			{
				name: "value",
				kind: "number",
				default: 999,
				min: 0,
				max: 9999,
				step: 1,
				description: "The value to display and animate to.",
			},
			{
				name: "animationType",
				kind: "enum",
				default: "flip",
				options: ["flip", "slide", "fade", "scale-bounce"],
				description: "Transition style between values.",
			},
			{
				name: "duration",
				kind: "number",
				default: 0.4,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Transition duration.",
			},
			{
				name: "staggerDelay",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.3,
				step: 0.01,
				unit: "s",
				description: "Delay between each digit's animation.",
			},
		],
	},
	{
		slug: "marquee-text",
		name: "MarqueeText",
		category: "Text Animations",
		tier: "free",
		description:
			"A marquee that scrolls only when its text overflows the container.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Marquee",
			"Loop",
			"Linear",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-text/MarqueeText.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-text/auto-mask-horizontal.tsx",
				role: "peer",
				label: "auto-mask-horizontal.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "speed",
				kind: "number",
				default: 35,
				min: 5,
				max: 120,
				step: 5,
				description: "Scroll speed (px/s).",
			},
			{
				name: "gap",
				kind: "number",
				default: 40,
				min: 0,
				max: 120,
				step: 4,
				unit: "px",
				description: "Gap between repetitions.",
			},
			{
				name: "pause",
				kind: "number",
				default: 5,
				min: 0,
				max: 15,
				step: 0.5,
				unit: "s",
				description: "Pause at the start before scrolling.",
			},
		],
	},
	{
		slug: "variable-proximity",
		name: "VariableProximity",
		category: "Text Animations",
		tier: "pro",
		pausable: true,
		description:
			"Text whose letters interpolate font weight by cursor proximity.",
		dependencies: ["motion"],
		cookbook: [
			"Hover effect",
			"Interpolation / Tween",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/variable-proximity/VariableProximity.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
			},
		],
		props: [
			{
				name: "radius",
				kind: "number",
				default: 80,
				min: 20,
				max: 200,
				step: 5,
				unit: "px",
				description: "Cursor influence radius.",
			},
			{
				name: "falloff",
				kind: "enum",
				default: "linear",
				options: ["linear", "exponential", "gaussian"],
				description: "How influence falls off with distance.",
			},
		],
	},
	{
		slug: "marquee-velocity",
		name: "MarqueeVelocity",
		category: "Text Animations",
		tier: "free",
		description:
			"A wrapping marquee whose drift speed and direction follow scroll velocity — fast scrolls whip the row along, upward scrolls reverse it.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Marquee",
			"Scroll-driven animation",
			"Velocity",
			"Spring",
			"Momentum",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/marquee-velocity/MarqueeVelocity.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "velocity",
				kind: "number",
				default: 50,
				min: -200,
				max: 200,
				step: 10,
				unit: "px/s",
				description:
					"Resting drift before scroll multiplies it. Positive moves the row right, negative moves it left, 0 leaves it still until you scroll.",
			},
			{
				name: "damping",
				kind: "number",
				default: 50,
				min: 10,
				max: 100,
				step: 5,
				description:
					"Friction on the velocity spring. Low overshoots and rebounds once the scroll stops; high settles dead.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 400,
				min: 100,
				max: 800,
				step: 20,
				description:
					"How hard the spring chases the current scroll speed. High tracks it instantly; low lags and keeps coasting, which reads as weight.",
			},
			{
				name: "numCopies",
				kind: "number",
				default: 6,
				min: 2,
				max: 12,
				step: 1,
				description:
					"Minimum copies tiled into the loop. A floor, not a count — narrow content gets more so the wrap never sweeps a gap through.",
			},
		],
	},
	{
		slug: "letters-pull",
		name: "LettersPull",
		category: "Text Animations",
		tier: "free",
		description:
			"A per-letter pull-up reveal — letters rise, sharpen from a blur, and fade in with a stagger.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Stagger",
			"Slide in",
			"Blur",
			"Fade in / Fade out",
			"Enter / Exit",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/letters-pull/LettersPull.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "duration",
				kind: "number",
				default: 0.5,
				min: 0.1,
				max: 2,
				step: 0.05,
				unit: "s",
				description: "Per-letter animation duration.",
			},
			{
				name: "delay",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.2,
				step: 0.005,
				unit: "s",
				description: "Delay between successive letters.",
			},
			{
				name: "yValue",
				kind: "number",
				default: 10,
				min: 0,
				max: 60,
				step: 1,
				unit: "px",
				description: "Rise distance of each letter.",
			},
			{
				name: "blur",
				kind: "number",
				default: 8,
				min: 0,
				max: 20,
				step: 1,
				unit: "px",
				description: "Starting blur each letter sharpens from.",
			},
		],
	},
	{
		slug: "word-reveal",
		name: "WordReveal",
		category: "Text Animations",
		tier: "free",
		description:
			"A scroll-scrubbed word reveal — each word brightens and rises as it enters the viewport, tied directly to scroll position.",
		dependencies: ["gsap"],
		cookbook: [
			"Scroll reveal",
			"Scroll-driven animation",
			"Stagger",
			"Reveal",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/word-reveal/WordReveal.tsx",
			},
		],
		props: [
			{
				name: "stagger",
				kind: "number",
				default: 0.05,
				min: 0,
				max: 0.2,
				step: 0.005,
				unit: "s",
				description: "Offset between successive words along the scrub.",
			},
			{
				name: "yOffset",
				kind: "number",
				default: 30,
				min: 0,
				max: 80,
				step: 2,
				unit: "px",
				description: "Rise distance per word.",
			},
			{
				name: "fromOpacity",
				kind: "number",
				default: 0.1,
				min: 0,
				max: 0.6,
				step: 0.05,
				description: "Resting opacity of unrevealed words.",
			},
			{
				name: "scrub",
				kind: "number",
				default: 1,
				min: 0.1,
				max: 3,
				step: 0.1,
				unit: "s",
				description: "Smoothing lag between scroll and reveal.",
			},
			{
				name: "ease",
				kind: "enum",
				default: "power2.out",
				options: ["power1.out", "power2.out", "power3.out", "none"],
				description: "Reveal easing along the scrub.",
			},
		],
	},
	{
		slug: "scramble-text",
		name: "ScrambleText",
		category: "Text Animations",
		tier: "free",
		description:
			"Ciphered glyphs boiling out of noise and resolving into words — a decode cascade that settles character by character, a hover that re-scrambles on demand, or a continuous low glitch that keeps the type restless, each freshly-resolved letter flashing accent before it cools to ink.",
		dependencies: [],
		cookbook: [
			"Text morph",
			"Stepped animation",
			"Hover effect",
			"Stagger",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/scramble-text/ScrambleText.tsx",
			},
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "decode-on-mount",
				options: ["decode-on-mount", "scramble-on-hover", "continuous-glitch"],
				description: "Decode once on mount, re-scramble on hover, or glitch forever.",
			},
			{
				name: "charset",
				kind: "enum",
				default: "symbols",
				options: ["symbols", "alphanumeric", "katakana", "binary", "blocks"],
				description: "Pool of cipher glyphs shown before a character settles.",
			},
			{
				name: "duration",
				kind: "number",
				default: 900,
				min: 200,
				max: 3000,
				step: 50,
				unit: "ms",
				description: "Total time for the full decode cascade to resolve.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 40,
				min: 0,
				max: 100,
				step: 5,
				unit: "ms",
				description: "Per-character offset of the settle deadline across the string.",
			},
			{
				name: "speed",
				kind: "number",
				default: 45,
				min: 10,
				max: 120,
				step: 5,
				unit: "ms",
				description: "How often unsettled glyphs re-roll to new noise.",
			},
			{
				name: "glitchInterval",
				kind: "number",
				default: 3,
				min: 0.5,
				max: 8,
				step: 0.5,
				unit: "s",
				description: "Seconds between glitch bursts (continuous-glitch mode only).",
			},
			{
				name: "flashColor",
				kind: "color",
				default: "#a855f7",
				description: "Accent tint a character flashes as it resolves.",
			},
		],
	},
	{
		slug: "long-shadow",
		name: "LongShadow",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Text that casts a long shadow sweeping like a sundial through the hours.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Loop",
			"Idle animation",
			"Linear",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/long-shadow/LongShadow.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "shadowLength",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "Reach of the cast shadow (layer count).",
			},
			{
				name: "sweepSpeed",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "How fast the sun arcs; 0 holds a fixed shadow.",
			},
			{
				name: "angleStart",
				kind: "number",
				default: 20,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Sundial start angle.",
			},
			{
				name: "angleSweep",
				kind: "number",
				default: 140,
				min: 0,
				max: 360,
				step: 5,
				unit: "°",
				description: "Total arc the sun sweeps.",
			},
			{
				name: "pingPong",
				kind: "boolean",
				default: true,
				description: "Arc back and forth (off = full rotation).",
			},
			{
				name: "fade",
				kind: "number",
				default: 0.6,
				min: 0,
				max: 1,
				step: 0.05,
				description: "How much the shadow dissolves along its length.",
			},
			{
				name: "skew",
				kind: "number",
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.05,
				description: "Italic lean of the cast shadow.",
			},
			{
				name: "shadowColor",
				kind: "color",
				default: "#2a1a3a",
				description: "Color of the long shadow.",
			},
		],
	},
	{
		slug: "specter",
		name: "Specter",
		category: "Text Animations",
		tier: "pro",
		addedAt: "2026-07-24",
		pausable: true,
		description:
			"Spectral RGB-split echoes drift off the letters and dissolve into the dark.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Follow-through",
			"Blur",
			"Loop",
			"Idle animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/specter/Specter.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "ghostCount",
				kind: "number",
				default: 3,
				min: 1,
				max: 8,
				step: 1,
				description: "Number of spectral echoes.",
			},
			{
				name: "drift",
				kind: "number",
				default: 24,
				min: 4,
				max: 80,
				step: 2,
				unit: "px",
				description: "How far each ghost drifts before dissolving.",
			},
			{
				name: "speed",
				kind: "number",
				default: 1,
				min: 0,
				max: 3,
				step: 0.05,
				unit: "×",
				description: "Drift and dissolve cycle speed.",
			},
			{
				name: "angle",
				kind: "number",
				default: 90,
				min: 0,
				max: 360,
				step: 15,
				unit: "°",
				description: "Direction the ghosts drift toward.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				unit: "s",
				description: "Delay between successive emissions.",
			},
			{
				name: "blur",
				kind: "number",
				default: 2,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Ghost softness as it dissolves.",
			},
			{
				name: "splitColor1",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst chromatic ghost.",
			},
			{
				name: "splitColor2",
				kind: "color",
				default: "#22d3ee",
				description: "Cyan chromatic ghost.",
			},
		],
	},
	{
		slug: "lumen",
		name: "Lumen",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-07-26",
		description:
			"Copy that lights up as you read it — words ahead sit dim and unfocused, and stay lit once you pass them.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Scroll-driven animation",
			"Scroll reveal",
			"Stagger",
			"Interpolation / Tween",
			"Blur",
			"Purposeful animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/lumen/Lumen.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "dimOpacity",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.6,
				step: 0.05,
				description: "Opacity of words that haven't been reached yet.",
			},
			{
				name: "fadeSpan",
				kind: "number",
				default: 6,
				min: 1,
				max: 20,
				step: 1,
				unit: "words",
				description: "Width of the reading band — words mid-transition at once.",
			},
			{
				name: "blurAmount",
				kind: "number",
				default: 4,
				min: 0,
				max: 12,
				step: 0.5,
				unit: "px",
				description: "Blur on a word that hasn't been reached.",
			},
			{
				name: "startOffset",
				kind: "number",
				default: 0.15,
				min: 0,
				max: 0.5,
				step: 0.05,
				description: "Point in the scroll pass where the first word brightens.",
			},
			{
				name: "endOffset",
				kind: "number",
				default: 0.6,
				min: 0.3,
				max: 1,
				step: 0.05,
				description: "Point by which the last word is fully lit.",
			},
			{
				name: "highlightColor",
				kind: "color",
				default: "#a855f7",
				description: "Amethyst bloom on the leading edge.",
			},
		],
	},
	{
		slug: "redact",
		name: "Redact",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-07-31",
		description:
			"Copy that arrives fully classified under solid bars, then declassifies word by word — each bar clearing its own word and leaving an amethyst edge behind as the only evidence it was ever there.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Reveal",
			"Mask",
			"Clip-path",
			"Stagger",
			"Enter / Exit",
			"Ease-out",
			"Loop",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/redact/Redact.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "mode",
				kind: "enum",
				default: "wipe",
				options: ["wipe", "slide", "lift"],
				description:
					"How a bar leaves. Wipe retracts it into its own edge, slide throws it clear of the word, lift peels it off the page — wipe reads as redaction being undone, slide reads as tape being pulled.",
			},
			{
				name: "direction",
				kind: "enum",
				default: "ltr",
				options: ["ltr", "rtl", "center-out", "random"],
				description:
					"The order words declassify in. Random is the only one that reads as a machine working through a document rather than a person reading it.",
			},
			{
				name: "duration",
				kind: "number",
				default: 420,
				min: 120,
				max: 1500,
				step: 20,
				unit: "ms",
				description: "How long one bar takes to clear its own word.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 70,
				min: 0,
				max: 400,
				step: 10,
				unit: "ms",
				description:
					"Gap between one word starting to clear and the next. At 0 the whole block lifts at once and the espionage goes out of it.",
			},
			{
				name: "startDelay",
				kind: "number",
				default: 300,
				min: 0,
				max: 3000,
				step: 50,
				unit: "ms",
				description:
					"Dead air after the classified block lands before the first bar moves. The pause is what makes the reveal feel authorised.",
			},
			{
				name: "barPadding",
				kind: "number",
				default: 3,
				min: 0,
				max: 10,
				step: 0.5,
				unit: "px",
				description:
					"How far each bar overhangs its word. Drawn tight to the glyphs it reads as a highlighter; give it a couple of pixels and it reads as tape laid over the page.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: false,
				description:
					"Bring the bars back down and run the whole sweep again, forever, instead of settling on plain text.",
			},
			{
				name: "interval",
				kind: "number",
				default: 3.5,
				min: 1,
				max: 12,
				step: 0.5,
				unit: "s",
				disabledWhen: { prop: "loop", equals: false },
				description:
					"Seconds the plain text stays legible before the bars come back down.",
			},
			{
				name: "barColor",
				kind: "color",
				default: "#15101f",
				description:
					"Solid ink of the bars. Near-black on purpose — a censor bar that lets any of the word through is not a censor bar.",
			},
			{
				name: "edgeColor",
				kind: "color",
				default: "#a855f7",
				description:
					"Amethyst hairline riding the retreating edge of each bar. It is the only part of the effect the eye actually tracks.",
			},
		],
	},
	{
		slug: "split-flap",
		name: "SplitFlap",
		category: "Text Animations",
		tier: "pro",
		addedAt: "2026-07-31",
		pausable: true,
		description:
			"A Solari departure board. Every column walks the charset one flap at a time until it reaches its letter, so the word is never revealed — it is arrived at, with a real hinged half falling away as the next one seats behind it.",
		dependencies: ["clsx", "tailwind-merge"],
		cookbook: [
			"Stepped animation",
			"Stagger",
			"3D tilt / Flip",
			"Perspective",
			"Loop",
			"Follow-through",
			"Tabular numbers",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/split-flap/SplitFlap.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
				label: "use-animation-loop.ts",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "charset",
				kind: "enum",
				default: "alphanumeric",
				options: ["alphanumeric", "letters", "digits", "departures"],
				description:
					"Which glyphs a column walks through on its way to its letter. This is what sets the length of the journey — a digits-only board lands almost immediately, a full alphanumeric one takes its time.",
			},
			{
				name: "flapDuration",
				kind: "number",
				default: 90,
				min: 30,
				max: 300,
				step: 5,
				unit: "ms",
				description:
					"Time for one flap. Under about 50ms the column reads as a blur rather than as discrete cards, which throws away the whole point of the mechanism.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 45,
				min: 0,
				max: 300,
				step: 5,
				unit: "ms",
				description:
					"Delay between one column starting and the next. At 0 the board moves as one slab; a small offset is what makes it sound like a board even in silence.",
			},
			{
				name: "settleBounce",
				kind: "number",
				default: 0.5,
				min: 0,
				max: 1.5,
				step: 0.05,
				description:
					"Overshoot as a flap hits its stop. This is follow-through: the card has mass, so it arrives slightly past and comes back.",
			},
			{
				name: "cardGap",
				kind: "number",
				default: 4,
				min: 0,
				max: 16,
				step: 1,
				unit: "px",
				description: "Space between one card stack and the next.",
			},
			{
				name: "seamWeight",
				kind: "number",
				default: 1,
				min: 0,
				max: 4,
				step: 0.5,
				unit: "px",
				description:
					"The hairline across the middle of a card, where the two halves meet. Kept in the DOM rather than drawn, so the browser snaps it to the pixel grid instead of letting it shimmer on fractional scaling.",
			},
			{
				name: "specular",
				kind: "number",
				default: 0.55,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Light sweeping across a moving flap, brightest edge-on. Without it a flip reads as a rectangle changing shape rather than as a surface turning.",
			},
			{
				name: "perspective",
				kind: "number",
				default: 420,
				min: 120,
				max: 1200,
				step: 20,
				unit: "px",
				description:
					"Depth of the foreshortening. Lower exaggerates the hinge and puts the viewer close to the board; higher flattens it toward a straight fold.",
			},
			{
				name: "cardColor",
				kind: "color",
				default: "#17141d",
				description:
					"Body of the cards. Its own material, not a themed surface — a departure board is a dark object in any room.",
			},
			{
				name: "glyphColor",
				kind: "color",
				default: "#e8e4ee",
				description: "The printed characters.",
			},
		],
	},
	{
		slug: "teletype",
		name: "Teletype",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"A line of type arriving one character at a time, at a rate that varies and with a beat at every mark.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Typewriter",
			"Stepped animation",
			"Loop",
			"Idle animation",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/teletype/Teletype.tsx",
			},
			{
				lang: "ts",
				style: "tailwind",
				file: "hooks/use-animation-loop.ts",
				role: "hook",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "charsPerSecond",
				kind: "number",
				default: 22,
				min: 4,
				max: 90,
				step: 1,
				description:
					"Typing rate before jitter. Above roughly 40 the reader stops perceiving individual keystrokes and starts seeing a wipe.",
			},
			{
				name: "deleteRate",
				kind: "number",
				default: 2.4,
				min: 0,
				max: 6,
				step: 0.1,
				description:
					"Erase rate as a multiple of the typing rate — deleting is never as deliberate as writing. At 0 the line is not erased at all: it is cut, and the next one starts clean.",
			},
			{
				name: "hold",
				kind: "number",
				default: 1500,
				min: 0,
				max: 4000,
				step: 100,
				unit: "ms",
				description:
					"Dwell on a finished line before it is taken away. This is the only window the reader has to actually read it.",
			},
			{
				name: "gap",
				kind: "number",
				default: 420,
				min: 0,
				max: 2000,
				step: 20,
				unit: "ms",
				description: "Empty beat between one line clearing and the next starting.",
			},
			{
				name: "jitter",
				kind: "number",
				default: 0.45,
				min: 0,
				max: 1,
				step: 0.05,
				description:
					"Spread on the per-line rate. At 0 the machine is a metronome, which reads as a progress bar rendered in letters rather than as typing.",
			},
			{
				name: "punctuationPause",
				kind: "number",
				default: 220,
				min: 0,
				max: 800,
				step: 20,
				unit: "ms",
				description:
					"Extra beat after a comma, period, dash or colon. The pause a reader hears at a mark is the silence that follows it, so it lands after the glyph, never before.",
			},
			{
				name: "caret",
				kind: "enum",
				default: "block",
				options: ["block", "bar", "underscore", "none"],
				description: "Shape of the cursor trailing the text.",
			},
			{
				name: "caretBlink",
				kind: "number",
				default: 1.05,
				min: 0.2,
				max: 3,
				step: 0.05,
				unit: "s",
				disabledWhen: { prop: "caret", equals: "none" },
				description:
					"Seconds per blink cycle. The caret holds steady while characters are arriving and only blinks once the line is at rest — a terminal does the same, and the contrast is what makes the typing read as live.",
			},
			{
				name: "loop",
				kind: "boolean",
				default: true,
				description: "Wrap to the first line when the list runs out.",
			},
			{
				name: "reserveSpace",
				kind: "boolean",
				default: true,
				description:
					"Hold the box at the size of the longest line. Turn it off to watch everything below the type walk up and down the page — which is the reason it is on.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				description: "The caret.",
			},
		],
	},
	{
		slug: "kinetic",
		name: "Kinetic",
		category: "Text Animations",
		tier: "pro",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"Type with mass: every glyph is its own spring, and the squash and stretch are read back off that spring rather than authored.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Squash & stretch",
			"Anticipation",
			"Spring",
			"Follow-through",
			"Stagger",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/kinetic/Kinetic.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "stiffness",
				kind: "number",
				default: 620,
				min: 60,
				max: 1400,
				step: 20,
				description: "Spring tension. Higher launches harder and settles sooner.",
			},
			{
				name: "damping",
				kind: "number",
				default: 20,
				min: 4,
				max: 60,
				step: 1,
				description:
					"Spring friction. Low overshoots and rings; high arrives dead, and takes the follow-through with it.",
			},
			{
				name: "mass",
				kind: "number",
				default: 1,
				min: 0.2,
				max: 4,
				step: 0.1,
				description:
					"Weight of a body. Heavier lags further behind its own intent, which is where the whole effect comes from.",
			},
			{
				name: "jumpHeight",
				kind: "number",
				default: 26,
				min: 0,
				max: 90,
				step: 2,
				unit: "px",
				description: "Peak of the jump.",
			},
			{
				name: "anticipation",
				kind: "number",
				default: 7,
				min: 0,
				max: 30,
				step: 1,
				unit: "px",
				description:
					"Depth of the wind-up before the launch, in spring travel. Spent as compression rather than as downward movement — the floor is real, and a body loading its spring squats instead of sinking.",
			},
			{
				name: "windUp",
				kind: "number",
				default: 130,
				min: 0,
				max: 500,
				step: 10,
				unit: "ms",
				disabledWhen: { prop: "anticipation", equals: 0 },
				description: "How long the wind-up takes.",
			},
			{
				name: "squash",
				kind: "number",
				default: 0.62,
				min: 0,
				max: 1.5,
				step: 0.02,
				description:
					"How hard velocity and floor contact deform a body. At 0 the type is rigid and still jumps — which is precisely what weightless motion looks like.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 34,
				min: 0,
				max: 160,
				step: 2,
				unit: "ms",
				description:
					"Delay between one body launching and the next. At 0 the line moves as a slab; the offset is what makes it read as a row of separate objects.",
			},
			{
				name: "interval",
				kind: "number",
				default: 2400,
				min: 200,
				max: 6000,
				step: 100,
				unit: "ms",
				disabledWhen: { prop: "trigger", equals: "hover" },
				description: "Rest between one pass finishing and the next beginning.",
			},
			{
				name: "trigger",
				kind: "enum",
				default: "loop",
				options: ["loop", "hover"],
				description:
					"What starts a pass. Hover also answers focus and touch — a pointer-only trigger is half a component.",
			},
			{
				name: "split",
				kind: "enum",
				default: "character",
				options: ["character", "word"],
				description: "Whether a body is one glyph or one whole word.",
			},
			{
				name: "shadow",
				kind: "boolean",
				default: true,
				description:
					"Contact shadow under each body, tightening as it rises. Without it a jump is ambiguous with a slide.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				disabledWhen: { prop: "shadow", equals: false },
				description: "The contact shadow.",
			},
		],
	},
	{
		slug: "reflow",
		name: "Reflow",
		category: "Text Animations",
		tier: "free",
		addedAt: "2026-08-06",
		pausable: true,
		description:
			"Text whose words keep their identity when the line breaks move — narrow the measure and the sentence travels instead of re-wrapping.",
		dependencies: ["motion", "clsx", "tailwind-merge"],
		cookbook: [
			"Layout animation",
			"Continuity transition",
			"Spatial consistency",
			"Enter / Exit",
			"Stagger",
		],
		variants: [
			{
				lang: "ts",
				style: "tailwind",
				file: "components/registry/reflow/Reflow.tsx",
			},
			UTILS_VARIANT,
		],
		props: [
			{
				name: "columnWidth",
				kind: "number",
				default: 100,
				min: 30,
				max: 100,
				step: 1,
				unit: "%",
				description:
					"Width of the text column as a percentage of its container — the measure. Dragging this is the reflow, with not one word changing.",
			},
			{
				name: "stiffness",
				kind: "number",
				default: 340,
				min: 40,
				max: 900,
				step: 10,
				description: "Spring tension on the travel.",
			},
			{
				name: "damping",
				kind: "number",
				default: 34,
				min: 6,
				max: 80,
				step: 1,
				description: "Spring friction on the travel.",
			},
			{
				name: "stagger",
				kind: "number",
				default: 14,
				min: 0,
				max: 120,
				step: 2,
				unit: "ms",
				description:
					"Delay between one word starting its travel and the next. The index is capped at twenty, so a long paragraph cannot leave its tail sitting still in plain sight.",
			},
			{
				name: "enterScale",
				kind: "number",
				default: 0.82,
				min: 0.2,
				max: 1,
				step: 0.02,
				description: "Size a word enters at and leaves at.",
			},
			{
				name: "wordGap",
				kind: "number",
				default: 0.3,
				min: 0.1,
				max: 0.9,
				step: 0.02,
				unit: "em",
				description:
					"Space between words. A margin rather than a space character, so a word leaving the sentence does not strand the gap that followed it.",
			},
			{
				name: "lineHeight",
				kind: "number",
				default: 1.6,
				min: 1,
				max: 2.6,
				step: 0.05,
				description: "Leading.",
			},
			{
				name: "align",
				kind: "enum",
				default: "left",
				options: ["left", "center", "right"],
				description: "Text alignment.",
			},
			{
				name: "auto",
				kind: "boolean",
				default: true,
				description: "Advance through the phrases on a timer.",
			},
			{
				name: "interval",
				kind: "number",
				default: 3600,
				min: 800,
				max: 9000,
				step: 200,
				unit: "ms",
				disabledWhen: { prop: "auto", equals: false },
				description: "Time on each phrase.",
			},
			{
				name: "traceMoves",
				kind: "boolean",
				default: false,
				description:
					"Tint a word for as long as it is travelling. A debugging affordance that earned its place — it is the only way to prove a word moved rather than being destroyed and re-created somewhere else.",
			},
			{
				name: "accentColor",
				kind: "color",
				default: "#a855f7",
				disabledWhen: { prop: "traceMoves", equals: false },
				description: "The trace tint.",
			},
		],
	},
];
