"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { PreviewProps } from "@/lib/registry/types";

// slug → live preview component, code-split so only the active component loads.
// Register a real component here once its source is dropped into
// components/registry/<slug>/. Unregistered slugs fall back to the reference
// stand-in (see LiveWorkspace), so the full spine works end-to-end regardless.
export const previews: Record<string, ComponentType<PreviewProps>> = {
  threads: dynamic(() => import("./threads/ThreadsPreview"), { ssr: false }),
  grainient: dynamic(() => import("./grainient/GrainientPreview"), { ssr: false }),
  "light-rays": dynamic(() => import("./light-rays/LightRaysPreview"), { ssr: false }),
  "gradual-blur": dynamic(() => import("./gradual-blur/GradualBlurPreview"), { ssr: false }),
  "side-rays": dynamic(() => import("./side-rays/SideRaysPreview"), { ssr: false }),
  "dot-field": dynamic(() => import("./dot-field/DotFieldPreview"), { ssr: false }),
  strands: dynamic(() => import("./strands/StrandsPreview"), { ssr: false }),
  ribbons: dynamic(() => import("./ribbons/RibbonsPreview"), { ssr: false }),
  "morphing-text": dynamic(() => import("./morphing-text/MorphingTextPreview"), { ssr: false }),
  "animated-number": dynamic(() => import("./animated-number/AnimatedNumberPreview"), { ssr: false }),
  "marquee-text": dynamic(() => import("./marquee-text/MarqueeTextPreview"), { ssr: false }),
  "variable-proximity": dynamic(() => import("./variable-proximity/VariableProximityPreview"), { ssr: false }),
  "pixel-transition": dynamic(() => import("./pixel-transition/PixelTransitionPreview"), { ssr: false }),
  "border-glow": dynamic(() => import("./border-glow/BorderGlowPreview"), { ssr: false }),
  "spotlight-shell": dynamic(() => import("./spotlight-shell/SpotlightShellPreview"), { ssr: false }),
  "animated-hamburger": dynamic(() => import("./animated-hamburger/AnimatedHamburgerPreview"), { ssr: false }),
  "morph-dialog": dynamic(() => import("./morph-dialog/MorphDialogPreview"), { ssr: false }),
  "grow-dialog": dynamic(() => import("./grow-dialog/GrowDialogPreview"), { ssr: false }),
  "flip-card": dynamic(() => import("./flip-card/FlipCardPreview"), { ssr: false }),
  "blueprint-card": dynamic(() => import("./blueprint-card/BlueprintCardPreview"), { ssr: false }),
  "corner-letters": dynamic(() => import("./corner-letters/CornerLettersPreview"), { ssr: false }),
  "hover-list": dynamic(() => import("./hover-list/HoverListPreview"), { ssr: false }),
  preloader: dynamic(() => import("./preloader/PreloaderPreview"), { ssr: false }),
  "circle-menu": dynamic(() => import("./circle-menu/CircleMenuPreview"), { ssr: false }),
  "scroll-velocity": dynamic(() => import("./scroll-velocity/ScrollVelocityPreview"), { ssr: false }),
  "letters-pull": dynamic(() => import("./letters-pull/LettersPullPreview"), { ssr: false }),
  constellation: dynamic(() => import("./constellation/ConstellationPreview"), { ssr: false }),
  "plus-grid": dynamic(() => import("./plus-grid/PlusGridPreview"), { ssr: false }),
  "word-reveal": dynamic(() => import("./word-reveal/WordRevealPreview"), { ssr: false }),
  barcode: dynamic(() => import("./barcode/BarcodePreview"), { ssr: false }),
  "sakura-tree": dynamic(() => import("./sakura-tree/SakuraTreePreview"), { ssr: false }),
  "command-palette": dynamic(() => import("./command-palette/CommandPalettePreview"), { ssr: false }),
  "world-map-ascii": dynamic(() => import("./world-map-ascii/WorldMapAsciiPreview"), { ssr: false }),
  "physics-engine": dynamic(() => import("./physics-engine/PhysicsEnginePreview"), { ssr: false }),
  "black-hole": dynamic(() => import("./black-hole/BlackHolePreview"), { ssr: false }),
  "vortex-bloom": dynamic(() => import("./vortex-bloom/VortexBloomPreview"), { ssr: false }),
  aurora: dynamic(() => import("./aurora/AuroraPreview"), { ssr: false }),
  starfield: dynamic(() => import("./starfield/StarfieldPreview"), { ssr: false }),
  "scramble-text": dynamic(() => import("./scramble-text/ScrambleTextPreview"), { ssr: false }),
  "magnetic-button": dynamic(() => import("./magnetic-button/MagneticButtonPreview"), { ssr: false }),
  "shadow-cursor": dynamic(() => import("./shadow-cursor/ShadowCursorPreview"), { ssr: false }),
  "flock-field": dynamic(() => import("./flock-field/FlockFieldPreview"), { ssr: false }),
  "smoke-field": dynamic(() => import("./smoke-field/SmokeFieldPreview"), { ssr: false }),
  "ripple-field": dynamic(() => import("./ripple-field/RippleFieldPreview"), { ssr: false }),
  "file-explorer": dynamic(() => import("./file-explorer/FileExplorerPreview"), { ssr: false }),
  cinders: dynamic(() => import("./cinders/CindersPreview"), { ssr: false }),
  shadowflame: dynamic(() => import("./shadowflame/ShadowflamePreview"), { ssr: false }),
  "long-shadow": dynamic(() => import("./long-shadow/LongShadowPreview"), { ssr: false }),
  specter: dynamic(() => import("./specter/SpecterPreview"), { ssr: false }),
  torchlight: dynamic(() => import("./torchlight/TorchlightPreview"), { ssr: false }),
  dissolve: dynamic(() => import("./dissolve/DissolvePreview"), { ssr: false }),
  "umbral-orrery": dynamic(() => import("./umbral-orrery/UmbralOrreryPreview"), { ssr: false }),
  "shadow-bloom": dynamic(() => import("./shadow-bloom/ShadowBloomPreview"), { ssr: false }),
  tilt: dynamic(() => import("./tilt/TiltPreview"), { ssr: false }),
  sigil: dynamic(() => import("./sigil/SigilPreview"), { ssr: false }),
  lumen: dynamic(() => import("./lumen/LumenPreview"), { ssr: false }),
  "parallax-rail": dynamic(() => import("./parallax-rail/ParallaxRailPreview"), { ssr: false }),
  rift: dynamic(() => import("./rift/RiftPreview"), { ssr: false }),
  unfold: dynamic(() => import("./unfold/UnfoldPreview"), { ssr: false }),
  approach: dynamic(() => import("./approach/ApproachPreview"), { ssr: false }),
  elastic: dynamic(() => import("./elastic/ElasticPreview"), { ssr: false }),
  masonry: dynamic(() => import("./masonry/MasonryPreview"), { ssr: false }),
  hold: dynamic(() => import("./hold/HoldPreview"), { ssr: false }),
  redact: dynamic(() => import("./redact/RedactPreview"), { ssr: false }),
  moire: dynamic(() => import("./moire/MoirePreview"), { ssr: false }),
  dismiss: dynamic(() => import("./dismiss/DismissPreview"), { ssr: false }),
  aperture: dynamic(() => import("./aperture/AperturePreview"), { ssr: false }),
  "split-flap": dynamic(() => import("./split-flap/SplitFlapPreview"), { ssr: false }),
  "intro-animation": dynamic(
    () => import("./intro-animation/IntroAnimationPreview"),
    { ssr: false },
  ),
};
