"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { PreviewProps } from "@/lib/registry/types";

// slug → live preview component, code-split so only the active component loads.
// Register a real component here once its source is dropped into
// components/registry/<slug>/. Unregistered slugs fall back to the reference
// stand-in (see LiveWorkspace), so the full spine works end-to-end regardless.
export const previews: Record<string, ComponentType<PreviewProps>> = {
  waves: dynamic(() => import("./waves/waves-preview"), { ssr: false }),
  grainient: dynamic(() => import("./grainient/grainient-preview"), { ssr: false }),
  "light-rays": dynamic(() => import("./light-rays/light-rays-preview"), { ssr: false }),
  "mask-blur": dynamic(() => import("./mask-blur/mask-blur-preview"), { ssr: false }),
  "side-rays": dynamic(() => import("./side-rays/side-rays-preview"), { ssr: false }),
  "dot-field": dynamic(() => import("./dot-field/dot-field-preview"), { ssr: false }),
  strands: dynamic(() => import("./strands/strands-preview"), { ssr: false }),
  ribbons: dynamic(() => import("./ribbons/ribbons-preview"), { ssr: false }),
  "morphing-text": dynamic(() => import("./morphing-text/morphing-text-preview"), { ssr: false }),
  "animated-number": dynamic(() => import("./animated-number/animated-number-preview"), { ssr: false }),
  "marquee-text": dynamic(() => import("./marquee-text/marquee-text-preview"), { ssr: false }),
  "variable-proximity": dynamic(() => import("./variable-proximity/variable-proximity-preview"), { ssr: false }),
  "pixel-transition": dynamic(() => import("./pixel-transition/pixel-transition-preview"), { ssr: false }),
  "border-glow": dynamic(() => import("./border-glow/border-glow-preview"), { ssr: false }),
  "spotlight-shell": dynamic(() => import("./spotlight-shell/spotlight-shell-preview"), { ssr: false }),
  "animated-hamburger": dynamic(() => import("./animated-hamburger/animated-hamburger-preview"), { ssr: false }),
  "morph-dialog": dynamic(() => import("./morph-dialog/morph-dialog-preview"), { ssr: false }),
  "blueprint-card": dynamic(() => import("./blueprint-card/blueprint-card-preview"), { ssr: false }),
  "corner-letters": dynamic(() => import("./corner-letters/corner-letters-preview"), { ssr: false }),
  "hover-list": dynamic(() => import("./hover-list/hover-list-preview"), { ssr: false }),
  preloader: dynamic(() => import("./preloader/preloader-preview"), { ssr: false }),
  "stagger-menu": dynamic(() => import("./stagger-menu/stagger-menu-preview"), { ssr: false }),
  "letters-pull": dynamic(() => import("./letters-pull/letters-pull-preview"), { ssr: false }),
  constellation: dynamic(() => import("./constellation/constellation-preview"), { ssr: false }),
  "plus-grid": dynamic(() => import("./plus-grid/plus-grid-preview"), { ssr: false }),
  barcode: dynamic(() => import("./barcode/barcode-preview"), { ssr: false }),
  "command-palette": dynamic(() => import("./command-palette/command-palette-preview"), { ssr: false }),
  "world-map-ascii": dynamic(() => import("./world-map-ascii/world-map-ascii-preview"), { ssr: false }),
  "physics-engine": dynamic(() => import("./physics-engine/physics-engine-preview"), { ssr: false }),
  "black-hole": dynamic(() => import("./black-hole/black-hole-preview"), { ssr: false }),
  "vortex-bloom": dynamic(() => import("./vortex-bloom/vortex-bloom-preview"), { ssr: false }),
  aurora: dynamic(() => import("./aurora/aurora-preview"), { ssr: false }),
  starfield: dynamic(() => import("./starfield/starfield-preview"), { ssr: false }),
  "scramble-text": dynamic(() => import("./scramble-text/scramble-text-preview"), { ssr: false }),
  "magnetic-button": dynamic(() => import("./magnetic-button/magnetic-button-preview"), { ssr: false }),
  "shadow-cursor": dynamic(() => import("./shadow-cursor/shadow-cursor-preview"), { ssr: false }),
  "smoke-field": dynamic(() => import("./smoke-field/smoke-field-preview"), { ssr: false }),
  "ripple-field": dynamic(() => import("./ripple-field/ripple-field-preview"), { ssr: false }),
  cinders: dynamic(() => import("./cinders/cinders-preview"), { ssr: false }),
  shadowflame: dynamic(() => import("./shadowflame/shadowflame-preview"), { ssr: false }),
  "long-shadow": dynamic(() => import("./long-shadow/long-shadow-preview"), { ssr: false }),
  specter: dynamic(() => import("./specter/specter-preview"), { ssr: false }),
  torchlight: dynamic(() => import("./torchlight/torchlight-preview"), { ssr: false }),
  dissolve: dynamic(() => import("./dissolve/dissolve-preview"), { ssr: false }),
  "umbral-orrery": dynamic(() => import("./umbral-orrery/umbral-orrery-preview"), { ssr: false }),
  tilt: dynamic(() => import("./tilt/tilt-preview"), { ssr: false }),
  sigil: dynamic(() => import("./sigil/sigil-preview"), { ssr: false }),
  lumen: dynamic(() => import("./lumen/lumen-preview"), { ssr: false }),
  "parallax-rail": dynamic(() => import("./parallax-rail/parallax-rail-preview"), { ssr: false }),
  rift: dynamic(() => import("./rift/rift-preview"), { ssr: false }),
  approach: dynamic(() => import("./approach/approach-preview"), { ssr: false }),
  hold: dynamic(() => import("./hold/hold-preview"), { ssr: false }),
  redact: dynamic(() => import("./redact/redact-preview"), { ssr: false }),
  aperture: dynamic(() => import("./aperture/aperture-preview"), { ssr: false }),
  "split-flap": dynamic(() => import("./split-flap/split-flap-preview"), { ssr: false }),
  "approval-flow": dynamic(() => import("./approval-flow/approval-flow-preview"), { ssr: false }),
  "diff-review": dynamic(() => import("./diff-review/diff-review-preview"), { ssr: false }),
  ledger: dynamic(() => import("./ledger/ledger-preview"), { ssr: false }),
  teletype: dynamic(() => import("./teletype/teletype-preview"), { ssr: false }),
  reflow: dynamic(() => import("./reflow/reflow-preview"), { ssr: false }),
  segmented: dynamic(() => import("./segmented/segmented-preview"), { ssr: false }),
  tether: dynamic(() => import("./tether/tether-preview"), { ssr: false }),
  "inline-edit": dynamic(() => import("./inline-edit/inline-edit-preview"), { ssr: false }),
  crossing: dynamic(() => import("./crossing/crossing-preview"), { ssr: false }),
  cathode: dynamic(() => import("./cathode/cathode-preview"), { ssr: false }),
  "metallic-text": dynamic(() => import("./metallic-text/metallic-text-preview"), { ssr: false }),
  reorder: dynamic(() => import("./reorder/reorder-preview"), { ssr: false }),
  turing: dynamic(() => import("./turing/turing-preview"), { ssr: false }),
  quicksilver: dynamic(() => import("./quicksilver/quicksilver-preview"), { ssr: false }),
  rotunda: dynamic(() => import("./rotunda/rotunda-preview"), { ssr: false }),
  holofoil: dynamic(() => import("./holofoil/holofoil-preview"), { ssr: false }),
  lens: dynamic(() => import("./lens/lens-preview"), { ssr: false }),
  "ascii-engine": dynamic(() => import("./ascii-engine/ascii-engine-preview"), { ssr: false }),
  swarm: dynamic(() => import("./swarm/swarm-preview"), { ssr: false }),
  mirage: dynamic(() => import("./mirage/mirage-preview"), { ssr: false }),
  submerge: dynamic(() => import("./submerge/submerge-preview"), { ssr: false }),
};
